### ISSUE TITLE
node-lambda deploy fails due to quotes in .env

### ISSUE THREAD

**Issue by tracstarr** [openhab/openhab-alexa#10]
The following causes _node-lambda deploy_ to fail. remove the quotes and it works.
EXCLUDE_GLOBS="event.json"

**Comment by digitaldan** [comment]
I have not been able to produce this, although I admit using single quotes would be better.  I'm closing, if you still have this issue or can provide some more logging that shows its a bug in openhab-alexa I will be happy to reopen.
