### ISSUE TITLE
multi user support

### ISSUE THREAD

**Issue by abhitheawesomecoder** [openhab/openhab-alexa#103]
does it support multi user. Where is the code to get user authentication details and pass it to the server?

**Comment by SamuelBrucksch** [comment]
Alexa now can differentiate between users by voice. So if you have multiple accounts on one alexa device, everyone has their own configuration and skills. Also its possible if you have multiple accounts and that feature not enabled if you say 'alexa, switch account'.

So Person 1 for example can install openhab skill and then discover devices and rename them and do whatever.
Person 2 can do the same with either the same or a different openhab cloud account. Or even install the v3 alexa skill as self deployment, it will not conflict with the skill from person 1.

**Comment by lblabr** [comment]
i´m very new to alexa in combination with openhab. i can switch on and off the tv set, may be in future wlan for my sons mobile devices. I would like to say "WLAN SON off" how to do this. My son should not be able to switch it on afterwards. for sure he sould be able to turn on and off the light or change the volume on tv....
