### ISSUE TITLE
[V3] Lambda timeouts

### ISSUE THREAD

**Issue by pahofmann** [openhab/openhab-alexa#108]
I've setup the V3 branch to use with my locally installed openhab 2.4 which is available to the outside via a reverse proxy with basic auth.
Setup was smooth, but the app does not discover any devices.  
Looking at cloudwatch I see that the lambda function always times out:  
```
START RequestId: 5bc03f16-0493-11e9-82b6-79f589f8e736 Version: $LATEST
2018-12-20T20:10:56.073Z	5bc03f16-0493-11e9-82b6-79f589f8e736	Input:
{
    "directive": {
        "header": {
            "namespace": "Alexa.Discovery",
            "name": "Discover",
            "payloadVersion": "3",
            "messageId": "aba919a0-31cf-46fe-ad6c-9cabeb48dc71"
        },
        "payload": {
            "scope": {
                "type": "BearerToken",
                "token": "--TOKEN--"
            }
        }
    }
}

END RequestId: 5bc03f16-0493-11e9-82b6-79f589f8e736
REPORT RequestId: 5bc03f16-0493-11e9-82b6-79f589f8e736	Duration: 15015.24 ms	Billed Duration: 15000 ms Memory Size: 512 MB	Max Memory Used: 23 MB	
2018-12-20T20:11:11.076Z 5bc03f16-0493-11e9-82b6-79f589f8e736 Task timed out after 15.02 seconds
```
If I can provide more information for torubleshooting just let me know.

**Comment by digitaldan** [comment]
It seems as if you are not actually hitting the rest URL of your server, did you change this in the config.js?

**Comment by pahofmann** [comment]
Yes, I set if to the correct URL in the config.js

**Comment by digitaldan** [comment]
There could be many reasons why this is not working, but with out a whole lot more info I don't know how to help.  The rest requests the lambda makes are standard node http requests, no magic there, I would add a few console.log statements to rest.js and see what URL it is trying to request.  Also look out for things like valid SSL certs (if using ssl) and that DNS and ports are correct.
