### ISSUE TITLE
No Devices detected

### ISSUE THREAD

**Issue by querdenker2k** [openhab/openhab-alexa#11]
Hi there,

I installed everything and added 2 Homekit tags to my openhab installation, but alexa does not find any devices. What is going wrong. Can i somewhere look in some logfiles to check out whats going wrong?
please help.

**Comment by digitaldan** [comment]
You can check the log files in Amazon Cloud watch, also I would need to know more about how you setup your instance, are you using amazon login for SSO?  I'm assuming you are attempting to connect directly to you OH instance from the lambda skill?

**Comment by digitaldan** [comment]
@querdenker2k is this still the case or can I close this?

**Comment by querdenker2k** [comment]
I am not using it anymore. So it can be closed.

**Comment by hco** [comment]
I actually have the same problem. I added the tags, and https://myopenhab.org/rest/items?tags=Lighting actually returns some items of Type "Dimmer", "Switch" and "Color".

Should I create a new ticket or should we stick with this one?

**Comment by digitaldan** [comment]
@hco are you running you own hosted version of the app as is the case in this issue?  I take it that  hitting just https://myopenhab.org/rest/items returns your items with the correct tags?  I would open a new ticket if your items are returning ok then, please also state what country/language you are using to help isolate logging on AWS.
