### ISSUE TITLE
Whilst uploading the node-lambda deploy function it tells you nodejs4.3 is no longer supported 

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-alexa#112]
for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs8.10) while creating or updating functions.

In my .env file I have nodejs set to 4.x

Can anyone tell me how to resolve this?

Thanks

**Comment by dastrix80** [comment]
FYI, if i uncomment the nodejs 6 and comment out version 4, it uploads. Then I edit the Lambda in the console and change it back to Version 4. This appears to work fine.

However after ALL of this, I'm unable to discover any devices.

**Comment by digitaldan** [comment]
your env file should have something like `AWS_RUNTIME=nodejs6.10` in it.   As for not discovering devices,  i would need a lot more info on that with console logs from cloudwatch.  Feel free to open another issues for that if you are still having issues. thanks.

**Comment by viseatconcierge** [comment]
Where is the .env file typically located?

**Comment by jsetton** [comment]
@viseatconcierge the .env is no longer used. Please refer to the latest deployment instructions.

https://github.com/openhab/openhab-alexa#general-deployment-instructions

**Comment by viseatconcierge** [comment]
What is a better way to change the runtime to nodejs6.10

**Comment by jsetton** [comment]
The current version of the skill requires node.js 8.10. On top of this, AWS Lambda no longer supports nodejs 6.10 functions. Anyway, the current deployment instructions should remove the necessity to fiddle with nodejs versions.
