### ISSUE TITLE
Cannot read property 'namespace' of undefined at exports.handler 

### ISSUE THREAD

**Issue by redbeardmcg** [openhab/openhab-alexa#113]
I'm able to perform account linking from both the main and v3 branch, but only if the skill is set to v2. From the v3 branch with the skill set to v3 linking fails with the following message:

`TypeError: Cannot read property 'namespace' of undefined at exports.handler (/var/task/index.js:21:26)`

It appears during linking the header property is stuck under "directive":

```
Input:
{
    "directive": {
        "header": {
            "namespace": "Alexa.Authorization",
            "name": "AcceptGrant",
            "messageId": "03df3e28-3247-4ae2-b69c-78ec45d1675d",
            "payloadVersion": "3"
        },
```

Should these events just be ignored? It would be easy to skip them in index.js, but I'm not savvy enough to know if these need to be handled in some manner.

Regards,

-Ryan

**Comment by digitaldan** [comment]
It looks like you have v2 still deployed to your lambda, can you check if v3 is really deployed?  If you look at line 21 in index.js in v3 that does not match up to that log line.
