### ISSUE TITLE
Trouble with sensors

### ISSUE THREAD

**Issue by xibriz** [openhab/openhab-alexa#12]
Hi.

I'm having trouble to discover sensors. Can you see whats wrong in the response from OpenHAB when i run "Discover Devices" from Alexa?

`{ "link": "https://MYHOST/rest/items/tellstick_sensor_79aa59da_4433381_temperature", "state": "-3.8", "stateDescription": { "pattern": "%f °C", "readOnly": true, "options": [] }, "type": "Number", "name": "tellstick_sensor_79aa59da_4433381_temperature", "label": "Outside Temperature", "category": "Temperature", "tags": [ "CurrentTemperature" ], "groupNames": [] }`

**Comment by digitaldan** [comment]
Are you running the Alexa app your self?  Also what are you trying to do with a sensor and Alexa?

**Comment by xibriz** [comment]
I'm trying to get alexa to read me the value.

I have studied the code and I see that this function is not implemented.

**Comment by xibriz** [comment]
And yes, self hosted alexa app on AWS and openhab at home.

**Comment by digitaldan** [comment]
>Can you see whats wrong in the response from OpenHAB when i run "Discover Devices" from Alexa?

If its all self hosted then I don't see how I can help here?  Also this is a SmartHome skill, which is different then a generic Alexa skill, you can't have it read off values.

**Comment by xibriz** [comment]
What about the GetTemperatureReadingRequest

**Comment by digitaldan** [comment]
That is for the thermostat functionality, you can't ask for it specifically,  but when you set a temp, it validates the setting back.  I would read the alexa SmartHome docs to see what's possible. If there are other features we should definitely add them.

**Comment by digitaldan** [comment]
I'm going to close this issue as I do not think there is a problem with the alexa app here.
