### ISSUE TITLE
[v3] Unable to ask for current state

### ISSUE THREAD

**Issue by Flole998** [openhab/openhab-alexa#124]
When asking German Alexa about the state of a lamp/lock/Mediaplayer I get "sorry, the device doesn't support that". I think this is because we don't have retrievable set, I did a quick search through the repo and couldn't find it. Also I couldn't find reportState which would be a requirement for that. I've only done a quick search using the github search function though, it might just not find it.

**Comment by jsetton** [comment]
Looking at the lambda logs, there is no directive received for these requests.

It's not 100% clear in the [API document](https://developer.amazon.com/docs/smarthome/state-reporting-for-a-smart-home-skill.html) but I suspect that requesting for a device status by voice requires Alexa to already know its current status through proactive change reporting which is not currently supported by the skill. Opposed to the Alexa app which requests for state reports to get that information. It is certainly very odd.

**Comment by Flole998** [comment]
I'll try to take care of clarifying this

**Comment by jsetton** [comment]
No need. The confusion is not with what you reported but more how Alexa is supporting this feature. Anyway, this is expected behavior with the current skill version. We will need to revisit this once the skill supports proactive change reporting.

**Comment by Flole998** [comment]
Already have the answer: Querying by voice is not supported for every endpoint. Only Thermostats and locks Support it at the moment

**Comment by digitaldan** [comment]
so should this issue be closed?

**Comment by Flole998** [comment]
Yes most likely, or at least rephrased to "update documentation to make clear only locks and thermostats can be queried by voice" and that it's a limit at Amazon so it's clear for everyone what's going on and why it won't work like probably most people expect it to.

**Comment by Flole998** [comment]
Actually right now the documentation says "You can ask Alexa to turn "Light Switch" on or off as well as ask for its current state." so this should definitely be changed.

**Comment by digitaldan** [comment]
Yep , you are correct, lets keep this open so we can update the readme
