### ISSUE TITLE
Add Color to accepted item types

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#13]
see https://community.openhab.org/t/official-alexa-smart-home-skill-for-openhab-2/23533/15

**Comment by dominicdesu** [comment]
@digitaldan should this already work?
Color items which are tagged with "Lighting" are not available in the alexa openHAB skill, even though they have been available when using the hue emulation?

**Comment by digitaldan** [comment]
Wow,  I really thought I had merged that, you are correct, i did not :-(

I will prepare a new release tomorrow.

**Comment by digitaldan** [comment]
@dominicdesu see #22 , I would think you would prefer that over just basic control?  I wonder if it's worth merging this, or just doing the work to support colors?

**Comment by dominicdesu** [comment]
@digitaldan I would prefer #22 however it is US only ;-) Might take some while until Amazon adds support for German?

**Comment by digitaldan** [comment]
it's a good point,  I will proceed with this first.
