### ISSUE TITLE
Set temperature rounded (up) in confirmation reply after adjusting it

### ISSUE THREAD

**Issue by cubistico** [openhab/openhab-alexa#130]
I have setup my Max! thermostats for control via Alexa, and it works quite well, but I have a strange rounding effect that I don’t know how to get rid of:

I say, "Alexa, set living room temperature to 21.5 degrees".
Alexa replies, "Automatic mode is set to 22 degrees".
However, the thermostat is in fact set to 21.5 degrees (as expected).
Now when I ask, "Alexa, what is the living room temperature set to?",
Alexa replies, "Automatic mode is set to 21.5 degrees".

Could this be a problem in the construction if the confirmation message in the adjust temperature method? 

Note: I am using Alexa in German, but I don't think it's a language specific problem.

**Comment by digitaldan** [comment]
Can you post all the items in your thermostat group please ?

**Comment by cubistico** [comment]
I have 10 thermostat groups, but they are all setup in the same manner as this one:
```
Group LivingRoomThermostat "Wohnzimmer" (LivingRoom) [ "Thermostat" ]
Number LivingRoomThermostat_ActualTemperature "Aktuelle Temperatur" (LivingRoomThermostat) [ "CurrentTemperature" ] {channel="max:wallthermostat:...:actual_temp"}
Number LivingRoomThermostat_SetTemperature "Solltemperatur" (LivingRoomThermostat, allThermostats_SetTemperature) [ "TargetTemperature" ] {channel="max:wallthermostat:...:set_temp"}
String LivingRoomThermostat_ControlMode "Steuermodus" (LivingRoomThermostat, allThermostats_ControlMode) ["homekit:HeatingCoolingMode"] {channel="max:wallthermostat:...:mode"}
```
My first thought was a configuration problem on my side, but since when just asking for the current set temperature, the reply is correct, I can't imagine how. Both commands refer to the same Item, but return different values.

Oh, btw, this happens only when the set temperature is at *.5 degrees – so no problem with integer values.

**Comment by digitaldan** [comment]
Can you post the exact time, timezone and country you are in when you were tying this please.

**Comment by digitaldan** [comment]
sorry, i think i confused myself.  You are are reporting this against our current released version and not our beta V3 version, correct?   In which case ignore my request above about time and timezone. I'm not sure why thats happening, but I will want to wait until our new version is deployed I think to validate if this is still an issue.

**Comment by cubistico** [comment]
Okay. I've applied for the v3 beta, but haven't got an invite yet, so can't test it.

**Comment by digitaldan** [comment]
Let me know if this is still the case with v3, and if so what item name, time, timezone and location so I can easily find it in the logs.

**Comment by cubistico** [comment]
I can confirm that the problem described in this issue is gone with v3. However, the confirmation reply changed in a way, so it does not tell me which control mode the thermostat is currently set to. I assume this was changed on purpose?

However, I am having otherwise big troubles with v3. Although I can set the temperature of my thermostat, it's not possible to query anything from it like set or actual temperature. Alexa always replies that there's no reaction from the device. Even worse, Alexa claims not to know my groups and device names, and most of the devices are displayed as offline in the app.

Do I need to update the cloud connector? Or did I miss anything else?

**Comment by digitaldan** [comment]
>it does not tell me which control mode the thermostat is currently set to. I assume this was changed on purpose?

No, we report back what the thermostat reports and the Alexa service decides what to say back to you.
 
I will take a look at the responses since i assume they are around now, but in the future can you please add item name, time, timezone and location so I can easily find it in the logs.  There are a lot of logs and it saves me time to not have to search through them all.

**Comment by digitaldan** [comment]
If you look at the response below, you will notice that the "thermostatMode" object is missing a value, I'm not sure why yet.

```"context": {
        "properties": [
            {
                "namespace": "Alexa.TemperatureSensor",
                "name": "temperature",
                "value": {
                    "value": 20.3,
                    "scale": "CELSIUS"
                },
                "timeOfSample": "2019-02-13T17:08:21.352Z",
                "uncertaintyInMilliseconds": 0
            },
            {
                "namespace": "Alexa.ThermostatController",
                "name": "targetSetpoint",
                "value": {
                    "value": 19,
                    "scale": "CELSIUS"
                },
                "timeOfSample": "2019-02-13T17:08:21.352Z",
                "uncertaintyInMilliseconds": 0
            },
            {
                "namespace": "Alexa.ThermostatController",
                "name": "thermostatMode",
                "timeOfSample": "2019-02-13T17:08:21.352Z",
                "uncertaintyInMilliseconds": 0
            },
            {
                "namespace": "Alexa.EndpointHealth",
                "name": "connectivity",
                "value": {
                    "value": "OK"
                },
                "timeOfSample": "2019-02-13T17:08:21.352Z",
                "uncertaintyInMilliseconds": 0
            }
        ]
    },```

**Comment by cubistico** [comment]
From the setpoint value, this looks like one of the devices that I cannot control any more, because Alexa says there's no reaction. Once more with item name, time, timezone and location of the one I'm playing with:
gOfficeThermostat, 18:26 CET, DE

**Comment by cubistico** [comment]
Any hint why all devices are non-reactive in the Alex app? When I select any device, the app gets stuck on "Waiting for openHAB". But on myopenhab.org, everything looks okay, and I can access my openHAB from there.

**Comment by digitaldan** [comment]
So the MAX thermostat modes are translating correctly to Alexa, and this may be causing response issues. In v3 Alexa is much more sensitive to response values.  I will look into this a bit more

**Comment by cubistico** [comment]
Sorry, I don't get it. Translating correctly causes issues? Translating what? Is this a typo?

**Comment by digitaldan** [comment]
No, it not a typo 
https://github.com/openhab/openhab-alexa/blob/v3/utils.js#L26

**Comment by digitaldan** [comment]
So it looks like MAX!  thermostat modes are: 
`AUTOMATIC/MANUAL/BOOST/VACATION `
where Alexa v3 modes are:
`AUOT/COOL/HEAT/ECO/OFF`

I don't see how we map MAX! to Alexa, so I would remove the `["homekit:HeatingCoolingMode"]` tag from the mode so Alexa does not pick it up,  and then run the discovery process again.  You may need to delete the thermostat first through the Alexa app and run discovery, i don't know if it will pick up the change otherwise.

I am open to other suggestions, but the modes Alexa has are immutable, we can't change or add them, see https://developer.amazon.com/docs/device-apis/alexa-property-schemas.html#thermostat-mode

I may also look to default to OFF or something if we can't translate a returned mode so this doesn't break other functionality. 

Curious how mode and Alexa worked for you in v2?

**Comment by cubistico** [comment]
This is really amazing, because I could swear that Alexa even knew about control mode MANUAL which doesn't even exist in you list?!

**Comment by cubistico** [comment]
> No, it not a typo

It was. You edited in the "not" afterwards! Argh! :-)

**Comment by digitaldan** [comment]
>It was. You edited in the "not" afterwards! Argh! :-)

Yes, I did edit it seconds after i posted, but i did not realize that was what was confusing you.

>This is really amazing, because I could swear that Alexa even knew about control mode MANUAL which doesn't even exist in you list?!

I'm not sure it is, v2 only supported 3 modes ,  AUTO, COOL, HEAT, (no OFF)  and I believe at one point they allowed you to report arbitrary values, but then deprecated that.  Since there was no mode control, i don't think they cared much about the response, but now that it is designed for both command and reporting they now care about the exact state.  You have the option of mapping your own custom values, so if you wanted to map AUTO="AUTOMATIC" in the metadata on an item, it would at least report that mode.  See the v3 readme for instructions.

**Comment by cubistico** [comment]
After reverting back to the public release version, I can report the following behaviour:

- If a thermostat is set to automatic mode, Alexa replies, "Automatic mode is set to 21 degrees"
- If a thermostat is set to manual mode, Alexa replies, "Manual is set to 21 degrees"
Obviously, Alexa recognizes the AUTOMATIC mode, and for the other modes, Alexa just uses the word as provided by the device. Actually, I think this is an excellent solution, and I find it a bit disappointing that it wouldn't work in v3 any more.

Other than that, I have the same connection problems with the public version now, so it seems not to be connected to v3. Unless there is some kind of cache or something that needs to be cleared?

**Comment by cubistico** [comment]
I've been able to solve the connections problems by deactivating the skill, deleting all devices and groups from Alexa, reactivating the skill, and rediscovering all devices. Somewhere I had read that the v3 skill would migrate my devices to v3 somehow – was that a misunderstanding on my side? Is it generally required to delete and rediscover all devices?

**Comment by cubistico** [comment]
> I'm not sure it is, v2 only supported 3 modes , AUTO, COOL, HEAT, (no OFF) and I believe at one point they allowed you to report arbitrary values, but then deprecated that.

Looking at https://github.com/openhab/openhab-alexa/blob/faf78bdf61b427bc1d48dc06128166ed25101863/utils.js#L50-L69 I suppose this tries to map the mode, but if that's not possible, it returns it unmapped value. While in the v3 code, a mode value that cannot be mapped gets lost.

I would prefer to keep the old behaviour.

**Comment by digitaldan** [comment]
Yes, this is where we would send the arbitrary value since at the time it was written Alexa allowed un-mapped values.  They deprecated that feature in their docs, but we never changed our code to enforce it.
>I would prefer to keep the old behaviour, if that is possible.

We can try, but according to the docs will not work, but I guess if it kept working in v2, maybe it will work in v3.  I'll make the change and let you know when its up.

**Comment by digitaldan** [comment]
Ok, i have deployed a version which will pass the original result if a mapping is not found. Make sure to give me the item name and time when you test so i can take a look at the logs

**Comment by digitaldan** [comment]
>Somewhere I had read that the v3 skill would migrate my devices to v3 somehow

Glad to hear that devices are working.  When we launch this out of beta, it should be transparent to users, unfortunately it seems the Alexa beta program treats the beta version as a second skill. In any case, do you have a item name (non thermostat) and approximate time of a device that was not working until you deleted it?  I want to see if there are any logs around it.  Thanks.

**Comment by cubistico** [comment]
Thanks for the explanation. 
I'm afraid I don't have anything I can give you. I played mostly with the thermostats. Other than that, I have only a few hue lights set up for Alexa yet. 
I would like to use v3 with my other account, but I found out that it's not as easy as I thought to use multiple profiles on an Echo device. I will try and reset one of my devices to configure the other Amazon account on it. Do you know if both of them could be connected to the same openHAB cloud account? Otherwise, I'll also have to setup another cloud account first.

**Comment by digitaldan** [comment]
>Do you know if both of them could be connected to the same openHAB cloud account? Otherwise, I'll also have to setup another cloud account first.

This should not be a problem, you can link as many Alexa accounts to a single myopenhab account as you wish.  

Let me know how the thermostat mode reports now, i have not committed my changes yet, i want to wait to see if it works

**Comment by cubistico** [comment]
I'll do it as soon as possible, but it may take 1 or 2 days.

**Comment by cubistico** [comment]
> Ok, i have deployed a version which will pass the original result if a mapping is not found. Make sure to give me the item name and time when you test so i can take a look at the logs

I've made  a few tests with Item group gOfficeThermostat between 17:00 and 17:02 CET, region DE.

Asked for the current set temperature, Alexa replies 
* "Automatic mode is set to 21 degrees" when mode is AUTOMATIC 
* "_device_name_ is set to 19 degrees" when mode is MANUAL

It seems the unknown mode value is either not received or simply dropped by Alexa.

Trying to set the mode (around 17:08-17:10 CET):
* "Alexa, set mode of _device_name_ to automatic" - reply is "It is set to automatic" - but its not true: mode is not altered
* "Alexa, set mode of _device_name_ to manual" - reply is "I don't know how to make this setting for _device_name_" - which is totally acceptable

**Comment by digitaldan** [comment]
So it sounds like Alexa will repeat what we send back, the rest of the what you posted is expected. 

>To me, this seems like worth opening an extra issue

No need, I have added the ability for a user to specify what supported modes should be discovered, see #133
