### ISSUE TITLE
AVS Notification Support

### ISSUE THREAD

**Issue by gdgeist** [openhab/openhab-alexa#140]
AVS service allows Notifications.  While audible notifications through the speech channel or amazonechocontrol binding are available - visual notifications in line with what the Amazon Echo ecosystem offers simplifies a path to visual notifications.  ESP/Arduino  MQTT based homegrown solutions aside most with this binding active would use this feature.

**Comment by digitaldan** [comment]
This is a Duplicate of #49 .  If we want to re-open that, then that's ok, but let's not create another issue.
