### ISSUE TITLE
[V3] Mode, Range, and Toggle  support

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#142]
These are US only atm, but looks very cool

https://developer.amazon.com/blogs/alexa/post/2ccbb04d-47c0-41c8-92fe-feb581deb676/understanding-the-updated-smart-home-skill-api-preview

**Comment by jsetton** [comment]
Based on the examples provided in the API documentation, here is my proposed sketch for these interfaces:


[Mode Controller](https://developer.amazon.com/docs/device-apis/alexa-modecontroller.html#example-discovery-response)
```js
Group gWasher "Washer" {alexa="Endpoint.Other"}
Number WasherCycle "Washer Cycle" (gWasher) {alexa="ModeController.mode" [Normal=0,Delicates=1,supportedModes="Normal:Cottons,Delicates:Knites",friendlyNames="Wash Cycle,Wash Setting",ordered=false,local="en-US"]}
Number WasherTemperature "Washer Temperature" (gWasher) {alexa="ModeController.mode" [Cold=0,Warm=1,Hot=2,supportedModes="Cold:Cool,Warm,Hot",friendlyNames="Wash Temperature,assetId:Setting.WaterTemperature",ordered=true,local="en-US"]}
```

[Range Controller](https://developer.amazon.com/docs/device-apis/alexa-rangecontroller.html#example-discovery-response)
```js
Number BasementFan "Basement Fan" {alexa="RangeController.rangeValue" [supportedRange="1:10:1",presets:10="assetId:Value.Maximum,assetId:Value.High,Highest",friendlyNames"assetId:Setting.FanSpeed",locale="en-US"]}
```

[Toggle Controller](https://developer.amazon.com/docs/device-apis/alexa-togglecontroller.html#discovery-response)
```js
Switch TowerFan "Tower Fan" {alexa="ToggleController.toggleState" [friendlyNames="assetId:Setting.Oscillate,Rotate",local="en-US"]}
```

These are indeed very powerful. Regarding the [asset ids](https://developer.amazon.com/docs/device-apis/resources-and-assets.html#global-alexa-catalog), this is a new feature part of the capability ressources included in these interfaces.

**Comment by digitaldan** [comment]
Thanks @jsetton I like it!  i think once you read the api docs it make sense, for users we will need to have lots of examples  and a tables of assetIds  in our usage doc to clearly explain.
