### ISSUE TITLE
[v3] Remove v2 logic from code 

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#143]
@jsetton I think we can remove the compatibility layer for v2.  According to the Alexa docs, during the transition to v3,  our v2 lambda will continue to function until users get migrated over.

https://developer.amazon.com/docs/smarthome/smart-home-skill-migration-guide.html#create-a-new-lambda

WDYT?

**Comment by digitaldan** [comment]
And by compatibility layer i mean removing https://github.com/openhab/openhab-alexa/blob/v3/ohConnectorV2.js (we still support v2 tags of course)

**Comment by jsetton** [comment]
Actually, you are correct. Based on the blog post below, it seems that having the old v2 lambda function available is just needed for the migration period until all users' devices get updated to point to the new function. It seems that it shouldn't take longer than 24 hours. Anyway, we can certainly remove the v2 code, along with its test cases, from the v3 branch.

https://developer.amazon.com/blogs/alexa/post/87c5cf67-1f27-42d3-a07a-e4f559674392/how-to-migrate-your-alexa-skill-to-the-updated-smart-home-skill-api

**Comment by jsetton** [comment]
I can submit a PR if you want. There are some minor cleanup to do in the other files as well.

**Comment by digitaldan** [comment]
Sounds good, i also have some cleanup work I want to update today.
