### ISSUE TITLE
[v3] Conversion from V2 skill?

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-alexa#159]
Hi All

There appears to be no documentation on how to do this.  I would assume that all is required is an update of the payload version from V2 to V3. If so, once done I cannot discover a V2 device based on a [ "Lighting" ] tag.

The item is 'Garage' and is a Switch

Thanks

**Comment by dastrix80** [comment]
CloudWatch says so:

2019-02-28T20:48:26.458Z 8e3a38be-804e-427c-a161-12b86c5c8448 TypeError: Cannot read property 'namespace' of undefined
at exports.handler (/var/task/index.js:21:25)

**Comment by digitaldan** [comment]
Hi, i'm not sure what steps you are taking to move to v3?  Are you using the V3 branch ?  Master is still v2 while we beta test our v3 changes.  That error would indicate you are still using the v2 code.

>This type of information would be great for people who arent developers.

V3 is still in very active development and is not ready for simple deployments.  Once we have finished, moving to v3 should be seamless and not require much info at all.

**Comment by dastrix80** [comment]
Hi Dan, understood. Yes I am still using the V2 branch. I guess I need to redeploy to AWS as I'm using my own private cloud instance

Regards

**Comment by dastrix80** [comment]
Hi Dan

Ive cloned the v3 branch to my server and edited the .env and config files as per your v3 notes.

I receive this error on deploy:


root@netsecure:/var/www/openhab-alexa# sudo node_modules/node-lambda/bin/node-lambda deploy
Generating zip file
(node:5819) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
/var/www/openhab-alexa/node_modules/node-lambda/lib/main.js:117
      throw err;
      ^

Error: Command failed: zip -roq /tmp/openhab-1551780920666.zip * -x '.git' -x '*/.*' -x '*/*.log' -x 'event.json'
/bin/sh: 1: zip: not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)

**Comment by dastrix80** [comment]
Hi Dan

ive deployed the V3 skill and lambda. When I go to authorise the skill on my device, it diverts to myopenhab.org for authorisation instead of my OpenHab Cloud private server.

Here is the config.js

```

/**
* Default options, copy to config.js for deployment
* host
*    REST https host
* port
*    REST https port
* userpass
*    Optional username:password for the REST server
*    by default oauth2 tokens will be used for authentication, uncomment this
*    to use standard BASIC auth when talking directly to a openHAB server.
* path
*    Base URL path for openHAB items
*
**/
module.exports = {
    //userpass: 'user@domain:password',
    host: 'nsautomate.ddns.net',
    port: 443,
    path: '/rest/items/',
};

```

Any suggetions?

**Comment by digitaldan** [comment]
I saw emails with new comments, but i don't see them here, i'm guessing you deleted?  Can this issue be closed?

**Comment by dastrix80** [comment]
Hi Dan, yes I deployed it succesfully
