### ISSUE TITLE
[v3] Using item commandOptions and stateDescription

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#161]
The openHAB core (formally ESH) added commandOptions and stateDescription to the item description in January, see https://github.com/eclipse/smarthome/pull/5131.  

This exposes the preset options for item commands/states that have existed for a while, but were not easily used by UI's using the rest interface, but are now.  For example, I have a String item which represents the current state of my logitech harmony remote.  If you send it a string, it will change to that current activity (like "Watch TV"). 

 I could see this being useful for Alexa channelControllers, modeController and possibly others.

Here's a snipit from from the /rest/items call:
```json
{
        "link": "https://myopenhab.org/rest/items/HarmonyHubMovieRoomActivity",
        "state": "PowerOff",
        "stateDescription": {
            "pattern": "%s",
            "readOnly": false,
            "options": [
                {
                    "value": "PowerOff",
                    "label": "PowerOff"
                },
                {
                    "value": "TiVo",
                    "label": "TiVo"
                },
                {
                    "value": "APPLETV",
                    "label": "APPLETV"
                },
                {
                    "value": "Game",
                    "label": "Game"
                },
                {
                    "value": "Roku",
                    "label": "Roku"
                }
            ]
        },
        "commandDescription": {
            "commandOptions": [
                {
                    "command": "PowerOff",
                    "label": "PowerOff"
                },
                {
                    "command": "TiVo",
                    "label": "TiVo"
                },
                {
                    "command": "APPLETV",
                    "label": "APPLETV"
                },
                {
                    "command": "Game",
                    "label": "Game"
                },
                {
                    "command": "Roku",
                    "label": "Roku"
                }
            ]
        },
        "editable": false,
        "type": "String",
        "name": "HarmonyHubMovieRoomActivity",
        "tags": [],
        "groupNames": []
    },
```

**Comment by jsetton** [comment]
I am already using stateDescription option for ModeController implementation 😄 I wasn't aware of commandDescriptions.

**Comment by digitaldan** [comment]
Could be useful too for thermostat modes when nothing is passed by the user:
```json
 {
                "link": "https://myopenhab.org/rest/items/F2_Hallway_HVAC_Mode",
                "state": "0",
                "stateDescription": {
                    "pattern": "%s",
                    "readOnly": false,
                    "options": [
                        {
                            "value": "0",
                            "label": "Off"
                        },
                        {
                            "value": "1",
                            "label": "Heat"
                        },
                        {
                            "value": "2",
                            "label": "Cool"
                        },
                        {
                            "value": "3",
                            "label": "Auto"
                        }
                    ]
                },
                "commandDescription": {
                    "commandOptions": [
                        {
                            "command": "0",
                            "label": "Off"
                        },
                        {
                            "command": "1",
                            "label": "Heat"
                        },
                        {
                            "command": "2",
                            "label": "Cool"
                        },
                        {
                            "command": "3",
                            "label": "Auto"
                        }
                    ]
                },
                "metadata": {
                    "alexa": {
                        "value": "ThermostatController.thermostatMode",
                        "config": {
                            "HEAT": 1,
                            "AUTO": 3,
                            "COOL": 2,
                            "OFF": 0
                        }
                    }
                },
                "editable": false,
                "type": "Number",
                "name": "F2_Hallway_HVAC_Mode",
                "label": "Mode",
                "tags": [],
                "groupNames": [
                    "F2_Hallway_HVAC",
                    "HVAC_Mode"
                ]
            },
```

**Comment by digitaldan** [comment]
>I am already using stateDescription option for ModeController implementation 😄 I wasn't aware of commandDescriptions.

Yes, my bad, state descriptions where of course there, this added only commandDescriptions.

**Comment by jsetton** [comment]
I understand the difference between the two properties from the OH side but when will they be different? The only thing I can see is if states not defined use commands.

**Comment by digitaldan** [comment]
Speaking of modeController,  i think i remember this allowed you to specify more then one name for the action?  There is a synonyms meta property like: `{ synonyms="Toilets,WC,Restroom" }` . This is being used by Habot atm, see  https://community.openhab.org/t/habot-walkthrough-2-n-semantic-tagging-item-resolving/55651 .  we might want to think about using it.

**Comment by digitaldan** [comment]
>I understand the difference between the two properties from the OH side but when will they be different? The only thing I can see is if states not defined use commands.

I have not looked into it yet, but i would guess it can be defined differently by the thing, either in its thing.xml file or dynamically by the binding.

**Comment by jsetton** [comment]
> The openHAB core (formally ESH) added commandOptions and stateDescription to the item description in January, see eclipse/smarthome#5131.

Based on my understanding of that PR, it seems that commandOptions is just an alternative to statesDescription which is design primarily for UI purpose. So I am not sure if there is a need to support it if we already have statesDescription.

**Comment by jsetton** [comment]
> Could be useful too for thermostat modes when nothing is passed by the user:

I actually initially tried adding the support for thermostat but realized this is actually way harder to do then with ModeController as thermostat modes are pre-defined and cannot be remap on the Alexa side. 

So between the different number/string item types and item state description options values and label names, it makes it hard to determine the proper mapping, unless we start cataloging the different states. If there was a naming convention that was enforced, that would certainly make it easier to achieve. 

This is the same issue with InputController as all the values are pre-defined. I guess using mode, range and toggle controllers might be the way to go to include all the customization on the OH side supported. We could create/update some of the v2 style labels to accommodate for this. That is actually one of the reasons why Amazon added these capabilities.

Just to compare with the example you provided, here is how the nest 2.x binding report the thermostat mode:

```
{
  "link": "http://localhost:8090/rest/items/ThermostatHVACMode",
  "state": "HEAT",
  "stateDescription": {
    "pattern": "",
    "readOnly": false,
    "options": [
      {
        "value": "OFF",
        "label": "off"
      },
      {
        "value": "ECO",
        "label": "eco"
      },
      {
        "value": "HEAT",
        "label": "heating"
      },
      {
        "value": "COOL",
        "label": "cooling"
      },
      {
        "value": "HEAT_COOL",
        "label": "heat/cool"
      }
    ]
  },
  "editable": false,
  "type": "String",
  "name": "ThermostatHVACMode",
  "label": "HVAC Mode",
  "category": "climate",
  "tags": [
    "homekit:HeatingCoolingMode"
  ],
  "groupNames": []
}
```

On a side note, you can use `binding="zwave"` for your thermostat mode item setup 😄

**Comment by jsetton** [comment]
One thing that came to mind. Is there a way to determine what binding 1.x or 2.x a specific item is using? For 2.x, I guess we could retrieve the channel metadata selector. So for thermostat mode, we could determine the custom binding maps that way.

```
"metadata": {
  "channel": {
    "value": "nest:thermostat:account:foobar:mode"
  }
}
```

**Comment by digitaldan** [comment]
>On a side note, you can use binding="zwave" for your thermostat mode item setup 😄

Yes, although mine are actually https://github.com/digitaldan/openhab2-addons/tree/venstar-jetty/addons/binding/org.openhab.binding.venstarthermostat  :-)  

>One thing that came to mind. Is there a way to determine what binding 1.x or 2.x a specific item is using?

Not off the top of my head, would need to do a little research.

**Comment by jsetton** [comment]
So the support for stateDescription is included in the ModeController interface. As I mentioned previously, I don't believe trying to add support for pre-defined Alexa states capability interfaces is worth it since there isn't much of a standard naming convention between bindings for a given capability unless you have any idea on how to implement.

In terms of commandOptions, do we want to add it as a backup of stateDescription? Although based on my understanding the former cannot exist unless the latter does.

Regarding the ability to determine bindings, we could just stick to retrieving the channel meta property. That would cover the 2.x bindings at least. What do you think? This would be useful for the thermostat mode capability at the moment.

Last, related to the synonyms meta property, do you think we should retrieve that value as well to use as default friendlyNames if not defined in parameter?

**Comment by digitaldan** [comment]
> I don't believe trying to add support for pre-defined Alexa states capability interfaces is worth it since

I don't either, the more i looked at them, the less it seemed to benefit this use case. 

>That would cover the 2.x bindings at least.

I think this is fine, users can always manually set what they need

>do you think we should retrieve that value as well to use as default friendlyNames if not defined in parameter?

I think it would nice to use them if present, but ignore them if the user specifies friendlyNames in the alexa conifg.

**Comment by jsetton** [comment]
Ok I will add these to the next PR including the Equalizer Controller support 😄 

> I think it would nice to use them if present, but ignore them if the user specifies friendlyNames in the alexa conifg.

The order for friendlyNames, depending on availability, would be (1) alexa meta config, (2) synonym meta property, (3) item label

**Comment by jsetton** [comment]
@digitaldan I believe this issue can be closed unless you think otherwise.
