### ISSUE TITLE
[V3] Alexa Skills Kit CLI Deployment Support

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#170]
We should probably migrate the skill deployment to use the [ASK CLI](https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html). This will allow an all-in-one approach that will deploy the smart home skill along with its lambda function at the same time. Moreover, it makes it easier to deploy to various regions in one go and once we decide to implement Custom Intent Support (#164), the intent models will be able to be stored in the repository.

**Comment by digitaldan** [comment]
👍

**Comment by jsetton** [comment]
@digitaldan I didn't want to respond on the main beta thread. Have you try to use the ASK CLI beta test subcommands? Maybe the [list beta testers](https://developer.amazon.com/docs/smapi/ask-cli-command-reference.html#list-beta-testers-subcommand) subcommand might still return a list of users.

**Comment by digitaldan** [comment]
It looks like when the beta is over, it completely wipes out the previous beta test.  I did not try the skills api (have not hooked it up to beta) , but in the web UI, everything was gone.

**Comment by jsetton** [comment]
You don't need to hook it up. The api subcommands I mentioned above aren't related to the skill deployment. You just need to specify the skill id when calling the command. It is worth a shot but if you don't see in the web UI, the underlying data is probably gone as well.
