### ISSUE TITLE
[v3] Dimmer state is not properly restored when turned back on

### ISSUE THREAD

**Issue by thewilli** [openhab/openhab-alexa#173]
Consider the following Dimmer definition from the usage guide:

```plain
Dimmer LightDimmer "Light Dimmer" {alexa="PowerController.powerState,BrightnessController.brightness" [category="LIGHT"]}
```

The following steps lead to an inconsistency. Best done with the Alexa App:

1. Set the brightness to a non-zero non-maximum value
2. Turn the light off
3. Turn the light back on
4. The brightness displayed in the app equals to the previous value, while the one in OH is always 100%

It would be great if the previous brightness could be restored properly (that's what the offical Tradfri Skill seems to do), or if the behavior would be configurable without adding custom rules for each bulb.

**Comment by digitaldan** [comment]
Hi Willi,  just want to make clear the scenerio you are describing. 

You are doing this in the mobile/web app and not with voice control?

this is what I think we are sending...
>1. Set the brightness to a non-zero non-maximum value

Alexa sends a number (say 50) to "LightDimmer"
>2. Turn the light off

Alexa sends OFF to "LightDimmer"
>3. Turn the light back on

Alexa send ON to "LightDimmer"

>It would be great if the previous brightness could be restored properly 

I would think this is up to openHAB to control, not our skill.  When the item receives the ON command, its up to the binding that the item/channel is linked to  to decide what to do.  For example, my Z-wave lights turn on to the last level they were set at, so it works as you would want, but this was a setting in my zwave configuration.  Also the skill does not keep item state between requests, so it does not know what the last level was.

>>4. The brightness displayed in the app equals to the previous value, while the one in OH is always 100%

I'm not sure why this is, other then the app is not asking for a state report?  I don't use the mobile app much for control.

If you could report the exact item name, exact time,  and time zone, it would make it easier for me to look in the logs and report exactly what was being sent and received.

**Comment by thewilli** [comment]
> You are doing this in the mobile/web app and not with voice control?

The strange thing is that it is not equally reproducible using voice control instead of the app 😕 

>>  It would be great if the previous brightness could be restored properly

> I would think this is up to openHAB to control, not our skill

The developer in me would agree with you at once. Still, there is the possible inconsistency where the Alexa app displays a value different from the OH one. The question may be if this was important enough to care about.

> If you could report the exact item name, exact time, and time zone, it would make it easier for me to look in the logs and report exactly what was being sent and received.

I'll try to bundle this for you.

**Comment by digitaldan** [comment]
>Still, there is the possible inconsistency where the Alexa app displays a value different from the OH one.

When you view a device in the Alexa app it sends a 'ReportState' message to the skill, we query the item and return back whatever openHAB says the item state is.  If the light state changed from OFF to ON,  somehow OH reported a % back.  I can't think of another explanation, but next time it happens let me know the times and names and maybe we can get to the bottom if it. If you have an item name I can probably find todays incident.

**Comment by jsetton** [comment]
To add to @digitaldan, it is important to note that the state in the Alexa app is polled from OH opposed of being proactively pushed by OH. So whenever the state changes in OH, the state in the Alexa app will not necessarily change right away especially if the app is already showing a specific item. In that event, the first state is polled and any subsequent state changes on the OH side wouldn't show in the app unless a refresh is requested by the user.

**Comment by jsetton** [comment]
@thewilli have you experienced any more state inconsistency since then?
