### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#174]
We need to start collecting usage examples for the usage doc.  Let's add them to this issue. Please try and use generic names and labels. Lets also add the sample utterances that can be used on those items.

**Comment by digitaldan** [comment]
as mentioned in https://github.com/openhab/openhab-alexa/issues/123#issuecomment-473709061

```plain
// Dimmable Light with 3-step CT support (like Tradfri)
Group  AlexaBulb            "My Fake Light"             {alexa="Endpoint.Light"}
Dimmer AlexaBulb_Brightness                 (AlexaBulb) {alexa="BrightnessController.brightness,PowerController.powerState"}
Dimmer AlexaBulb_Color                      (AlexaBulb) {alexa="ColorTemperatureController.colorTemperatureInKelvin" [increment=50]}
```

`"Alexa turn My Fake Light On"`
`"Alexa turn My Fake Light Green"`

**Comment by dastrix80** [comment]
May you please add Lock support in your examples.

**Comment by jsetton** [comment]
@digitaldan I don't think this example is correct based on the utterances you listed. If I go by the OH items definition that @thewilli provided, this would define a dimmable light that has **white shade** color temperature capability. So the proper utterance would be:

_Alexa, turn My Fake Light On_
_Alexa, set My Fake Light to daylight_
_Alexa, make My Fake Light warmer_

In order to have color control, the brightness dimmer needs to be converted to a color item:
```
Group  AlexaBulb            "My Fake Light"             {alexa="Endpoint.Light"}
Color  AlexaBulb_Color                      (AlexaBulb) {alexa="BrightnessController.brightness,PowerController.powerState,ColorController.color"}
Dimmer AlexaBulb_ColorTemperature           (AlexaBulb) {alexa="ColorTemperatureController.colorTemperatureInKelvin" [increment=50]}
```

**Comment by digitaldan** [comment]
Good catch, thanks!

**Comment by thewilli** [comment]
> If I go by the OH items definition that @thewilli provided, this would define a dimmable light that has white shade color temperature capability.

@jsetton yes, you're right. I should have made that clearer. The intension was to setup a bulb that explicitly only supports a limited variety of color temperatures, just like the Tradfri bulbs do.

**Comment by dastrix80** [comment]
Hi Guys

Im still using V2 tags, Lighting specifically. Recently nothing has worked, discoveries failing etc. Should I be removing all V2 tags and going over to V3? Im confused as to why its suddenly broken.

Cheers

**Comment by jsetton** [comment]
@dastrix80 it should work with V2 tags. You should at least see your Alexa-enabled devices listed under your Alexa account. If this is related to beta testing, I would recommend posting in the relevant thread #123 with a sample of the items not working along with the utterance you may have used and time you tried. I am not sure which v3 version is currently rolled out.

**Comment by jsetton** [comment]
I just merged the smart bulb examples to the usage documentation. I don't see any other examples to add at this point. Closing for now until someone has additional examples that need to be added.
