### ISSUE TITLE
Determine calling echo

### ISSUE THREAD

**Issue by jlippold** [openhab/openhab-alexa#176]
I'm wondering if this project can determine which device heard the command and trigger different results.

For example, I have multiple TV's and I currently use [this emulator](https://github.com/armzilla/amazon-echo-ha-bridge) and name the devices "Bedroom TV, Livingroom TV, etc.." so the TV's are just hue light switches according to alexa. I'm hoping I can say "Turn on the TV" and have it turn on the correct TV based on which echo heard it.

I'm hoping that since is a Smart Home Skill and not an emulator, that it's possible as I've seen other skills do it. Such as [lexigram](https://github.com/m0ngr31/kanzi)

Thanks in advance

**Comment by jsetton** [comment]
@jlippold you can actually accomplish this by using the v3 skill implementation and the [Alexa-enabled group](https://developer.amazon.com/blogs/alexa/post/0a55ae8a-1f39-411f-a3ca-6a19be80b2f3/now-available-routines-alexa-enabled-groups-and-smart-home-device-state-in-the-amazon-alexa-app) feature.

Basically, you define a TV category endpoint on the OH side and than attached the Living Room TV device to your echo device located in your living room via the Alexa app. The endpoint can either be a single device for just controlling the power or you can set a group allowing to control different abilities (e.g. power, volume, channel, input, ...). At that point, you can just ask that echo device to turn on the TV and it will automatically know which TV device you are referring to.

**Comment by jlippold** [comment]
Man, so you're saying I can just install openhab and set this all up myself huh? I think it's time for me to try openhab and stop fiddling with my own implementations

**Comment by jsetton** [comment]
Yes but the v3 skill implementation is currently in beta testing. So you can't just use the current official Alexa skill. You can either request to be part of it (#123) or setup your own skill based on the v3 branch.

I would strongly suggest you go over the [usage documentation](https://github.com/openhab/openhab-alexa/blob/v3/USAGE.md) so you can get a sense of how to setup your OH items.

**Comment by jsetton** [comment]
@jlippold do you still need this issue to be opened?

**Comment by jlippold** [comment]
Nope, you guys explained it well, thanks
