### ISSUE TITLE
[v3] door opener (Alexa.LockController)

### ISSUE THREAD

**Issue by oeiber** [openhab/openhab-alexa#178]
hi,
i‘d like to use alexa.lockcontroller for my door opener because of the ability of entering a pin. however, relais closed is state ON and relais open is switch state OFF. For this reason i‘ve added [LOCKED=„OFF“, UNLOCKED=„ON] to the item definition. After that the correct state will be shown in alexa app. But everytime I say „alexa, unlock front door“ an OFF command will be sent to the switch. Are there additional parameters?
Are the sent commands hardcoded, aren‘t they?

thx!

**Comment by jsetton** [comment]
@oeiber it should work as long as this is a Switch item. It seems some extra commas were added in your description above. Would you be able to provide the exact item definition?

**Comment by oeiber** [comment]
@jsetton of course, here it is ;-)
`Switch	FrontDoor "FrontDoor"	<frontdoor>	{expire="1s,state=OFF", alexa="LockController.lockState" [LOCKED="OFF", UNLOCKED="ON"]}`

Just an additional question: Everytime the door gets unlocked using Alexa voice control, it will check if the unlock was successful or not. The only problem is, I use expire, because the switch for my door opener should work like a "push button". After clicking the switch it will wait 1 second and then it will switch it back to state "OFF". Controlling the door opener by voice will result, that the door gets unlocked, but at this time the switch has already set to OFF and alexa's check will fail. Is there a way to disable this check? If not  I have to configure expire to 5 seconds.

Thanks a lot!

**Comment by jsetton** [comment]
@oeiber So I made a mistake in my previous statement. For LockController, the command is actually [hard-coded](https://github.com/openhab/openhab-alexa/blob/v3/lambda/smarthome/alexa/v3/lockController.js#L37) to `LOCKED=ON` and `UNLOCKED=OFF`. The metadata parameter state mapping is only used for the state response.

So looking into this closer, we should update this interface to account for the metadata parameter mapping for OH commands as well. I will make the code change in the next few days.

In term of state response with your setup, you will need to have an item that provided the current state of your door state after the command is sent. You can use an [item sensor](https://github.com/openhab/openhab-alexa/blob/v3/USAGE.md#Item-Sensor) for that purpose.

**Comment by jsetton** [comment]
@oeiber actually, looking into this more in details, the reason why the command for LockController is hard-coded to `LOCKED=ON` and `UNLOCKED=OFF`, is that all OH bindings supporting locks are using that mapping. So not sure if having this configurable makes sense since for custom configuration like yours, it can be inverted on the OH side.

**Comment by jsetton** [comment]
@oeiber I am not 100% sure to follow you at this point. Are you using a specific binding to interact with your door opener? Which GUI are referring to?

**Comment by digitaldan** [comment]
@oeiber just for context, is this lock more like a momentary unlock state, like you would find in apartment buildings with a common front door?  In the US we sometimes say "can you buzz me in", ie press the buzzer to unlock the gate or door.  

In the gui you can define a button with multiple states like:
`Switch door label='Front Door' mappings=[ON="Off", OFF="On"]`
or a single button (which sounds more what you want)
`Switch door label='Front Door' mappings=[ON="Unlock"]`

These will be rendered differently than the basic switch widget, which may not be what you want.  You can always use a proxy object and a rule, or change your rules to invert the behavior (i'm guessing this item triggers a rule).  Would need to know more about your setup to help.

**Comment by digitaldan** [comment]
this is really strange, our conversation timestamps are all messed up for me.  Apparently i have a new github feature where i can see into the future!

![image](https://user-images.githubusercontent.com/1903737/57397945-af2a8f80-7182-11e9-92a1-4407f1d25b46.png)

**Comment by jsetton** [comment]
> Apparently i have a new github feature where i can see into the future!

I have the same feature 😄 I think it's @oeiber last post that had incorrect timezone somehow.

**Comment by jsetton** [comment]
@oeiber did the suggestion that @digitaldan provided above help with resolving your issue?
