### ISSUE TITLE
Support Locks

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#21]
Changes to Smart Home Skill API Reference - February 28, 2017
New directives added for querying for for lock status and setting lock status.
GetLockStateRequest
GetLockStateResponse
SetLockStateRequest
SetLockStateConfirmation
New error messages specific to lock error conditions.
UnableToGetValueError
UnableToSetValueError

**Comment by digitaldan** [comment]
This has been mostly implemented by #19 , I am only keeping this open b/c we probably need a way of polling the lock to make sure we report the correct success or failure message.   Right now we return OK if OH accepts the ON/OFF command, but most locks take a few seconds to work and may have a separate status channel we would need to report on.

**Comment by fseffert** [comment]
Can you guys enable this also for german and austrian users? It's working now... https://developer.amazon.com/de/blogs/alexa/post/f679579b-f786-42ed-ae54-cf004e31ce02/alexa-is-the-front-door-locked-lock-control-and-query-for-smart-home-skills-now-available-in-germany-and-austria

**Comment by digitaldan** [comment]
Implemented in V3
