### ISSUE TITLE
[v3] Devices not found?

### ISSUE THREAD

**Issue by stefan0001** [openhab/openhab-alexa#215]
Sorry for this question, but is v3 now deployed in production?
When I run a discovery scan no devices are found.
I also deployed the old v3 skill + lambda by my own and connected it to my alexa -> and with that the devices are found. So I thought v3 is in production because it was merged to master.

**Comment by DerEros** [comment]
Also, documentation on the website now explains v3 metadata. But it looks like v3 is not in production yet. See issue https://github.com/openhab/openhab-alexa/issues/123.

**Comment by jsetton** [comment]
Unfortunately, v3 is not in production as of yet. It takes quite some time to submit and get a skill approved by Amazon especially globally. Additionally, @digitaldan is currently working hard in fixing the current myopenhab service reliability [issue](https://community.openhab.org/t/myopenhab-not-reachable/76974). So it will most likely take some additional time to get the skill deployed to production.

**Comment by jsetton** [comment]
Closing this one in favor of #221.
