### ISSUE TITLE
[v3] rollershutter not found

### ISSUE THREAD

**Issue by CyberLine** [openhab/openhab-alexa#216]
I'am using this skill with my own cloud. Every single item with tags is found by alexa except my rollershutters. Why?

![image](https://user-images.githubusercontent.com/195617/60204875-17772280-9850-11e9-8abe-006d24ee807c.png)

**Comment by jsetton** [comment]
I did a quick test using the below item definition and it is working fine. Are you running your own skill? Metadata v3 support has not been deployed to the official skill as of yet.

```
Rollershutter TestBlind "Test Blind" {alexa="RangeController.rangeValue" [supportedRange="0:100:1",category="OTHER",friendlyNames="@Setting.Preset"]}
```

**Comment by CyberLine** [comment]
Yeah, own skill. For now i changed it to: `alexa="PercentageController.percentage" [category="SWITCH"]` and then they are both found

**Comment by jsetton** [comment]
Are you using the latest master version?

**Comment by CyberLine** [comment]
Yes.

Jeremy <notifications@github.com> schrieb am Mi., 26. Juni 2019, 21:10:

**Comment by jsetton** [comment]
Could you provide the exact rollershutter item definition you used? Would you be able to see if there are any errors in your [Lambda function logs](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logStream:group=/aws/lambda/alexa-openhab)? (Link assuming you deployed in us-east-1 region)

**Comment by CyberLine** [comment]
Discovery log from CloudWatch (for the single item):

`{
                    "endpointId": "Rolllade_Wohnzimmer",
                    "manufacturerName": "openHAB",
                    "friendlyName": "Rolllade Wohnzimmer",
                    "description": "Rollershutter Rolllade_Wohnzimmer via openHAB",
                    "displayCategories": [
                        "OTHER"
                    ],
                    "cookie": {
                        "propertyMap": "{\"RangeController:Rolllade_Wohnzimmer\":{\"rangeValue\":{\"parameters\":{\"supportedRange\":{\"minimumValue\":0,\"maximumValue\":100,\"precision\":1},\"category\":\"OTHER\",\"friendlyNames\":[\"@Setting.Preset\"]},\"item\":{\"name\":\"Rolllade_Wohnzimmer\",\"type\":\"Rollershutter\"},\"schema\":{\"name\":\"rangeValue\"}}}}"
                    },
                    "capabilities": [
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa",
                            "version": "3"
                        },
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa.RangeController",
                            "version": "3",
                            "instance": "Rolllade_Wohnzimmer",
                            "capabilityResources": {
                                "friendlyNames": [
                                    {
                                        "@type": "asset",
                                        "value": {
                                            "assetId": "Alexa.Setting.Preset"
                                        }
                                    }
                                ]
                            },
                            "properties": {
                                "supported": [
                                    {
                                        "name": "rangeValue"
                                    }
                                ],
                                "proactivelyReported": false,
                                "retrievable": true
                            },
                            "configuration": {
                                "supportedRange": {
                                    "minimumValue": 0,
                                    "maximumValue": 100,
                                    "precision": 1
                                }
                            }
                        },
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa.EndpointHealth",
                            "version": "3",
                            "properties": {
                                "supported": [
                                    {
                                        "name": "connectivity"
                                    }
                                ],
                                "proactivelyReported": false,
                                "retrievable": true
                            }
                        }
                    ]
                },`

Definition:

mqtt.things:
`Type rollershutter : Rolllade_Wohnzimmer "Rolllade Wohnzimmer" [ stateTopic="shellies/shellyswitch25-XXXXXX/roller/0/pos", commandTopic="shellies/shellyswitch25-XXXXXX/roller/0/command/pos" ]`

shelly.items:
`Rollershutter Rolllade_Wohnzimmer "Rolllade Wohnzimmer [%d %%]" { autoupdate="false", channel="mqtt:topic:mosquitto:shellys:Rolllade_Wohnzimmer", alexa="RangeController.rangeValue" [supportedRange="0:100:1", category="OTHER", friendlyNames="@Setting.Preset"] }`

**Comment by jsetton** [comment]
Thanks for the information. So the item is discovered by the skill per your CloudWatch logs. Are you seeing that item listed under your [Alexa account](https://alexa.amazon.com/spa/index.html#appliances)?

**Comment by jsetton** [comment]
Actually, I think I know what is the issue. The RangeController interface is currently only [supported](https://developer.amazon.com/docs/device-apis/list-of-interfaces.html) in the US.  I assume your Amazon account is located in another country.

**Comment by jsetton** [comment]
I just updated the [usage documentation](https://github.com/openhab/openhab-alexa/blob/master/USAGE.md#regional-availability). Hopefully that answers your question.

In terms of workaround, there is much that can be done other than to relocate or create a new account on the Amazon US website. Doing so would prevent you from accessing other skills that are only available in your country.

**Comment by CyberLine** [comment]
If so (only en-Us) i'am wondering why motiondetection works for me in Germany.
But maybe as motion has no voice capability? This may be the solution yeah.

**Comment by jsetton** [comment]
Based on the api documentation, it shouldn't but based on my previous experience, their documentation seem to not always reflect the latest improvements. In one instance, they even had a feature advertised that wasn't implemented and ended removing it after I pointed it out to them.

Anyway, I would say it is hit or miss in regards to the latest capabilities. So you may give it a try with no guarantees. In regards to why range, mode & toggle interfaces aren't available in other regions is probably due to the amount of locale support involved with these capabilities which is far greater than any of the other ones they have been implemented so far.

From your example, using an asset id may be the first issue. Have you tried to use a text label instead? Although this will also be an issue since the [skill](https://github.com/openhab/openhab-alexa/blob/master/lambda/smarthome/alexa/capabilities.js#L234) will always set the locale to `en-US` on these labels. So, if you can, try to make the code change below and redeploy the skill. It will use the locale metadata parameter, if defined, otherwise your OH server regional setting. Again, this is a long shot but it might worth it...

```diff
diff --git a/lambda/smarthome/alexa/capabilities.js b/lambda/smarthome/alexa/capabilities.js
index 82971b2..14d30e3 100644
--- a/lambda/smarthome/alexa/capabilities.js
+++ b/lambda/smarthome/alexa/capabilities.js
@@ -231,7 +231,7 @@ function getResourcesObject(parameters = {}) {
           '@type': 'text',
           'value': {
             'text': label,
-            'locale': 'en-US'
+            'locale': parameters.locale || 'en-US'
           }
         });
       }
```

**Comment by CyberLine** [comment]
OK, i redeployed the skill with the change. Where do i set locale in itemconfig?

**Comment by jsetton** [comment]
You can set it up as below example but it can also be automatically detected from your OH server (Paper UI > Configuration > System > Regional Settings > Language + Country/Region) without specifying that parameter in the metadata configuration.

`Rollershutter Rolllade_Wohnzimmer "Rolllade Wohnzimmer [%d %%]" { autoupdate="false", channel="mqtt:topic:mosquitto:shellys:Rolllade_Wohnzimmer", alexa="RangeController.rangeValue" [supportedRange="0:100:1", category="OTHER", friendlyNames="<your-label>", locale="<your-locale>"] }`

The capability resources of the discovered item should show as follow in your lambda logs:

```
"capabilityResources": {
  "friendlyNames": [
    { "@type": "text", "value": { "text": "<your-label>", "locale": "<your-locale>" } }
  ]
}

**Comment by CyberLine** [comment]
Nope, doesn't work :(

**Comment by jsetton** [comment]
Thanks for giving it a try. What locale did you use?

**Comment by CyberLine** [comment]
de-DE

Am Fr., 28. Juni 2019 um 22:18 Uhr schrieb Jeremy <notifications@github.com
