### ISSUE TITLE
Discovery failed

### ISSUE THREAD

**Issue by oeiber** [openhab/openhab-alexa#218]
Since converting my custom skill to the latest master version no new items where discovered.
lamda log says:

```
"stack": "TypeError: Cannot read property 'synonyms' of undefined\n    at items.forEach (/var/task/alexa/v3/discovery.js:47:58)\n    at Array.forEach (<anonymous>)\n    at Promise.all.then (/var/task/alexa/v3/discovery.js:45:13)\n    at process._tickCallback (internal/process/next_tick.js:68:7)"
}
```

**Comment by jsetton** [comment]
Good catch. The assumption was that metadata information would always be available. The bug is triggered when an item has no label or metadata configuration but has an Alexa-related tag as per the example below.
```
Switch TestSwitch ["Switchable"]
```
A fix has been pushed to master.

**Comment by oeiber** [comment]
now its working. thx!
