### ISSUE TITLE
Support Color Lights

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#22]
Changes to Smart Home Skill API Reference - April 7, 2017 

New directives added to control the color and tunable white light settings of devices
SetColorRequest
SetColorConfirmation
SetColorTemperatureRequest
SetColorTemperatureConfirmation
IncrementColorTemperatureRequest
IncrementColorTemperatureConfirmation
DecrementColorTemperatureRequest
DecrementColorTemperatureConfirmation
New value added to NotSupportedInCurrentModeError.currentDeviceMode to support lighting changes.

**Comment by mavris** [comment]
Any update on this?

**Comment by digitaldan** [comment]
@mavris I put this in as a reminder, but have not yet worked on it,  this and lock support are next on my list of things todo.
