### ISSUE TITLE
[v3] Release

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-alexa#221]
@jsetton , I just got back last night from vacation and was traveling for work for the past three weeks, so i'm super behind where we are !   

I was hoping to use this issue to track what needs to be done (if anything) to release v3.  We can reference other issues here that need to be completed.

**Comment by jsetton** [comment]
Sure. Can you go over the PRs I didn't merge? Wanted to get your input and review one of them. It shouldn't take too long. Other than that, I think we are ready to release.

**Comment by digitaldan** [comment]
Yep, i'll do that today, thanks.

**Comment by fsedarkalex** [comment]
Is there any reason not to have v3 in production while having the documentation live (and not stating this is still unreleased) for months?
I just invested a whoile evening into figuring out why that damns v3 tagging is not working just to find out that after 4 hours of research while I was just upon filing abug report...
Damn thats disgusting... Why not at least add a notice to the docs?

**Comment by jsetton** [comment]
@fsedarkalex my apologies for your frustration related to this. Know that the effort you put in setting up your environment won't be lost. And worse comes to worst, you can setup your own skill in the meantime.

Unfortunately, it takes quite time to submit and get a skill approved by Amazon especially globally. So we need to make sure we get it right before submitting the skill.

In terms of the documentation, there is an automated process that pulls the latest usage page from the master branch of this repository. So when the v3 branch was merged to master, in preparation of the upcoming production release, the documentation on the main website was updated. I will add a notice as you recommended it until the official skill v3 is available.

**Comment by jsetton** [comment]
@digitaldan I forgot to mention that I have a minor code refactoring PR in the pipeline once the color temperature improvement PR is reviewed and merged.

**Comment by fsedarkalex** [comment]
@jsetton please don't get me wrong. Sure I was a bit frustrated but I did not want to complain in a negative way. It was meant more like constructive criticism.

**Comment by jsetton** [comment]
@fsedarkalex No worries. I think it's fair to say that the v3 documentation being available on the official website is misleading and you aren't the only person that got excited by going over it at first, only to be disappointed that it is not available as of yet, especially since this major update has been a long time coming.

**Comment by digitaldan** [comment]
@jsetton I see only two issues for deployment.  First is we do not have language translations for the "whats new" section.  Second is that we have not submitted for Japan yet, pushing to a new country invokes the wrath of the Alexa Smart Home review team in that country which can be very, very painful for a first submission.  I'm ok with #2, it just may delay release a bit.  I will run the whats new section through google translate and hope we get by with that!

**Comment by digitaldan** [comment]
> see only two issues for deployment. First is we do not have language translations for the "whats new" section. 

Ok, nm, i see you fixed that!  So its just JP and whats new we need to update.

**Comment by digitaldan** [comment]
I have submitted the skill for review, fingers crossed!

**Comment by jsetton** [comment]
Did you end up submitting the Japanese language skill at the same time?

**Comment by digitaldan** [comment]
I did, curious to see what will happen.  I used google translate for the "whats new" , my guess is they will respond back with grammatical  suggestions for all the JP texts, hopefully it does not hold things up too much.  The review process has taken a while in the past, right now they are saying July 29th!  Uhg.  Hopefully thats a worst case estimation :-( 

![image](https://user-images.githubusercontent.com/1903737/60905308-a6f5db80-a229-11e9-85b4-ceb20afbc61d.png)

**Comment by jsetton** [comment]
Ok. Crossing fingers as well. Talking about locale support, I forgot to mention again that we needed to add Portuguese to crowdin for pt-BR support. I don't think it's critical but we could add it now so it is setup for the next skill update.

**Comment by Flole998** [comment]
Something is broken for the last few days (at least for me) in the Beta: I can ask alexa to do something with my lights/rollershutters/whatever, she does it but responds that "xyz is not working at the moment".

**Comment by jsetton** [comment]
@Fole988 have you gone through the [troubleshooting steps](https://github.com/openhab/openhab-alexa/blob/master/USAGE.md#troubleshooting)? If this is related to the beta testing, can you please post in the relevant [issue](#123)? Otherwise, please open a new issue including the relevant item configuration and utterance you used to trigger this response. Thanks.

**Comment by Flole998** [comment]
Thank to whoever fixed it. Seems like the entire Skill's response was just broken.

**Comment by digitaldan** [comment]
@jsetton so since i submitted we have had a couple of rejections, first it was language based, not just Japanese but other languages (which ironically did not change since our last submission) . I will update the translation this weekend to reflect what i changed manually.  I also had an issue with our demo account on oh cloud which i fixed.  

The last rejection was a new one for me:

```
1. One or more of the discovered devices associated with the skill’s test account, which appear as Smart Home interaction model-enabled devices, did not successfully respond to commands.

Steps to Reproduce:

User: "Alexa, règle thermostat à quatre cents degrés"

Skill: "Le thermostat Thermostat est réglé sur 400"

Note: Please be aware that thermostat should not set the temperature to such high value. Kindly make sure that the skill provides a response telling the user what is the maximum value whenever a high temperature value is prompted by the user.
``` 
I think we may need to add a min/max option to our meta data, and possibly set a default one ( like  32/104 F) .  WDYT ?

**Comment by Flole998** [comment]
As usually every Thermostat has a Max/Min value this should be fine, setting it to anything outside that window causes the thermostat to usually simply ignore the command, so we should indeed make sure to limit this properly. For example on my Max Thermostats they go from 5°C to 30°C, I assume they want a minimum value aswell. We should at least set the default to the max/min of one binding instead of making up our own values, I don't know what other bindings (for example nest is widely used I think) use as max/min though, if it's similar to these values it would be an easy decision in my opinion.

**Comment by digitaldan** [comment]
in the US i know of no residential thermostats that allow temperatures above 99 degrees F, I'm not sure  what the floor value is.  While we could try and find out and map each thermostat, i wonder if having a reasonable default, like 0c to 38c ( or maybe even higher) would be simpler.   If the user can specifically set it, then this should not be an issue for those rare use cases.  FYI, its actually super tough to find out what ranges are supported on some residential units, I actually had to call Nest/Google for this information some time back as it was not published (and they had to get engineering on the phone). 

 We could try and add this model by model, like we do with modes,  for those units that we do have ranges for, but I'm also concerned about the amount of developer  work this is going to be to get this submitted again.

Amazon is testing with really, really high values, so my guess is they are just making sure you have some reasonable upper limit

**Comment by Flole998** [comment]
Not sure if you understood me correctly: Of course this should be user-setable but the default should not just be made up but match at least one thermostat, for example if you know the nest values make those the default for Fahrenheit and take 5 and 30 for Celsius, that reduces the configuration amount for Nest and Max Thermostat Users as they can use the defaults. There has to be some kind of default, so why not take the values from a device as default here?

On my devices it was actually easy to figure out: Turn the thermostat up to max, note down the value, turn down to min, note that value and then dont forget to change it back to a reasonable value. Of course this only works if you have access to such a device.

**Comment by jsetton** [comment]
> I think we may need to add a min/max option to our meta data, and possibly set a default one.

I actually thought about it when I introduced the range metadata parameter with the last color temperature update. So we could easily extend that functionality to thermostat temperatures.

> in the US i know of no residential thermostats that allow temperatures above 99 degrees F, I'm not sure what the floor value is. While we could try and find out and map each thermostat, i wonder if having a reasonable default, like 0c to 38c ( or maybe even higher) would be simpler. If the user can specifically set it, then this should not be an issue for those rare use cases. FYI, its actually super tough to find out what ranges are supported on some residential units, I actually had to call Nest/Google for this information some time back as it was not published (and they had to get engineering on the phone).

I agree with just using a default range. I did a quick search and Nest actually published the maximum spread in their [deprecated api](https://developers.nest.com/reference/api-thermostat#target_temperature_f) but other smart thermostats, as you mentioned, seem to not clearly publish that information. For the default range, I think we could use what Nest is using (50F/10C to 90F/32C) which should cover standard use cases.

I should be able to come up with the implementation towards the middle of the coming week.

**Comment by digitaldan** [comment]
Sounds good 👍

**Comment by jsetton** [comment]
Sorry for the delay. I got sidetrack with others things and the change isn't straight forward as I initially thought. I should have this available before the end of the week if not earlier.

**Comment by digitaldan** [comment]
👍

**Comment by jsetton** [comment]
@digitaldan I submitted PR #230 for this change. Looking for your feedback.

**Comment by jsetton** [comment]
@digitaldan thanks for reviewing the PR. I have merged it to master. What happened to the translation issue you mentioned? I don't recall seeing any updates coming from Crowdin.

**Comment by digitaldan** [comment]
I went back through the rejection email shortly after i posted this and realized it was rejecting us in those languages for the same thermostat issue, the way it was formatted in the email it looked like they were suggesting alternative wording for our examples, but they were giving examples  about what Alexa should be speaking back in those languages if the temperature was out of range.   My brain saw a foreign language and assumed it was a translation issue.

**Comment by jsetton** [comment]
Good the hear. So we should be all set to resubmit the skill 👍

**Comment by digitaldan** [comment]
Whoa! 
```
Dear Kai, 

Thank you for the recent submission of your skill, ‘openHAB’. 

Congratulations! Your skill has passed our certification process and will be published to the skill store shortly. 
You should expect to see increased traffic to your service once the skill is available on the skill store. Please ensure that you have sufficient capacity and that your service remains operational as customers explore your skill. 
```

I was expecting a bit more of a fight, so this was a little unexpected. but welcome for sure!   I will craft a post for the community tomorrow.  I have a very early flight with wifi access, so  plenty of time to write something.

**Comment by digitaldan** [comment]
FYI, i am seeing a lot of these messages in the logs:
`error: No supported payloadVersion: 2`
It looks like we are getting command requests from users still on v2 of the app.  I am hoping this goes away in the next 24 hours as amazon migrates them to v3. but this was not very clear in their migration docs exactly how that happens.

**Comment by digitaldan** [comment]
https://community.openhab.org/t/alexa-smart-home-skill-v3-is-now-live/79848

**Comment by jsetton** [comment]
> https://community.openhab.org/t/alexa-smart-home-skill-v3-is-now-live/79848

@digitaldan thanks for the shout-out 👍 

> It looks like we are getting command requests from users still on v2 of the app. I am hoping this goes away in the next 24 hours as amazon migrates them to v3. but this was not very clear in their migration docs exactly how that happens.

My guess is that you use the same lambda function name which basically overwrote the existing production v2 function. I think we came to the correct conclusion when we removed the v2 code (#143) but I think we forgot that we should have renamed the new function. I tried to see if we could quickly redeployed v2 support in the current implementation but with the major code refactoring it would require some work to retrofit the old code. Hopefully, it will clear in the next 24 hours as you said.

**Comment by jsetton** [comment]
@digitaldan when you get a chance, can you do a sweep of the logs for errors? I think the V2 errors should have stopped by now. I am curious about V3 errors that we may have missed during the beta testing.

**Comment by jsetton** [comment]
> My guess is that you use the same lambda function name which basically overwrote the existing production v2 function.

Coming back on this, after taking a look at the logs, these error messages are actually related to users that had their v3 discovery request fail causing their skill to remain on v2. This is related to #242.

**Comment by jsetton** [comment]
@digitaldan I have been going over the skill error logs. At this point, I think we have most of them covered in terms of bugfixes and changes. I noticed one related to the discovery where the items data returned by the call, which, surprisingly seems successful since we got to that point, isn't iterable. The skill returns an internal error response back, which I think is appropriate in that event.

What do you think could be the root cause for this one?

```
error: discover failed with error:items.forEach is not a function
{
    "stack": "TypeError: items.forEach is not a function\n    at Promise.all.then (/var/task/alexa/v3/discovery.js:45:13)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)"
}
```

**Comment by digitaldan** [comment]
That is strange, as if the first promise in the call is returning something other than a object or array.  Can you see in the logs the retuned item JSON?

**Comment by jsetton** [comment]
> The call is returning something other than a object or array

We are expecting an array here. I even tested on an empty configuration and the rest api still returns an empty array. So technically we should never end up here.

> Can you see in the logs the retuned item JSON?

We would need to enable debug logs to see the content of the calls.

**Comment by digitaldan** [comment]
is it possible the promise is returning during a termination of the lambda when exceeding the TTL ?   And that structure has been deallocated somewhere?  Thats a super long shot i know :-)

**Comment by jsetton** [comment]
> is it possible the promise is returning during a termination of the lambda when exceeding the TTL ?

I just checked a few occurrences and the errors are generated within the first few seconds after receiving the request. No even close to the 10 seconds timeout.

Should we enable debug log level? It happens at least 3-4 times every hour. Hard to determine if it is coming from the same user as the bearer token is different for each occurrence.

**Comment by digitaldan** [comment]
Yes, please update the level whenever you need to.

**Comment by jsetton** [comment]
After enabling debug mode, I was to determine that the issue is due to the items data value being a string because the request call seems to only have read/received a partial response preventing the expected JSON object from being parsed properly.

The example I am looking at isn't that considerably big in size, although it's just partial data, and the Lambda execution time for that request was about 5 seconds.

Any idea why would this be happening?

**Comment by jsetton** [comment]
For reference purpose, during the initial discovery request conversion from v2 to v3, if an Alexa device previously discovered isn't part of the v3 discovery object, it will remain as a v2 entity while the other ones would become v3.

The only way to fix that is either find the reason for not being discovered by new skill (mis-configured group endpoints are mostly the culprit) or just manually delete it on the Alexa side.

**Comment by digitaldan** [comment]
we are released, closing

**Comment by Flole998** [comment]
Can we "opt out" of the Beta now or is new stuff still coming "beta-first"? I am currently having issues as Alexa states the Server is currently unavailable on every item in the App and the Skill is still shown under the "Developer" Section of "My Skills", maybe/hopefully disabling causes everything to start working again? Or is the skill itself broken at the moment?

**Comment by jsetton** [comment]
I just ended the beta test. You should have received a notification.

**Comment by Flole998** [comment]
Thanks, I had to delete all items and re-scan after activating the skill (and add them to all routines and groups again).
