### ISSUE TITLE
[V3] Support motion sensor "inactive since"

### ISSUE THREAD

**Issue by nougad** [openhab/openhab-alexa#226]
Hey,

Alexa added new(?) support for motion detector including a "inactive since" property:

![](https://i.redd.it/qcllt8jv93831.png)
- source: https://www.reddit.com/r/Hue/comments/c8nzmz/alexa_just_randomly_told_me_she_had_discovered_a/

Looks like there is a `timeOfSample` property: https://developer.amazon.com/docs/device-apis/alexa-motionsensor.html

I tried the following configuration with my hue motion detector:

```
Group KitchenMotion "Motion" <motion> (Kitchen,gMotion) {alexa="ENDPOINT.MOTION_SENSOR"}
Switch KitchenMotionSensor_Presence
    (KitchenMotion)
    {channel="hue:0xx7:$ID:kitchen-motion-sensor:presence", alexa="MotionSensor.detectionState"}
DateTime KitchenMotionSensor_LastUpdated
    (KitchenMotion)
    {channel="hue:0xx7:$ID:kitchen-motion-sensor:last_updated"}
Number KitchenMotionSensor_BatteryLevel
    (KitchenMotion)
    {channel="hue:0xx7:$ID:kitchen-motion-sensor:battery_level"}
Switch KitchenMotionSensor_BatteryLow
    (KitchenMotion)
    {channel="hue:0xx7:$ID:kitchen-motion-sensor:battery_low"}
```

But I guess there is some annotation for last updated missing.

**Comment by jsetton** [comment]
I think these extra annotations are tie in with the proactive reporting via [ChangeReport event](https://developer.amazon.com/docs/device-apis/alexa-motionsensor.html#changereport-event). Sending these events to Amazon would allow Alexa to keep track of historical events and therefore provide the information you mentioned above.

Unfortunately, the current skill doesn't support that type of reporting. You can follow #73 for the work related to this. Until that, only the real time item state is polled. This is why all property responses have a `timeOfSample` set to the time of the request. Additional, this is the reason why contact and motion sensors can't be use in Alexa routines at the moment with the skill.

**Comment by jsetton** [comment]
Closing this issue in place of #73 enhancement.
