### ISSUE TITLE
As a user, I would like Alexa to discover my Jasco 12718 controlled by OH2.

### ISSUE THREAD

**Issue by gk4** [openhab/openhab-alexa#23]
GE (Jasco) 12718 PlugIn Smart Dimmer is fully functional in OH2, but is not detected by the Alexa discover device scan.  Alexa can find my Smartthings  devices, but not my OH2 devices.

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devices

Please let me know where I might find more info/logs to share regarding this issue.

**Comment by digitaldan** [comment]
Our Alexa app uses the oh rest API, so it has no knowledge nor cares what type of device it is, have you tagged these items appropriately ?

**Comment by gk4** [comment]
@digitaldan I'm not clear on the tagging for Alexa.  In OH2 I see Label, Category, and Type, but if I change any of those then the device is not useable in OH2 Control.  I've seen your online references to the homekit add-on, but I'm not sure that is correct or what that info means.  Am I to install the misc-homekit-2.0.0 under Misc?   Is that where I am to tag?

http://docs.openhab.org/addons/io/homekit/readme.html

**Comment by gk4** [comment]
@digitaldan I'm not clear on the tagging for Alexa.  In OH2 I see Label, Category, and Type, but if I change any of those then the device is not useable in OH2 Control.  I've seen your online references to the homekit add-on, but I'm still unclear about it.

http://docs.openhab.org/addons/io/homekit/readme.html

1) OH2/paperui -> Add-ons -> Misc -> HomeKit Integration -> Install

2) OH2/paperui ->  Services -> IO -> HomeKit Integration (enter IP of your device)

The results of the HomeKit Integration setup are found int:

3) /var/lib/openhab2/config/org/openhab/homekit.config

From the following webpage, I’m not sure what file or webpage the sample items would be?  This is the part that I am unclear about.    Could you please elaborate?

https://github.com/openhab/openhab2-addons/tree/master/addons/io/org.openhab.io.homekit

Switch KitchenLights "Kitchen Lights" <light> (gKitchen) [ "Lighting" ]
Dimmer BedroomLights "Bedroom Lights" <light> (gBedroom) [ "Lighting" ]

**Comment by digitaldan** [comment]
Please see https://community.openhab.org/t/official-alexa-smart-home-skill-for-openhab-2/23533 Alexa skills are installed through their Alexa app (mobile or web), you also need to have myopenhab.org connected to your system (Amazon skills need a central point for authentication).

**Comment by gk4** [comment]
@digitaldan  Yes, I have had the OpenHab skill installed in my Alexa app.

Back to the tagging.   Where is that done?  Where do I find that list (KitchenLights, BedroomLights, ...) like I see in the instruction pages?

<img width="455" alt="screen shot 2017-04-14 at 10 13 09 am" src="https://cloud.githubusercontent.com/assets/13398918/25047230/199a5f06-20fb-11e7-82f4-5c711c1bef1d.png">

**Comment by digitaldan** [comment]
I understand now, sorry for the confusion ,  I do not believe we have a tag editor in the paperui , the examples are for items defined in item files , I believe you are using items created thorough the web GUI ( or auto generated ) .  The only way I know to archive this is using the rest API , which can be accessed through your browser at /docs/index.html , there is a item call to add tags. I'm typing this on my phone, when I'm back in front of a computer I can elaborate more.

**Comment by gk4** [comment]
I get a 404 at my http://192.168.1.125:8080/docs/index.html

**Comment by gk4** [comment]
I finally got it.  http://192.168.1.125:8080/doc/index.html

I'm getting a 405 response with the following.

![screen shot 2017-04-14 at 7 55 11 pm](https://cloud.githubusercontent.com/assets/13398918/25059447/93c69870-214c-11e7-9551-b7390e2903fb.png)

The name ZWaveNode212718SmartDimmer_Dimmer is not going to be Alexa friendly.   How do I change it to the name I had given it in OH2?

![screen shot 2017-04-14 at 7 59 09 pm](https://cloud.githubusercontent.com/assets/13398918/25059513/934b8eea-214d-11e7-9f7f-9cf1fb75da85.png)

**Comment by digitaldan** [comment]
>The name ZWaveNode212718SmartDimmer_Dimmer is not going to be Alexa friendly. How do I change it to the name I had given it in OH2?

The label is what is used for voice, so in this case "Olives Lamp"

**Comment by digitaldan** [comment]
I'm going to close this since it is not an issue with this code base
