### ISSUE TITLE
Unable to discover devices when using V3 Skill & Private Cloud

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-alexa#233]
Hi Guys, skill deployed and cloud server deployed. Cloud server working just fine, can manage the OH2 server without issue. Can also link the skill without issue, but a discover devices shows an internal error.

I assume the skill once deployed makes its call to openhab cloud using HTTPS, which is indeed open on my AWS Openhabcloud instance

Any suggestions on how to troubleshoot or where to look for whats wrong? thanks

**Comment by jsetton** [comment]
Did you specify your private cloud base url in your [config.js](https://github.com/openhab/openhab-alexa/blob/master/lambda/smarthome/config_sample.js#L32)?

**Comment by dastrix80** [comment]
Hi there, indeed. No devices :(

**Comment by dastrix80** [comment]
Any thoughts jsetton?

**Comment by jsetton** [comment]
Not sure. Have you looked at the skills Lambda logs?

**Comment by yekorzh** [comment]
As using myopenhub.org option is very unreliable at the moment, I decided to deploy this skill and link it to my server instead. I followed installation instructions and it can't discover my devices too. It appears that lambda function is not being called, there are no logs or invocation attempts in function monitoring. 

This message during the "ask deploy" is a bit suspicions: "[Warn]: Skill api domain "smartHome" can not be enabled. Skipping the enablement."

**Comment by yekorzh** [comment]
> Have you gone through step 3 and 4? It sounds like you didn't enable your skill under your account.
@jsetton Yes I've done the linking using Login with Amazon, the skill is enabled and shown as linked.

**Comment by yekorzh** [comment]
I'm sure there are no logs. I think it happens because I'm in Australia region and according to https://forums.developer.amazon.com/articles/104935/when-lambda-is-not-invoked-from-your-smart-home-sk.html it wants function to be in us-west. Now, no matter what I do "ask deploy" puts it into us-east-1

**Comment by yekorzh** [comment]
@jsetton yeah ... I did that, looks like ask cli ignores region setting from .aws/config. 

I've just got it to work by setting region under profile in .aws\credentials (as per https://forums.developer.amazon.com/questions/173679/ask-cli-does-not-deploy-to-eu-west-1-or-other-regi.html). It is now in correct region, and I can see that lambda is called when I discover devices.

**Comment by yekorzh** [comment]
@jsetton Probably add the mapping of alexa geographical regions to lambda function regions too. That was my main problem.
