### ISSUE TITLE
Rest API Request Call Timeout Restriction

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#241]
Currently, each request call made by the skill have a default timeout greater than the lambda function execution timeout. We should restrict the [request timeout](https://github.com/request/request#timeouts) based on a portion of the [lambda remaining execution time](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html).

**Comment by jsetton** [comment]
@digitaldan I just submitted a PR for this one. Ended up hard-coding the request timeout value using 2 seconds as default setting for get/post a single item and up to 8 seconds for get all items calls. The default setting can be changed through a function environment variable if necessary.

I looked at using the Lambda context remaining execution time method but this meant passing the context all the way to the rest api calls which felt as overkill.

Let me know what you think.

**Comment by digitaldan** [comment]
is 2 seconds enough?  I would be fine keeping it at 8 seconds for everything.

**Comment by jsetton** [comment]
If we are trying to maximize, we need the room for a post and then a get single item calls. So how about 4 seconds as default and 8 for the big one?

By the way, I am making changes to this implementation adding an overall timer that would respond with an Alexa error if the function is about to time out.

**Comment by jsetton** [comment]
@digitaldan so I updated the PR and went with 8 seconds default timeout across the board as you suggested. I also made a change to pass the timeout value to the rest functions along with adding a response timeout timer that will ensure we are sending a response back in time.

Let me know what you think. The response timer may be overkill.

**Comment by digitaldan** [comment]
Sorry i spaced replying to this yesterday.  I'm ok ok either way, but would it be better to use the timeout specified by alexa in the node request context?  Do we need to specify our own at all?  I think i remember you mentioning this, but it was going to be a pain to carry through all the classes, but you have seem to do that hard work in any case :-)

**Comment by jsetton** [comment]
> would it be better to use the timeout specified by alexa in the node request context?

We could but after thinking about it, I don't think the Lambda function timeout value is indicative of the Alexa response defined timeout value. Sure, currently there are in sync but maybe in the future, we may have the function run longer and at that point we will have to dissociate the two.

**Comment by digitaldan** [comment]
I'm good with your approach !

**Comment by jsetton** [comment]
And anything against the response timer I added? Not sure if it will make a difference on the Alexa side at the moment between sending a formatted error response and letting the function timed out without a response but I think it cleaner that way and we can build on that going forward.

In all, if you are fine, let me know if I can merge these changes.

**Comment by digitaldan** [comment]
LGTM.
