### ISSUE TITLE
Large Item Collection Discovery Lambda Timeout Fix

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#242]
Doing one big api call pulling every group members recursively is causing the discovery process to fail on large item collection as the lambda times out waiting for the response back.

The easy route would be to increase the lambda function timeout but that could be costly in the end. However, this could be just temporary until the logic to generate the list of discovered device is moved to the binding.

The other options would be to do an initial flat query similar to how it was done in v2 and only query endpoint-enabled groups when necessary. One downside with this approach will depend on how many of these groups a specific user will have, although we could have these calls run concurrently. Additionally, we should probably limit the output to a list of fields we use in the skill.

@digitaldan what do you think?

**Comment by digitaldan** [comment]
Can we up the time of the request timeout?  I thought home skill kits had a limit regardless of the lambda timeout.  if we could up it just for the discovery request that great, but since it's on every request , yes it could be a cost issue. 

On the other hand, i don't see a ton of these, and they appear to only be on disco requests, so it may not be a problem, I'm actually a bit on the fence.  I'm inclined to up the timeout to 15 or 20 seconds  (if we can) and see if this solves our issue for a while.  

Shall i do this or would you like to?

**Comment by jsetton** [comment]
> I thought home skill kits had a limit regardless of the lambda timeout.

I forgot about that part. We have 10 seconds to response to an Alexa request. This is probably why ask-cli sets the default lambda timeout to that value. Anything longer than that would require an immediate deferred response followed by an asynchronous one sent to the event gateway once available.

So it looks like we need to go for the latter option unless you have another idea?

**Comment by digitaldan** [comment]
Let me think on it a bit this morning, i want to flush out an idea or 2 as a short term workaround until we have a longer term option.

**Comment by digitaldan** [comment]
One idea for workaround today.  Just spitballing here, so not sold on anything. 

Supported deferred response just for Discovery requests.  Our skill would invoke another lambda on discovery that would perform the OH rest call with a timeout of 30 seconds and send the response it to the event gateway when it completes.   This avoids having to create a binding on OH which will take some time, and limits our exposure to longer running lambdas to just disco requests.  We would need to bring back your branch where we store in dynamo ( i think it was dynamo?) the user tokens .

**Comment by jsetton** [comment]
> Supported deferred response just for Discovery requests

I was actually going to mention that as another option. As you mentioned I have the [asynchronous logic](https://github.com/jsetton/openhab-alexa/commit/e3f562d59fa80b9fbd315d2f82e3d1c6b3dd9984) already implemented. We could build a process that would return a deferred response if no response available within the first 10 seconds and then send it to the event gateway after that time. Additionally, we can limit the request calls to specific timeout values, in order to restrict the overall lambda execution time based on the request type, so we can, for example, allow more time for get all items recursively calls vs getting an item state calls as per #241.

But I feel this might be a bit overkill when I think there is room to optimize the request calls. I believe I can have something by the end of the day on this to run some test scenarios and determine if this would work. Unless, you have some concerns about the increased number of calls hitting the myopenhab cloud service?

**Comment by digitaldan** [comment]
>Unless, you have some concerns about the increased number of calls hitting the myopenhab cloud service?

Not right now, if you have a simpler way to optimize I say let's look at this first.  Most important focus should be getting this working now and some time for us to come up with the right long term solution.

**Comment by jsetton** [comment]
> Most important focus should be getting this working now.

Agreed and my thought is that not a lot of users will have endpoint-enabled groups setup initially so we would benefit from not doing the recursive calls.

> Some time for us to come up with the right long term solution.

The binding would offload a good amount of cloud compute time and resources. 😄

**Comment by jsetton** [comment]
Also another thing to keep in mind if we would go with the supported deferred response option, we would have to re-certify the skill since we would be changing its permission.

**Comment by digitaldan** [comment]
>The binding would offload a good amount of cloud compute time and resources.

Yep, i have definitely  come around on that idea and am all for it. 

>Also another thing to keep in mind if we would go with the supported deferred response option, we would have to re-certify the skill since we would be changing its permission.

Good point

**Comment by digitaldan** [comment]
>I think there is room to optimize the request calls

Is the recursive parameter the culprit here?  If so are you thinking about building out Group->Item tree structure without this call?  I believe the v2 version did this, maybe b/c the recursive option was not available when we started that  (or did not realize it was there)

**Comment by digitaldan** [comment]
I just read the first post again and realized you clearly state its a recursive issue :-) So ignore that part of my question .

**Comment by jsetton** [comment]
> If so are you thinking about building out Group->Item tree structure without this call

That's actually a very good point. I was about to start coding the fix. I think we got our solution here and it won't even be so ugly in the end 👍 

> I believe the v2 version did this

I may be wrong but I don't recall that since there is no concept of group in that version. The recursive part was added for the endpoint-enabled group.

**Comment by digitaldan** [comment]
>I may be wrong but I don't recall that since there is no concept of group in that version.

We used groups for thermostats, so after getting  the items , the logic would go through the list and any time it found a group item it would add it to a list of groups.  The logic scanned the list again and anytime it found an item that had a thermostat related tag (like CurrentTemperature) it would check if one of the groups it belonged to was in our list of thermo groups.

I could see something similar where as you iterate the list you are first sorting items into groups they belong to (items say what group they belong to, groups do not list their members).  Then traverse the groups and create Alexa endpoints, and  then items which do not belong to groups and create Alexa endpoints.  This is all a theory, i have not sketched this out in code to prototype.

**Comment by jsetton** [comment]
> We used groups for thermostats

Now I remember 😄 It's been a while.

> I could see something similar where as you iterate the list you are first sorting items into groups they belong to (items say what group they belong to, groups do not list their members). Then traverse the groups and create Alexa endpoints, and then items which do not belong to groups and create Alexa endpoints. This is all a theory, i have not sketched this out in code to prototype.

I started to go towards that route but realized we could easily generate the group item member property and use the current code with minimal changes. Hopefully that would be to your liking 👍 

Anyway, I submitted a PR. Let me know what you think.
