### ISSUE TITLE
Discovery request timing out due to image item state

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#257]
For [users](https://community.openhab.org/t/alexa-smart-home-skill-v3-is-now-live/79848/131) that have image items, their discovery request is timing out due to overall size of the rest items query response which is pulling the raw data stored in the image item state. As a workaround, commenting these items resolves the issue.

Ideally, we would filter item types in the items query but the rest api only allows to filter based on one item type per request.

Another option would be to filter out the state field. We are currently using the state field only to determine the unit for item types supporting unit of measurement. This information can technically be retrieved in most cases from the item state presentation unless not part of the item label definition.

Should we enforce the item state presentation definition and forgo the logic using the state? One important point is that the state presentation is free form opposed to the state having a defined format. This mean the state is technically more reliable.

**Unable to determine unit**

- **item**
```
Number:Temperature TestTemperature "Test Temperature"
```

- **rest**
```
{
  "link":"https://myopenhab.org/rest/items/TestTemperature",
  "state":"60.0 °F",
  "editable":false,
  "type":"Number:Temperature",
  "name":"TestTemperature",
  "label":"Test Temperature",
  "tags":[],
  "groupNames":[]
}
```

**Able to determine unit**

- **item**
```
Number:Temperature TestTemperature "Test Temperature [%d °C]"
```

- **rest**
```
{
  "link":"https://myopenhab.org/rest/items/TestTemperature",
  "state":"20.0 °C",
  "stateDescription":{
    "pattern":"%d °C",
    "readOnly":false,
    "options":[]
  }
  "editable":false,
  "type":"Number:Temperature",
  "name":"TestTemperature",
  "label":"Test Temperature",
  "tags":[],
  "groupNames":[]
}
```

**Comment by jsetton** [comment]
@digitaldan what do you think about this one? Is worth it to filter the state out from the rest get items query? Maybe there is another option I am not seeing?

**Comment by digitaldan** [comment]
Uhg, I have never liked the concept of storing image data in an item, this being a prime example of why.  I'm torn b/c I don't think that its a widely used feature of OH, so my feeling is that not many people will have this problem.  Otoh, its obviously an issue we will continue to run into to.

I would personally punt on this one to see how widespread this is, possibly putting a note in the docs about this.  If you think not pulling the state  won't dramatically impact our ability to support UOM , then I'm good what whatever you decide.

**Comment by jsetton** [comment]
> I would personally punt on this one to see how widespread this is, possibly putting a note in the docs about this.

That's my fallback solution.

> If you think not pulling the state won't dramatically impact our ability to support UOM , then I'm good what whatever you decide.

I am torn because once we move to the bind, this won't be an issue anymore. In regards to the need of the state field, how likely do you think someone who is using UoM items wouldn't specify its state presentation? I think the response to this question would decide if we can pull the state field or not. Also, not pulling that field would technically decrease the discovery items query response time and therefore lower the average compute time.
