### ISSUE TITLE
Thermostat Setpoints Support Improvements

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#271]
Here are the thermostat setpoints support improvements I am proposing:

- Add metadata configuration for setpoints type support (`single`, `dual` or `triple`) on a per mode-basis, with `single` being the default type if omitted (e.g. `OFF="off",HEAT="heat",COOL="cool",ECO="eco:dual",AUTO="auto:dual"` or `dualModes="AUTO,ECO",tripleModes="<mode1>,<mode2>,..."`).
- Limit requests and responses based on current mode setpoints type (e.g. if a request for dual setpoints is received and current mode is cooling, send an [error response](https://developer.amazon.com/docs/device-apis/alexa-thermostatcontroller.html#error-handling); same for state reporting and current mode is auto, only include upper/lower setpoints in response)
- Rename `comfortRange` metadata parameter to `minimumTemperatureDelta`, defaulting to 4°F/2°C, in line with the [Nest Alexa skill](https://support.google.com/googlenest/answer/9325080?hl=en). With that setup, the upper and lower setpoints would be set the same way then previously, using half of the delta configured as step value, when a target temperature is requested. For direct requests, both setpoints would be updated only if the requested temperature delta is greater or equal to the parameter, otherwise, an error response would be sent.

**Comment by jsetton** [comment]
@digitaldan Any thoughts on this one? 😄

**Comment by digitaldan** [comment]
I'm not sure I understand bullet 1, can you explain what the issue is that needs to be solved?  For bullet 2 I'm not sure i understand why when receiving a dual set point command would result in an error depending on what mode the thermostat is in?  For the last bullet, I'm fine with changing the default, i think i borrowed those , including the comfort range label from the ecobee skill  (or one of the major thermostat vendors).  ComfortRange seems to me to better describe what this is then minimumTemperatureDelta, maybe heatCoolTemperatureDelta  or upperLowerTemperatureDelta would be better?

**Comment by jsetton** [comment]
So the main reason for this change is to support thermostats that handles different setpoint modes based on thermostat modes. For example, I have a Nest thermostat which has the three setpoints (target, upper & lower) available to be mapped. Currently, if I map all of them with the skill, Alexa will consider my thermostat in triple mode no matter which mode it is on. This mean, I would get the 3 setpoints temperatures when asking for the thermostat status.

The change I am proposing is to bridge that gap and introduced thermostat/setpoints mode awareness, while still remaining backward compatible to the previous implementation. Using the Nest example, the thermostat should be considered in single mode with cooling and heating thermostat modes while in dual mode with auto or eco thermostat modes. Ultimately, the thermostat should never be considered in triple mode, even though the three setpoints are mapped.

Anyway, the PR, I submitted above, includes all these changes. I decided to keep `comfortRange` metadata parameter but slightly changed its behavior based on the thermostat mode, which I think makes sense. Basically, if requesting to set a single target temperature in dual mode and the thermostat mode is cooling, only the upper setpoint will be updated to that temperature, opposed to previously setting a range around it. It is the same behavior for heating mode updating the lower setpoint. Anything with other thermostat mode would fallback to the original logic.

When I initially made this logic change it made sense but now that I think about it more, cooling and hearing thermostat modes should always be considered as single mode. The problem is that in most cases, the target setpoint controls the temperature but in other setup where only the upper (cooling) and low (heating) setpoints are available, like with Z-Wave thermostats, we would need to add a way to determine which setpoint should be use in single mode (currently, it only uses target setpoint)

What do you think?

**Comment by digitaldan** [comment]
That makes sense to me.  I was also thinking about this yesterday that we could be more intelligent with the comfortRange when the thermostat is already in a desired mode, so i think thats a useful feature.  

>cooling and hearing thermostat modes should always be considered as single mode.

Not sure i understand this?  Do you mean for thermostats that have a target temperature setting (like nest)?  FYI my venstar thermostats do not have a target temp either

**Comment by jsetton** [comment]
> Not sure i understand this? Do you mean for thermostats that have a target temperature setting (like nest)? FYI my venstar thermostats do not have a target temp either

I meant that if a thermostat has heating and cooling modes and only have upper/lower setpoints defined, like yours, we should consider that the upper setpoint is basically the target point for the cooling mode and the same for heating with lower setpoint.

This means that when asking Alexa to change or check the state of the thermostat temperature setpoint in these modes, only the upper or lower setpoints would be updated/reported. Therefore, you wouldn't get a range back, as it is currently implemented, but the actually target value based on either the upper or the lower setpoint.

In the same idea, I am wondering if we should do the same automatically for all modes based on the defined setpoint properties and not provide a metadata parameter. The only issue is that triple mode would not be supported. Although, I have yet to see a thermostat supporting that mode.

`AUTO` => (1) `upperSetpoint` + `lowerSetpoint`; (2) `targetSetpoint`
`COOL` => (1) `targetSetpoint`; (2) `upperSetpoint`
`HEAT` => (1) `targetSetpoint`; (2) `lowerSetpoint`
`ECO` => (1) `upperSetpoint` + `lowerSetpoint`; (2) `targetSetpoint`
`OFF` => `<empty>`

**Comment by digitaldan** [comment]
Apologies if i sound dense, still trying to understand all the nuances around this

>AUTO => (1) upperSetpoint + lowerSetpoint; (2) targetSetpoint

 what does (1)  and (2) mean here? what is "upperSetpoint + lowerSetpoint"  represent? 

So for you above list, discovery still looks the same as it does today?
```js
 "supported": [{
                  "name": "targetSetpoint"
                },
                {
                  "name": "lowerSetpoint"
                },
                {
                  "name": "upperSetpoint"
                },
                {
                  "name": "thermostatMode"
                }
              ],
```

Or are you saying we would only have a target temperature, so the thermostat would look like:
```
 "supported": [{
                  "name": "targetSetpoint"
                },
                {
                  "name": "thermostatMode"
                }
              ],
```
 And we would set upper and lower setpoints to the specific asked value when in HEAT/COOl mode, and use the comfort range calculation when in AUTO mode?

**Comment by jsetton** [comment]
> what does (1) and (2) mean here? what is "upperSetpoint + lowerSetpoint" represent?

The number defines the logic order. So for the `AUTO` thermostat mode, if `upperSetpoint` and `lowerSetpoint` are defined in endpoint properties, then just use these two as setpoint properties, otherwise fallback to `targetSetpoint` which should be defined at that point. The "+" sign is just to show that both properties would be used and basically indicates dual mode. Same goes for `COOL`, use `targetSetpoint` if defined, otherwise fallback to `upperSetpoint`.

But again, the only concern with all this, is that we would drop triple mode support. Do you know if there is any precedence of a smart thermostat that supports that mode? It actually doesn't even make sense to me of what it represents unless a user wants to setup the target temperature for the current mode, and the temperature range for when the thermostat changes to a dual-enabled mode.

I just feel that having this automated is much better than forcing users to configure the setpoint mode for each of their thermostat mode if not already part of supported bindings.

> So for you above list, discovery still looks the same as it does today?
> Or are you saying we would only have a target temperature, so the thermostat would look like:

No change will happen at the discovery level. All this logic is to determine the actual setpoints that are relevant when a temperature setpoint change or state report request is received. An endpoint can have all 3 setpoint properties defined (that's how my Nest is configured) but we won't use all of them at the same time. You should check some of the test cases I added in PR #272. Maybe that would help to understand a bit.

> And we would set upper and lower setpoints to the specific asked value when in HEAT/COOl mode, and use the comfort range calculation when in AUTO mode?

Correct if the thermostat endpoint is configured with only the `upperSetpoint` and `lowerSetpoint` properties.

There is one point I just realized I forgot is that for `upperSetpoint` and `lowerSetpoint`, I think the Alexa API expects both setpoints to be reported back. So we may not be able to have the state report to be one setpoint when setup that way. I will have to do some testing. So the logic I mentioned above would be more for change requests.

**Comment by jsetton** [comment]
> There is one point I just realized I forgot is that for `upperSetpoint` and `lowerSetpoint`, I think the Alexa API expects both setpoints to be reported back. So we may not be able to have the state report to be one setpoint when setup that way. I will have to do some testing. So the logic I mentioned above would be more for change requests.

I did some testing and we can rename either `upperSetpoint` or `lowerSetpoint` property, in cooling or heating mode respectively, to `targetSetpoint` in the context response object, even though it wasn't defined in the discovery object. That way the voice commands and app status would work as expected.

So I updated my original PR #272 with the logic I outlined above and it is working very well with my Nest thermostat 😄 No need for extra metadata parameter. As I mentioned before, the triple mode, which I am still trying to figure out its purpose, isn't supported when the thermostat/setpoint mode awareness logic is active.

@digitaldan you should give it a try. I would love to hear how it is meshing with your thermostat. I am thinking of merging this one before v2 to limit the number of conflicts.

**Comment by jsetton** [comment]
So I went ahead and merged/deployed the v2 change so we don't have to wait for this one.

**Comment by digitaldan** [comment]
Great, i'm traveling this week for work  (and next) , so if i seem a little MIA its b/c i'm not in one place long enough to be useful here :-)

**Comment by jsetton** [comment]
No worries. I just realized that the setpoint channels for the auto and eco on a Nest thermostat are different.

So I am thinking of adding that support. I have to think about it. My first thought would be to use property component with supported mode (e.g. `alexa="ThermostatController.upperSetpoint:AUTO"`) in order to get multiple setpoints linked to a specific mode included in the property map configuration.

**Comment by jsetton** [comment]
@digitaldan So I added the [multi-channel dual mode setpoints support](https://github.com/openhab/openhab-alexa/pull/272/commits/808f63a2fc82e2d245834a432434358925203a22), I mentioned above, to the initial PR by introducing a concept of property tagging (e.g. `ThermostatController.upperSetpoint#eco`). I still need to update the usage documentation but I wanted to run the concept by you to see what your thoughts are.

Basically, my thermostat item config using the Nest binding would look like this. When the thermostat is in dual eco mode, the eco setpoints would be used, otherwise it would fallback to the standard dual mode setpoints.
```
Group gThermostat "Thermostat" {alexa="Endpoint.Thermostat"}
String ThermostatHVACMode "HVAC Mode"(gThermostat) {alexa="ThermostatController.thermostatMode", channel="nest:thermostat:account:foobar:mode"}
Number:Temperature ThermostatCurrentTemperature "Current Temperature [%.1f °F]" (gThermostat) {alexa="TemperatureSensor.temperature", channel="nest:thermostat:account:foobar:temperature"}
Number:Temperature ThermostatTargetTemperature "Target Temperature [%.1f °F]" (gThermostat) {alexa="ThermostatController.targetSetpoint", channel="nest:thermostat:account:foobar:set_point"}
Number:Temperature ThermostatTargetTemperatureMax "Maximum Target Temperature [%.1f °F]" (gThermostat) {alexa="ThermostatController.upperSetpoint", channel="nest:thermostat:account:foobar:max_set_point"}
Number:Temperature ThermostatTargetTemperatureMin "Minimum Target Temperature [%.1f °F]" (gThermostat) {alexa="ThermostatController.lowerSetpoint", channel="nest:thermostat:account:foobar:min_set_point"}
Number:Temperature ThermostatEcoTemperatureMax "Maximum Away Temperature [%.1f °F]" (gThermostat) {alexa="ThermostatController.upperSetpoint#eco", channel="nest:thermostat:account:foobar:eco_max_set_point"}
Number:Temperature ThermostatEcoTemperatureLow "Minimum Away Temperature [%.1f °F]" (gThermostat) {alexa="ThermostatController.lowerSetpoint#eco", channel="nest:thermostat:account:foobar:eco_min_set_point"}
```

All the thermostat setpoints determination logic I mentioned previously with the tagging support is here:

https://github.com/openhab/openhab-alexa/blob/808f63a2fc82e2d245834a432434358925203a22/lambda/smarthome/alexa/v3/capabilities.js#L335-L368

**Comment by digitaldan** [comment]
Sorry this has taken so long, I'm not sure why this is so hard to keep straight in my head!  

A question about the "#eco" mode qualifier.  Do we need to add another concept for users (property tagging) , or would it be easier to to have a `ThermostatController.ecoLowerSetpoint` property ?  I worry about the Alexa config becoming too complex for users. 

I'm good with the PR and functionally otherwise, i did try this out in September and it worked fine.

**Comment by jsetton** [comment]
> A question about the "#eco" mode qualifier. Do we need to add another concept for users (property tagging) , or would it be easier to to have a ThermostatController.ecoLowerSetpoint property ? I worry about the Alexa config becoming too complex for users.

The idea was to make this concept reusable in the future and also easily parsable. Anyway, we would still need a delimiter since `ThermostatController.ecoLowerSetpoint` would not plug in easily in the current capability property schema logic.

How about we keep the current implementation and just update the documentation to use "#eco" for integration that uses separate dual setpoints for eco mode and not mention the term tag? I think this would be less confusing to the users.

**Comment by jsetton** [comment]
@digitaldan I just committed a [small change](https://github.com/openhab/openhab-alexa/pull/272/commits/60d1913818e4324524078ca6e671fe1df49f8619) to the PR based on my suggestion below. Let me know what you think.
