### ISSUE TITLE
Open Close Raise Lower Commands Semantic Extensions Support

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#283]
Amazon just [announced](https://developer.amazon.com/blogs/alexa/post/49eff766-5d95-4faf-9205-2ab52ae8a437/announcing-updated-smart-home-building-block-apis-non-controllable-device-states-semantic-extensions-and-expanded-international-support) support for open, close, raise and lower commands via sementic extensions using mode, range and toggle controllers.

It seems Amazon is focusing on improving these controllers instead of creating specific ones that would have limited purposes. This means that we should probably start creating metadata labels for generic device using these controllers. For example, part of this enhancement, a blind-specific label should be included.

**Comment by CrispinP** [comment]
This functionality would be really cool. 

"Alexa, open the blinds" :)

**Comment by jsetton** [comment]
> This means that we should probably start creating metadata labels for generic device using these controllers.

Related to this point, the `CurrentHumidity` metadata label added in #292 is the first example.

**Comment by jsetton** [comment]
I have pushed a PR to add this support. Below are examples on how to configure [semantic extensions](https://developer.amazon.com/docs/device-apis/alexa-discovery.html#semantics-object) on the mode, range and toggle controllers. Additionally, the `Blind` and `Door` metadata label were added along with the [HomeKit](https://www.openhab.org/addons/integrations/homekit/#item-configuration) `WindowCovering` tag as an alias of the former.

@digitaldan let me know what you think.

**Mode**
```
String Shutter "Shutter" {alexa="ModeController.mode" [category="EXTERIOR_BLIND", friendlyNames="@Setting.Opening", supportedModes="Up=@Value.Open,Down=@Value.Close", actionMappings="Close=Down,Open=Up,Lower=Down,Raise=Up", stateMappings="Closed=Down,Open=Up"]}
```

**Range**
```
Rollershutter Blind "Blind" {alexa="RangeController,rangeValue" [category="INTERIOR_BLIND", friendlyNames="@Setting.Opening", supportedRange="0:100:10", unitOfMeasure= "Percent", actionMappings="Close=0,Open=100,Lower=(-10),Raise=(+10)", stateMappings="Closed=0,Open=1:100"]}
```

**Toggle**
```
Switch Door "Door" {alexa="ToggleController.toggleState" [category="DOOR", friendlyNames="@Setting.Opening", actionMappings="Close=OFF,Open=ON", stateMappings="Closed=OFF,Open=ON"]}
```
