### ISSUE TITLE
Brazilian Portuguese Support

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#289]
We need to add Brazilian Portuguese support by adding the Portuguese translation to Crowdin project.

**Comment by marceloarj** [comment]
I'm from Brazil and would like to help. I don't really know how eveything works but I can try for sure.

**Comment by jsetton** [comment]
Sure, once we add the Portuguese language to the Crowdin project below, you can help with the translations. Currently @digitaldan is the only person that can do so and is currently away until the end of the month. In the meantime, you can create an account for that service and familiarize yourself with it by looking at the other languages. Thanks!

https://crowdin.com/project/openhab-alexa

**Comment by jsetton** [comment]
@marceloarj The Portuguese language was added to the Crowdin project. Would you be able to help with the translation? Thanks!

**Comment by ivanfmartinez** [comment]
The language tha was added is Portuguese - Portugal (pt-PT), the new support for Alexa is Portuguese - Brazil (pt-BR)

**Comment by jsetton** [comment]
The [skill locale integration](https://github.com/openhab/openhab-alexa/blob/master/tools/updateSkillManifest.js#L57-L76) is only based of the language (pt) and uses the same translation for all associated regions.

**Comment by marceloarj** [comment]
> @marceloarj The Portuguese language was added to the Crowdin project. Would you be able to help with the translation? Thanks!

Sure, I will take a look at it

**Comment by ivanfmartinez** [comment]
I have made the translations, but I don't have any device like dimmer or thermostats to check if the examples are correct.

**Comment by jsetton** [comment]
@ivanfmartinez Thanks for the translations. I updated some of the utterances after running some voice command tests using the Alexa simulator. These are now merged #237.

The next step will be to get the skill re-certified. This will need to wait for @digitaldan.

**Comment by botura** [comment]
Any good news for brazilian OH users?

**Comment by jsetton** [comment]
Sorry for the delay. It took quite a bit of time to finally get the skill re-certified. Anyway, the skill is now available in Portuguese (BR) in the Alexa skill store, right in time for the openHAB 2.5 release 👍
