### ISSUE TITLE
ModeController seems to don't work with it-it locale

### ISSUE THREAD

**Issue by raneri** [openhab/openhab-alexa#298]
The locale support for italian (it-it) [has been added to the ModeController capability](https://developer.amazon.com/it/docs/device-apis/list-of-interfaces.html), so I expect it to work from here in Turin :)

Unfortunately I tried with a bunch of different item declarations and nothing seems to work. For example:

> String Lavatrice "Lavatrice" (Washer) {alexa="ModeController.mode" [supportedModes="Normale=Normale:Cotone,Delicati=Delicati:Seta",friendlyNames="Lavaggio,Ciclo",ordered=false]}

The Echo device finds the "Lavatrice" item but any voice command I try trows an error like "I don't know how to set Lavatrice to that Setting" (in italian, of course). I tried saying something like "Alexa, set the Lavaggio on the Lavatrice to Normale" (that in italian sounds like "Alexa, imposta lavaggio su lavatrice a normale") but I always receive the same error.

Maybe the locales that were unsupported when the v3 skill has been published are blocked at skill-level, even if they are now supported by Alexa?

Thank you for your answers.

**Comment by jsetton** [comment]
@raneri this is actually a known issue. While Amazon updated their documentation, it doesn't seem that the functionality is available currently. I have opened #299 to track this topic and provide latest updates.

> Maybe the locales that were unsupported when the v3 skill has been published are blocked at skill-level, even if they are now supported by Alexa?

In terms of the skill, there are no limitation in regards to using the mode, range, toggle controllers in other languages. However, the resources label text-based object locale is still limited to `en-US` based on [this](https://developer.amazon.com/docs/device-apis/resources-and-assets.html#label-object) documentation. This limitation is also [enforced](https://github.com/openhab/openhab-alexa/blob/master/lambda/smarthome/alexa/v3/capabilities.js#L249) in the skill at the moment.
