### ISSUE TITLE
Update mode range toggle controller regional availability

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#299]
Amazon [announced](https://developer.amazon.com/blogs/alexa/post/49eff766-5d95-4faf-9205-2ab52ae8a437/announcing-updated-smart-home-building-block-apis-non-controllable-device-states-semantic-extensions-and-expanded-international-support) additional Alexa locales support for mode, range and toggle controllers.

Based on the latest Amazon supported [list of interface](https://developer.amazon.com/docs/device-apis/list-of-interfaces.html) locales, the expectation should be that the additional locales support is available but after doing some testing, it doesn't seem to be the case. And others, based on [this](https://forums.developer.amazon.com/questions/216719/when-will-toggle-and-mode-controller-actually-supp.html) Amazon Developer forum thread, have experienced the same.

This is the reason why I reverted the initial changes #293, I had merged into the repository. Until Amazon clarifies what locale support is available, this feature will be considered unsupported. Since the skill doesn't actually limit interfaces on per language-basis, you are free to try without any guarantee of success.

**Comment by jsetton** [comment]
After doing some additional testing, I was able to confirm that the additional Alexa locales support for mode, range and toggle controllers are now working for global asset ids and text-based labels, even though the [documentation](https://developer.amazon.com/docs/device-apis/resources-and-assets.html#label-object) for the latter currently stipulates otherwise. Same with `en-CA` which oddly is the only locale not listed as supported but seems to be working fine.

Anyway, I have pushed a PR which adds that support including adding a skill catalog for asset ids used primarily for metadata labels (e.g. `CurrentHumidity`). That catalog supports locale ressources coming from Crowdin and is currently generated during the deployment process and stored with the skill, until Amazon give us a way to [upload our own](https://developer.amazon.com/docs/device-apis/resources-and-assets.html#upload-your-own-catalog)

@digitaldan Can you review this one? Looking for some feedback 😄

**Comment by digitaldan** [comment]
Hey @jsetton  I'm looking through the code now and will deploy and play with it today.  Any particular section you are looking for feedback on?  One question i have it how many entries/assets will the catalog have?  Right now i see its just Humidity.  The reason i ask is if there are not more, and soon Amazon will be allowing us to upload our own, do we need all the code around this PR.  Or, is this reusable with Amazon's upcoming change?   How many more assets to you see being added here?

**Comment by jsetton** [comment]
> Any particular section you are looking for feedback on?

Yes related to the catalog implementation which you just did 😄 

> One question i have it how many entries/assets will the catalog have? Right now i see its just Humidity.

Right now it is only for "humidity" as far as I can see. But I am sure we can be creative in the future. The idea, I mentioned before, is to have metadata labels that leverage the mode, range & toggle controllers and specific default parameters in order to lower the configuration complexity related to these interfaces. Otherwise, I am afraid users would just stick to basic capabilities due to the complexity or keep asking in community forum how to setup these interfaces for standard devices that can easily be covered by a label.

I am currently working on adding the semantics support, which Amazon just released. Below is a preview on how complex the configuration for a simple window blind would look like:

```
Rollershutter WindowBlind "Window Blind" {alexa="RangeController.rangeValue" [supportedRange="0:100:1", presets="0=@Value.Close,100=@Value.Open", friendlyNames="@Setting.Opening", actionMappings="Close=0,Open=100,Lower=(-10),Raise=(+10)", stateMappings="Closed=0,Open=1:100"]}
```

> The reason i ask is if there are not more, and soon Amazon will be allowing us to upload our own, do we need all the code around this PR. Or, is this reusable with Amazon's upcoming change? How many more assets to you see being added here?

The idea behind the catalog implementation is that we would have a translation pipeline already in place (I actually already modified that pipeline for the skill manifest with this in mind), and just update the deploy tool script to generate the catalog and upload it to Amazon instead of including it with the skill code. So, we would reuse the majority of the code.

Also, the documentation related to the ability to upload our own catalog in the future hasn't change for almost a year. So, we could be waiting for a while or even they might decide not to implement in the end.

**Comment by jsetton** [comment]
@digitaldan I am going to merge the change for this issue since my testing using the Alexa simulator has been successful and the change for semantic extensions support is dependent on this one.
