### ISSUE TITLE
Add scenes tag / capability

### ISSUE THREAD

**Issue by Dom1n1c** [openhab/openhab-alexa#30]
I noticed, that Smart Home Skills could provide scenes.
This might be useful, so that we don't have to use switches for scenes.
"Alexa, Switch scene... on"

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-scenes-in-a-smart-home-skill

**Comment by digitaldan** [comment]
I was just looking at this as well.  This would be very easy to implement, I'm a little hesitant to add new tags until we have https://github.com/eclipse/smarthome/issues/1093  figured out.

**Comment by HenniOVP** [comment]
Hi,
Any news on the scenes topic?
Looking through the code, I noticed that ["SCENE_TRIGGER"](https://github.com/openhab/openhab-alexa/blob/4a8e753915b10143b73c150aa5b5d22da330236a/oh2.js#L573) is already mentioned, but not implemented. As well the readme hints with "Alexa turn on Home Theater Scene" that there could be such a feature.
I would very much like to help with this topic. Concerning JavaScript my knowlege is very little, but if there is a way to do something to push this topic, it'd be intresting to know.

Cheers,
Hendrik

**Comment by jsetton** [comment]
In case, this support will not be part of the initial release of the v3 ported skill [#54], I have implemented the scene trigger support with the current version.

jsetton@f5e6a6352fc0ef4a4b183387d886a997458312a0

Here is an item definition example:

```
// Define a scene with on/off capability (default)
Switch sceneOne "Scene One" ['Scene']
// Define a scene with on capability only
Switch sceneTwo "Scene Two" ['SceneOn']
// Define a scene with off capability only
Switch sceneThree "Scene Three" ['SceneOff']

// Define an activity with on/off capability (default)
Switch activityOne "Activity One" ['Activity']
// Define a scene with on capability only
Switch activityTwo "Activity Two" ['ActivityOn']
// Define a scene with off capability only
Switch activityThree "Activity Three" ['ActivityOff']
```

Based on the [API reference](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/archive/shv2-providing-scenes-in-a-smart-home-skill#discoverappliancesresponse-requirements-to-describe-a-scene) guide, the only difference between an activity and a scene is if the changes in that entity must occur in a specific order or not. I am not sure how this difference is represented on the Amazon side as both activities and scenes are showing in the scenes discovered tab and are actionable when called directly. However, when using routines, it seems that only activities are available as scene commands.

**Comment by digitaldan** [comment]
This is implemented in the upcoming v3 skill, closing.
https://github.com/openhab/openhab-alexa/blob/v3/ohConnectorV3.js#L522
