### ISSUE TITLE
no connection to my openhab-cloud server

### ISSUE THREAD

**Issue by lukasl96** [openhab/openhab-alexa#309]
After setting up, deploing and activating the skill alexa found 0 items.

I checked my nginx acces logs and can't see any access from the skill.

i tried both in config.js, openhab-cloud.domain.com and home.openhab-cloud.com.

**Comment by jsetton** [comment]
Have you checked the skill Lambda function logs? Make sure to increase the log level by setting the function environmental variable `LOG_LEVEL` to `INFO`.

**Comment by lukasl96** [comment]
Hi jsetton, sorry I'm a totaly noob in AWS and Lambda. Where can I find the logs and set the log level to info?

**Comment by jsetton** [comment]
Now that I think of it, which region are you located in? You need to make sure to deploy your Lambda function in the proper Lambda region as indicated in the [requirement notes](https://github.com/openhab/openhab-alexa#alexa-skills-kit-cli-with-amazon-aws-and-developer-accounts).

In regards to AWS, try to access your AWS console. Logs are in Cloudwatch > Log Groups and the skill function settings in Lambda > Functions. Amazon provides a bunch of [documentation](https://docs.aws.amazon.com/) to help navigate through their services if necessary.

**Comment by lukasl96** [comment]
Hi jsetton, thank you so much!
The log output says that the server isn't reachable
`{
    "event": {
        "header": {
            "namespace": "Alexa",
            "name": "ErrorResponse",
            "payloadVersion": "3",
            "messageId": "68690199-51c8-4964-8ee7-9d322cad4e6f"
        },
        "payload": {
            "type": "BRIDGE_UNREACHABLE",
            "message": "Server not accessible"
        }
    }`

But I cant see the BaseUrl

**Comment by jsetton** [comment]
You should have gotten an error logged prior to that line. If you can't see it, set the `LOG_LEVEL` to `DEBUG` to get more information.

**Comment by lukasl96** [comment]
the only bad thing i see in the log is
`WARN: RequestError: write EPROTO 139859762177920:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802`

I checked my ssl via ssllabs.com and got A+

the warning appears at:
`{
    "directive": {
        "namespace": "Alexa.Discovery",
        "name": "Discover",
        "token": "####censored###"
    }
}`

**Comment by lukasl96** [comment]
i think the skill tries to use the bearer token instead of the basic auth. I modified the config.js for basic atuh i think this part isn't working

**Comment by jsetton** [comment]
> i think the skill tries to use the bearer token instead of the basic auth. I modified the config.js for basic atuh i think this part isn't working

The skill will always receive a bearer token from the Amazon Login integration. As long as you set the basic auth user/pass in your config.js, that authentication method will be used over bearer token.

From a quick Google search, it seems that this could happen with node.js 8.10. Not sure what the root cause but some are suggesting to bump the Lambda function version to node.js 10.x. Can you give a try?

**Comment by lukasl96** [comment]
changing to node.js 10.x was the trick. Thank you so much!
