### ISSUE TITLE
Let Alexa know her location

### ISSUE THREAD

**Issue by staehler** [openhab/openhab-alexa#31]
Hi,
I've a alexa for each room, so I don't want need to say "alexa switch livingroom lights on". It should be enough to say "alexa, switch on the light", as she knows what room she is placed in. 
Do you have any plans to implement such a feature?

Onother point is, that there could be a default light (kind of device) for each room, which means, when I have some light in my livingroom, alexa should know which light is the default.
This means, when I have three lights in my livingroom, I'ld like to default one of my lights, which is switched, when I just say "alexa, switch light on".

At the moment I need to say "alexa, switch the TV light in the livingroom on" and could be shorten to "alexa, switch light on".

Do you think it's possible and worth to think about?

Thanks for your efforts,
Michael

**Comment by Dom1n1c** [comment]
You could use similar items, then you might be able to assign them to the amazon echo device, you prefer. For example 'Light, Lights', 'Licht, Lichter'
So then you have one echo dot in the kitchen, it listens for light 
The other one in the kitchen could listen for lights

**Comment by digitaldan** [comment]
>Do you have any plans to implement such a feature?

We are at the mercy of the Smart Home API which does not allow this.  I wish Amazon would allow you to associate devices or their groups to a specific echo/dot/room.  One not so great solution is to setup each echo/dot under a different amazon account that you link to OH.  Then you would create a  group (in the alexa app) called "Lights" and add the item(s) you want that echo/dot to control.

> For example 'Light, Lights', 'Licht, Lichter'

Alexa, for me at least, get very confused when the names are very similar to each other.

**Comment by Protestallianz** [comment]
Maybe one could use the device id? Like Kodi did? Or is this custom skill only?
https://github.com/m0ngr31/kodi-alexa#controlling-more-than-one-instance-of-kodi

But as most people are not self hosting I am note quite sure where to put the config file. Maybe there is a way to send the device id to openhab and one could make a rule ?

**Comment by roben** [comment]
You can create smart home groups directly within the alexa app and also assign echo devices to the group. This way she'll know the room (=group) she should default to, so you can simply say "Alexa, light off".

**Comment by Protestallianz** [comment]
True, but this option is new and also not quite comfortable as it doesn't work for me with openhab items exposed to alexa. (I have to use the connection between the hue bridge directly). Color Hues coming directly from the bridge have a bulb icon. "Color Items" from OpenHab are having a Switch icon.

Furthermore, this is not a quite good way as you split up your configs in different places (openhab,  alexa, hue bridge (at least for better names of the bulbs). 

Additionally, I want to get rid of the HUE bridge in the future and as said above, OH Items are "not supported".

**Comment by roben** [comment]
> Furthermore, this is not a quite good way as you split up your configs in different places (openhab, alexa, hue bridge (at least for better names of the bulbs).

This would only work if you register every echo dot in OH otherwise. And then you have your Echo Dot configuration split up in two places.

> it doesn't work for me with openhab items exposed to alexa. 

Yes it does, I'm using it this way. OH is my only smart home skill. This way I have a centralized interfaces for all my (not so) smart devices (Tradfri, Z-Wave, custom stuff).

**Comment by Protestallianz** [comment]
> Yes it does, I'm using it this way. OH is my only smart home skill. With OH I have a centralized interface for all my smart home devices (Tradfri, Z-Wave, custom stuff).
Mhm I always get the response "Light doesn't support that" (Whereas naming the Item by its OH name works perfect.) What kind of icon do they have in the alexa app?

> And then you have your Echo Dot configuration split up in two places [....]
> OH is my only smart home skill
Yes, but I would rather split the alexa config once and then work in OH (Ones Smart Home changes all the time) than using the buggy and slow Alexa app for configuration instead of openhab.

**Comment by roben** [comment]
> What kind of icon do your OH items have in the alexa app?

They are shown as switches, but at least in German "Switch XYZ on/off" and "Set XYZ to N percent" works just fine.

**Comment by Protestallianz** [comment]
Sorry for the late response: Yes "Switch xyz on/off" works (but that wasnt the question).

"Switch THE LIGHTS On" only works with "Light Smarte Homedevices" in alexa as it is stated in this thread by somebody else: https://community.openhab.org/t/official-alexa-smart-home-skill-for-openhab-2/23533/512?u=rickecho

**Comment by staehler** [comment]
@roben 
Please correct me if I'm wrong: I just can create one group with the name "light", right? As I have three Alexas in different rooms, I want all of them to switch the ligt in her room (bathroom, living room, bedroom).
Your suggestion works only for one room/group, otherwise I need to define for each room another groupname, like light, lights, lighting or so. Or do I something wrong?
What I want is, when I'm in a room, Alexa should switch the devices in this particular room. I'ld like to say "switch light on" in bathroom or bedroom and light should go on either in badroom or in bedroom.

**Comment by roben** [comment]
Maybe you can create a single item for every room in OpenHAB which triggers all the lights in this room with a rule. If you export each as "lights" (or maybe "lights <room name>" works, too) to Alexa and put each in a different group assigned to the Alexas, each Alexa should react properly to "Switch lights on". I did not try this out but it sounds as it could work ;)

**Comment by Protestallianz** [comment]
Have not tried this as well but why should it work? It seems like it only works when is category "light" in alexa but unfortunately every item (no matter the openhab) is identified as a "switch". See also here for the fix: https://github.com/openhab/openhab-alexa/issues/57

I kinda solved it by using the native hue detected lights, so at least my rooms with hue lights work with "light on/off" (completely ignoring openhab)

**Comment by digitaldan** [comment]
Hi all, a small fix was deployed today which should enable "smart home groups" with items tagged as ["Lighting"] .  In the alexa mobile (don't use web) app you can create a new group, add your light(s) and the associated echo/dot and it will respond to "lights on/ lights off" for just that group.     You might need to remove your devices in the alexa app and have alexa re-discover them for this to work (have not verified if thats necessary, but i think it might be).

Are we ok to close?

**Comment by xibriz** [comment]
Tested this now. Works OK. Can say `Alexa, lights off` and `Alexa, dim to 50%`

No need to re-discover.

**Comment by staehler** [comment]
Tested it as well, works fine :-) I can confirm, there is no re-discovery necessary. Thanks a lot.

**Comment by staehler** [comment]
@digitaldan As far as I could find out, there is an individual deviceId returned within the json from alexa service, which could look like this:
```
cat bad_alexa.json |jq 
{
  "version": "1.0",
  "session": {
    "new": true,
    "sessionId": "amzn1.echo-api.session.826dfa8d-fdb9-4f8b-b0a4-7e818c2d0753",
    "application": {
      "applicationId": "amzn1.ask.skill.2bd908b6-37f4-48e0-9bb8-618b3eda7301"
    },
    "user": {
      "userId": "amzn1.ask.account.AFL7OX46HW5VN6NI2GM3AOWK2524SSA3R4RI3MDLIZ6CRB6FZITB2X7UB4NKA7Q3WOV7HVLSXE5L4UO2UFZ3MLO6KPTSFS7OGIWBQ5TYTQW5CD4K4US7TO54OAZ2AWJ5KWG4V2WAZRY5VDRYS3EQADVYRPQEIZSVZVHWI6DP7TYIO3EB65WQ66PB3RXDNMOBXYGBKDA2BXXXXX"
    }
  },
  "context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.2bd908b6-37f4-48e0-9bb8-618b3eda7301"
      },
      "user": {
        "userId": "amzn1.ask.account.AFL7OX46HW5VN6NI2GM3AOWK2524SSA3R4RI3MDLIZ6CRB6FZITB2X7UB4NKA7Q3WOV7HVLSXE5L4UO2UFZ3MLO6KPTSFS7OGIWBQ5TYTQW5CD4K4US7TO54OAZ2AWJ5KWG4V2WAZRY5VDRYS3EQADVYRPQEIZSVZVHWI6DP7TYIO3EB65WQ66PB3RXDNMOBXYGBKDA2XXXXX"
      },
      "device": {
        "deviceId": "amzn1.ask.device.AES5MNCU47N7OIWXTEZWBZHGXXHOZ6UE3LKFAUTDWD5CRWS5X5YI6PNYFGX7PHANZIVAXNUFXAOFX7XS6UKYRDTDWZQXKKTQWULDHZ2IWDQ3ORS6DNGJMDSC7WCRZ4PJEKBLKG4NBOFZZ72YIMMERDIESELBE",
        "supportedInterfaces": {
          "AudioPlayer": {}
        }
      },
      "apiEndpoint": "https://api.eu.amazonalexa.com",
      "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjJiZDkwOGI2LTM3ZjQtNDhlMC05YmI4LTYxOGIzZWRhNzMwMSIsImV4cCI6MTUyMTkxMDExNSwiaWF0IjoxNTIxOTA2NTE1LCJuYmYiOjE1MjE5MDY1MTUsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUVTNU1OQ1U0N043T0lXWFRFWldCWkhHWFhIT1o2VUUzTEtGQVVURFdENUNSV1M1WDVZSTZQTllGR1g3UEhBTlpJVkFYTlVGWEFPRlg3WFM2VUtZUkRURFdaUVhLS1RRV1VMREhaMklXRFEzT1JTNkROR0pNRFNDN1dDUlo0UEpFS0JMS0c0TkJPRlpaNzJZMlJKSDRDV0FIQVNRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUZMN09YNDZIVzVWTjZOSTJHTTNBT1dLMjUyNFNTQTNSNFJJM01ETElaNkNSQjZGWklUQjJYN1VCNE5LQTdRM1dPVjdIVkxTWEU1TDRVTzJVRlozTUxPNktQVFNGUzdPR0lXQlE1VFlUUVc1Q0Q0SzRVUzdUTzU0T0FaMkFXSjVLV0c0VjJXQVpSWTVWRFJZUzNFUUFEVllSUFFFSVpTVlpWSFdJNkRQN1RZSU8zRUI2NVdRNjZQQjNSWEROTU9CWFlHQktEQTJCUkJWQzNRIn19.jyC2zZPMv1SBpR_2EaspjM1X6FIzZDU42UHdCiMOgq6s-Z8CGRwkj5HRZBAsMAOgfgoWBJJVgcOnqgKIYa99BaauXHcHrgDLZWfIaVc503XyKN6F7_fF8ZRuKopxHeMhJCY9f4glptTGzapCk2lKS6E2WyoXko26da7cYWLQ4hwj75WwRhL1W2P0sGB2QIM869yoek9TE-l2a4mOI3qqha-LvK9j-Rtr28ay-Q95w32AZs7zzVMmq5v0MRUtaBVcl1nFo7lXgLy-0kfJ19aSPjNKQMngCiWJZhX2AaUx5wv1u_rNK1vGGuIiun4zG58lzRGqTIEOcr-xxxxxxxx"
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "amzn1.echo-api.request.3b4ac920-e1b3-44df-8704-xxxxxxx",
    "timestamp": "2018-03-24T15:48:35Z",
    "locale": "de-DE",
    "intent": {
      "name": "CheckTemperatureIntent",
      "confirmationStatus": "NONE"
    }
  }
}
```

Wouldn't it be possible to connect devices to one dedicated alexa, so that there is no need to say the location (bedroom, bathroom, ...)? At the moment I just can switch on/off the lights, but wouldn't it be nice to switch just any group of devices, without saying the room? I'ld like to say, switch on the music and switch the blinds to 100%.

I've really no idea, if this is possible at the moment, I occasianlly just found out that my alexas have individual deviceIds.

Maybe you already had a look at this?
Thank you for your effort!

**Comment by digitaldan** [comment]
This should already be there with Alexa "Smart Groups".  Using the mobile app (do not use the web version, option is not there), create a new group (say bedroom), there you can associate a specific alexa device along with any smart home devices.  Any devices under the category "lights" will respond to "turn all lights on/off" when asked from that alexa.  Right now the category is fixed in the v2 of the binding, so anything tagged "lighting" or "switchable" I think is considered a light.  In the upcoming v3 version this is configurable per item , see https://github.com/digitaldan/openhab-alexa/blob/v3/README.md#item-configuration
