### ISSUE TITLE
VoiceProfile Permission

### ISSUE THREAD

**Issue by Trinitus01** [openhab/openhab-alexa#311]
Would it be possible to add permissions based on VoiceProfile?

Example: Use an item tag to set permission for the item based on a specific user

**Comment by jsetton** [comment]
I assume you are referring to this feature [announcement](https://developer.amazon.com/blogs/alexa/post/1ad16e9b-4f52-4e68-9187-ec2e93faae55/recognize-voices-and-personalize-your-skills). 

Going over Amazon's [documentation](https://developer.amazon.com/docs/custom-skills/add-personalization-to-your-skill.html#set-up-your-skill-to-support-personalization), it looks like this feature is only available for standard skills based on how the structure of the request is formatted to include that information.

I did a quick test enabling the `alexa:person_id:read` permission in the skill manifest and, as expected, I didn't see any voice profile data attached to my smart home requests.

**Comment by andrelung** [comment]
This would be a great addition to home automation setups. Any chance that this will be implemented at some point? 


Probably there is a good reason openhab-alexa is using the smart home skill architecture. By the looks of it, right now one would need to create a custom skill, right? Starting with your experiece: Would an integration with openhab be possible?

**Comment by jsetton** [comment]
> Any chance that this will be implemented at some point?

There isn't much that can be done currently until Amazon decides to extend that feature to smart home skills.

> By the looks of it, right now one would need to create a custom skill, right?

Correct. One possibility is that the voice profile feature may carry over once the [Custom Intent support](#164) is made available for smart home skills. Although there is no guarantee this functionality will be released in the end as it has been in developer preview for close to a year now.
