### ISSUE TITLE
Private Openhab Alexa skill unable to invoke Openhab AWS lambda

### ISSUE THREAD

**Issue by keshavpeswani** [openhab/openhab-alexa#320]
Hi,

I have deployed alexa skill (as mentioned in README) and did a successful authorization (oauth2) with private openhab cloud  deployment by alexa skill in oauth2clients  and oauth2scopes. The skill is unable to invoke the lambda (successfully deployed in eu-west-1, Ireland) and hence, no commands are invoked. Can someone help me where I am going wrong ?

The region and locale is all correct as mentioned over [here](https://github.com/alexa/alexa-smarthome/issues/28)  but still the skill isnt able to invoke lambda.

Thanks
Keshav

**Comment by jsetton** [comment]
Two questions:

- Did you make sure to specify the proper `baseURL` setting in your config.js?
- When you are stating the skill isn't able to invoke your lambda function, were you able to confirm in the skill logs that no requests came in?

**Comment by keshavpeswani** [comment]
Hi @jsetton ,

Thanks for looking into the issue. 

- Yes, i have specified `baseURL` to my private openhab alexa skill.

- Yes, I could see no invocations happening at the lambda. Also, i was just testing the skill on alexa skill developer console (after enabling in app), so i guess the requests is coming to skill. Is there a way to check whether requests are coming to skill or not. how do i ensure that requests are going to skill ?

**Comment by jsetton** [comment]
> Also, i was just testing the skill on alexa skill developer console (after enabling in app), so i guess the requests is coming to skill.

If testing with the Alexa simulator through the developer console is working, this means your skill is accessible. So, I am not sure exactly what the problem is. Maybe something to do with your OAauth2 integration, which may not come into play via the simulator but does when a request is issued through an Echo device. Have you checked your cloud connector logs? Unfortunately, I am not too familiar with that setup. I usually point the skill directly to the OH server.

> Is there a way to check whether requests are coming to skill or not. how do i ensure that requests are going to skill ?

As I mentioned above, you should check your Lambda function logs. You can use some of the guidelines I mentioned in issue #309 if you unsure how to get to them.

**Comment by keshavpeswani** [comment]
@jsetton : Sorry if i didnt sound it right earlier but there are **no invocations** happening at lambda even though I am testing the skill from alexa developer console. This is what is causing the problem. I have matched the skill Id and and application id in alexa smart home trigger in lambda. 
Also, my lambda is deployed in eu-west-1 and my locale is set to English(IN), and the default endpoint in my skill is set to arn of the lambda. Is there something else that I am missing over here ?

**Comment by jsetton** [comment]
When you say "no invocations", are you saying you don't see any Lambda logs for the skill function? 

Moreover, have you looked at your Cloud connector logs? Do you see any OAuth2 requests?

Also, have you done a discovery? Do you see any device listed in your Alexa Smarthome console?

**Comment by keshavpeswani** [comment]
@jsetton : Please find the answers inline :

> When you say "no invocations", are you saying you don't see any Lambda logs for the skill function?
  Yes, there arent any lambda logs since there arent any invocations. By invocations, i mean that the request is not being reached to lambda.
> Moreover, have you looked at your Cloud connector logs? Do you see any OAuth2 requests?
     I see oauth2 request for `/oauth2/authorize` when i enable the skill in alexa app. There arent any oauth2 requests other than that in logs.
> Also, have you done a discovery? Do you see any device listed in your Alexa Smarthome console?
    Yes, I have done discovery, but even for discovery the skill needs to invoke lambda and then only
    it can get to know what all devices are there. My problem is that lambda is not being invoked/called by the skill at all .

**Comment by jsetton** [comment]
Can you confirm that the skill is actually enabled on your Alexa account? In the skill settings, you should see that the status of "Account Linking" as "linked". I am thinking that maybe the OAuth2 linking may have not succeed causing the skill not to be enabled on your account. If it is linked properly, maybe unlink and link back the skill just to be sure and give it another try.

Also, can you confirm that your Amazon [account location](https://www.amazon.com/gp/help/customer/display.html?nodeId=202205900) is India? If this is the case, then the Lambda region location listed in Amazon's documentation may be incorrect.

Try to deploy the skill in the Far East and than North America regions, and see if the Lambda function gets invoked there. When redeploying with the ASK-CLI, you will need to reset `.ask/config`, just keeping your current skill id, as follow:

```
{
  "deploy_settings": {
    "default": {
      "skill_id": "<skillId>",
      "was_cloned": false,
      "merge": {}
    }
  }
}
```

**Comment by LuckyMallari** [comment]
same issue here. Not seeing any invocation at all. No logs in OH cloud aside from the initial OAuth request when linking

**Comment by keshavpeswani** [comment]
@jsetton : Thanks , the issue was my amazon.com default country settings which was fixed using the [link](https://www.amazon.com/gp/help/customer/display.html?nodeId=202205900)

**Comment by keshavpeswani** [comment]
Closing the issue
