### ISSUE TITLE
Use none standard ports

### ISSUE THREAD

**Issue by jmccoy555** [openhab/openhab-alexa#328]
Hi all, 

I've just changed ISP and there is something odd going on with accessing my server at home on port 443, I have found that other ports work reliably. 

I have tried to redeploy the skill (from master is this the best branch to use?) with config.js file populated; for the url I have something like this;

`baseURL: 'https://openhab.my.domain:8443/rest',`

but I'm not having any luck. 

I have checked the url from my mobile and am presented with a basic login page, which I can login to and am able to get to the rest page. 

Should this work, or is changing the port not supported? 

Thanks.

**Comment by jsetton** [comment]
> Should this work, or is changing the port not supported?

I am not 100% sure. Have you checked your Lambda function logs?

**Comment by jmccoy555** [comment]
Hi, sorry I must have missed the notification. 

Yes I have tried with no luck, so I'm presuming it isn't supported. 

I also noticed there are some 443 within the code which tried changing to 8443 and redeploying, but didn't have any luck with that either.

**Comment by jsetton** [comment]
> Yes I have tried with no luck, so I'm presuming it isn't supported.

Are you saying you don't see any logs or there are no errors? Either or, it won't be related to the skill code. There are three reasons I can see why your setup working isn't working: (1) Your server on port 8443 isn't accessible from the Internet; (2) Your SSL certificate for your domain is not valid; (3) Your Lambda function isn't deployed in the correct region based on the skill language you are trying to use.

**Comment by jsetton** [comment]
@jmccoy555 were you able to resolve your issue? If so, can this issue be closed?

**Comment by jmccoy555** [comment]
Sorry for the delay, been a bit tied up entertaining a baby!!

I have managed to fix my port 443 issue, so have deployed without any modification, and all is working.

I wasn't able to get it working on a different port, but I guess this is a bit of an edge case anyway.

FYI - 1. verified from my phone, user and password correct and could reach the REST api, 2. valid cert in place, verified with 1, 3. using same settings as now working config (other than changing back to port 443. 

So, I either did something wrong, or it is not possible to use a none standard port. 

I'll close this as I'm back up and running now on port 443. 

Thank anyway.
