### ISSUE TITLE
use home openhab, not myopenhab.org

### ISSUE THREAD

**Issue by llamahunter** [openhab/openhab-alexa#33]
I'd prefer not to have a questionably secure cloud service in between the alexa service and my home openhab installation.  I sort of trust amazon opsec, not so much that of myopenhab.org.  I do have my openhab server available via https and username/password auth on a port on my home firewall for use by the openhab iPhone app.  I'd prefer to hook up alexa directly to that.

**Comment by digitaldan** [comment]
Then you are free to setup your own skill and point it directly to  your OH.  See https://github.com/openhab/openhab-alexa/blob/master/config_sample.js#L10

**Comment by llamahunter** [comment]
Ah, great. I didn't see this in the initial docs I read. My bad.

**Comment by llamahunter** [comment]
One more question... why does the github page say that openHAB Cloud is "preferred" over direct access to the home server? Is there an advantage?

**Comment by digitaldan** [comment]
No, but setting up a smart home skill is not for the faint hearted.  Just make sure your proxy server is using real SSL certs (lets encrypt work).  Also I don't test at all using this method, but I have been very strict about this skill only using the standard OH REST API and not anything special on myopenhab.

**Comment by llamahunter** [comment]
sweet... thx.  I think I will set up my own skill for the time being.  I'd like to +1 the goal of keeping to the official REST API so that direct communication continues to be possible.

**Comment by llamahunter** [comment]
Alright, after wrestling with all that oath setup and such, and fiddling with the SSL cert chain that safari and chrome are happy with, but apparently openssl is not, it's all working.  Thx!

**Comment by 2devnull** [comment]
Here are some icons for this that you can put into the Publishing Information section. Hopefully modifying this was OK.

![openhab-logo-square108](https://user-images.githubusercontent.com/4563854/29528721-0b8eab3a-866b-11e7-8cd3-f7c278d9e396.png)
![openhab-logo-square512](https://user-images.githubusercontent.com/4563854/29528722-0b91e49e-866b-11e7-9a53-8aabe3a73c0e.png)

**Comment by kaikreuzer** [comment]
> Hopefully modifying this was OK.

Honestly, I am not too keen on seeing the logo modified for special purposes. What speaks against using the plain logo?

**Comment by 2devnull** [comment]
Absolutely nothing. I'll pull these down. Thanks for the feedback.

**Comment by llamahunter** [comment]
Very clever, tho.
