### ISSUE TITLE
RangeController.rangeValue and Number items

### ISSUE THREAD

**Issue by oeiber** [openhab/openhab-alexa#346]
Hi, 
is it possible to support for RangeController.rangeValue Number items as well? I have a lot of proxy items, which I want to reduce. 
Thank you!

**Comment by jsetton** [comment]
It's already [supported](https://www.openhab.org/docs/ecosystem/alexa/#rangecontroller-rangevalue).

**Comment by oeiber** [comment]
Hi @jsetton,
I‘m sorry. There was an error with copy and paste. My question is: Is it possible to sipport number items for ToggleController.toggleState?
Thank you!

**Comment by jsetton** [comment]
Could you please elaborate on the use case? I can't see why a binding would use a Number item for on/off switching capability. If your goal is to control two modes, you can model that item as `ModeController.mode`.

**Comment by oeiber** [comment]
Because of the problem with sending off commands to ModeController.mode items (https://community.openhab.org/t/alexa-three-state-switch-with-modecontroller-mode/88743), my idea was to combine ModeController.mode and ToggleController.toggleState in one item without defining multiple items and groups...

**Comment by jsetton** [comment]
> my idea was to combine ModeController.mode and ToggleController.toggleState in one item without defining multiple items and groups...

The `ToggleController.toggleState` capability only sends ON/OFF commands which `Number` item doesn't support. So this would not be possible anyway.
