### ISSUE TITLE
Get Lamba ARN failiure after ask deploy

### ISSUE THREAD

**Issue by JornHermans** [openhab/openhab-alexa#348]
Followed your readme and stubled upon this error after running ask deploy

root@# ask deploy
[Error]: Get Lambda ARN alexa-openhab failure for smartHome/default.
UnrecognizedClientException: The security token included in the request is invalid.

**Comment by jsetton** [comment]
The error is self-explanatory. The AWS credentials you provided aren't valid. Make sure to initialize the ASK-CLI first.
