### ISSUE TITLE
Problems with item discovery

### ISSUE THREAD

**Issue by lukeIam** [openhab/openhab-alexa#349]
Since I upgraded to openhab 2.5 (and the installation of the Amazon Echo Control Binding) I have serious problems with the discovery of my items:

- items that are part of a group endpoint discovered as own devices in alexa
- some "parent" items of those group endpoints are not discovered at all, some are next to their sub item's device
- re-discover does not find more devices
- discovered devices can be controlled with the alexa app and via voice
- the number of devices flagged "unresponsive" in alexa increased but in most cases they can be controlled anyway (but that could be caused by a a problem I have with missing status updates from the mqtt binding)

My setup:
- openhab 2.5 stable
- openhab-alexa on aws 
- latest alexa app

What I tried so far:
- deleted all devices from alexa (multiple times)
- updated openhab-alexa to the lastest master branch
- deleted openhab cache
- checked the cloudwatch logs -> no errors

Example item:
```
Group gKueche "Küche"
Group gKuecheLicht "Licht (Küche)" (gKueche) {alexa="Endpoint.Light"}
Switch Kueche_Licht "Licht" (gKuecheLicht) {alexa="PowerController.powerState", channel="switch433:switch433:switch433_1:current_state"}
```
`Kueche_Licht` is discovered as `switch` in alexa with the name `state`. The exact same item file was discovered as a single `light` named `Licht (Küche)` before.
I do have more complex non working group endpoints but this is the simplest example.

Can you please give me a hint what happened? If you need further information please let me know.

**Comment by jsetton** [comment]
> re-discover does not find more devices

Follow the [troubleshooting guide](https://www.openhab.org/docs/ecosystem/alexa/#device-not-found). Stagger your changes. You probably have an item incorrectly setup causing the discovery to silently fail on the Alexa side.

> the number of devices flagged "unresponsive" in alexa increased but in most cases they can be controlled anyway (but that could be caused by a a problem I have with missing status updates from the mqtt binding)

You need the proper state to be available for the skill to poll otherwise the device will be considered unresponsive.

> checked the cloudwatch logs -> no errors

You should add environmental variable `LOG_LEVEL=info` to your Lambda function to get additional log information.

> `Kueche_Licht` is discovered as `switch` in alexa with the name `state`. The exact same item file was discovered as a single `light` named `Licht (Küche)` before.
I do have more complex non working group endpoints but this is the simplest example.

I just tried your example and it looks good on my end, with the expected device name on the Alexa side.

```
{
  "endpointId": "gKuecheLicht",
  "manufacturerName": "openHAB",
  "friendlyName": "Licht (Küche)",
  "description": "Group gKuecheLicht via openHAB",
  "displayCategories": [
    "LIGHT"
  ],
  "cookie": {
    "propertyMap": "{\"PowerController\":{\"powerState\":{\"parameters\":{},\"item\":{\"name\":\"Kueche_Licht\",\"type\":\"Switch\"},\"schema\":{\"name\":\"powerState\"}}}}"
  },
  "capabilities": [
    {
      "type": "AlexaInterface",
      "interface": "Alexa",
      "version": "3"
    },
    {
      "type": "AlexaInterface",
      "interface": "Alexa.PowerController",
      "version": "3",
      "properties": {
        "supported": [
          {
            "name": "powerState"
          }
        ],
        "proactivelyReported": false,
        "retrievable": true
      }
    },
    {
      "type": "AlexaInterface",
      "interface": "Alexa.EndpointHealth",
      "version": "3",
      "properties": {
        "supported": [
          {
            "name": "connectivity"
          }
        ],
        "proactivelyReported": false,
        "retrievable": true
      }
    }
  ]
}
```

**Comment by thedannymullen** [comment]
Make sure when you delete things try deleting from Amazon one thing at a time.  The delete all function does not always clear them out.

**Comment by thedannymullen** [comment]
> Since I upgraded to openhab 2.5 (and the 
installation of the Amazon Echo Control Binding) I have serious problems with the discovery of my items:

@lukeIam the echo control binding is not used when echo discovers items.  This is all based on my openHAB and the alexa skill.

**Comment by lukeIam** [comment]
hi @jsetton, @thedannymullen,

> You probably have an item incorrectly setup causing the discovery to silently fail on the Alexa side.

indeed - today I manged to fix my problematic mqtt backed item (had a JS transformation with a lambda function and that seems to let the status updates fail silently). After the item was fixed, I deleted all alexa devices and magically everything was as it should.
Didn't know that a faulty but controllable item could cause such a discovery trouble.

Thanks for pointing me in the right direction!

> You should add environmental variable `LOG_LEVEL=info` to your Lambda function to get additional log information.

> Make sure when you delete things try deleting from Amazon one thing at a time. The delete all function does not always clear them out.

Good to know if I have a problem again...
