### ISSUE TITLE
When deployed to eu-west-1 not working

### ISSUE THREAD

**Issue by JornHermans** [openhab/openhab-alexa#355]
When i deploy to the eu-west-1 lambda service, i can't discover any devices.
When i deploy to the us-east-1 lambda service, i can discover all my devices.

I tried multiple times it always works on the us servers buth not on the eu servers, what could be the issue?

**Comment by jsetton** [comment]
> I tried multiple times it always works on the us servers both not on the eu servers, what could be the issue?

If it is working deploying to `us-east-1`, this means that your Amazon account country/region setting is set to the United States or another country in the America continent. If you want your skill to point to `eu-west-1`, you would have to [transfer your Amazon account](https://www.amazon.com/gp/help/customer/display.html?nodeId=201248840) to a European country.
