### ISSUE TITLE
error on deploy "Invalid skill manifest"

### ISSUE THREAD

**Issue by mabadil** [openhab/openhab-alexa#363]
When try to deploy with  ask-cli@^1.0.0 (node 8.3) i have this error "Invalid skill manifest"

**Comment by jsetton** [comment]
Can you post the command and error output? Also can you run `ask --version` to confirm the version?

**Comment by mabadil** [comment]
ask --version 1.0.0

comand
ask deploy
Invalid skill manifest.

**Comment by jsetton** [comment]
Did you run `npm install -g ask-cli@^1.0.0`? It should install `1.7.23`.

**Comment by mabadil** [comment]
perfect. I try to npm install -g ask-cli@^1.7.23 and work
Thanks.
