### ISSUE TITLE
Unable to discover devices with OH3

### ISSUE THREAD

**Issue by candiesdoodle** [openhab/openhab-alexa#366]
I have been playing around with OH3 snapshot versions and noted alexa discovery for new devices fails with OH3.
So i hosted my own OH Cloud and connected to local OH3. I also hosted by copy of alexa skill on AWS/ Amazon. Looking at the nginx logs, there is a failure with the first of the two Get requests:
````javascript
34.XXX.XXX.XXX - xxx@xxx.com [15/Sep/2020:19:28:22 +0000] "GET /rest/services/org.eclipse.smarthome.i18n/config HTTP/1.1" 401 76 "-" "-"
34.XXX.XXX.XXX - xxx@xxx.com [15/Sep/2020:19:28:22 +0000] "GET /rest/items/?fields=editable%2CgroupNames%2CgroupType%2Cname%2Clabel%2Cmetadata%2CstateDescription%2Ctags%2Ctype&metadata=alexa%2Cautoupdate%2Cchannel%2Csynonyms HTTP/1.1" 200 1269 "-" "-"
````

The failed request is evident from the 401. The relevant code is here: [lambda/smarthome/alexa/v3/directives/discovery.js](https://github.com/openhab/openhab-alexa/blob/7679e6549844563bf60a6197a2f86504c71b9fb5/lambda/smarthome/alexa/v3/directives/discovery.js#L50)

 One thing is that probably the package `org.eclipse.smarthome.i18n` doesnt exist in OH3. But changing this package name to `org.openhab.i18n' also results in the same issue.

On local OH3 server, this is the debug log from the OH cloud connector. Request 18 resulted in failuere (possibly corresponding to the first Get request from above) while Request 19 did not (the second Get request i suppose). The complete log is here: [https://pastebin.com/7h0SKKUi](https://pastebin.com/7h0SKKUi)
````javascript
2020-09-16 00:58:21.228 [DEBUG] [io.openhabcloud.internal.CloudClient] - Got request 18
2020-09-16 00:58:21.239 [DEBUG] [io.openhabcloud.internal.CloudClient] - {"host":"openhab.mydomain.com","cache-control":"no-cache","accept-encoding":"gzip, deflate","accept":"application/json","user-agent":"openhab-cloud/0.0.1"}
...
2020-09-16 00:58:21.391 [DEBUG] [io.openhabcloud.internal.CloudClient] - Got request 19
2020-09-16 00:58:21.411 [DEBUG] [io.openhabcloud.internal.CloudClient] - {"host":"openhab.mydomain.com","cache-control":"no-cache","accept-encoding":"gzip, deflate","accept":"application/json","user-agent":"openhab-cloud/0.0.1"}
...
2020-09-16 00:58:21.541 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent headers to request 18
...
2020-09-16 00:58:21.564 [DEBUG] [io.openhabcloud.internal.CloudClient] - {"headers":{"Transfer-Encoding":"chunked","Server":"Jetty(9.4.20.v20190813)","Date":"Tue, 15 Sep 2020 19:28:21 GMT","Content-Type":"application/json"},"responseStatusCode":401,"responseStatusText":"OK","id":18}
2020-09-16 00:58:21.667 [WARN ] [io.openhabcloud.internal.CloudClient] - Jetty request 18 failed: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
2020-09-16 00:58:21.689 [WARN ] [io.openhabcloud.internal.CloudClient] - Response Failure: HTTP protocol violation: Authentication challenge without WWW-Authenticate header
2020-09-16 00:58:21.726 [DEBUG] [io.openhabcloud.internal.CloudClient] - Finished responding to request 18
...
2020-09-16 00:58:21.950 [DEBUG] [io.openhabcloud.internal.CloudClient] - Sent content to request 19
2020-09-16 00:58:21.983 [DEBUG] [io.openhabcloud.internal.CloudClient] - Finished responding to request 19
````

Overall, this results in a failed discovery.

I then tried with commenting out the Get requests to `org.eclipse.smarthome.i18n` and `org.eclipse.smarthome.core.i18nprovider` and used this code in `discovery.js` and it worked. Was able to discover and control devices.
````javascript
Promise.all([
      rest.getItems(
        this.directive.payload.scope.token, this.timeout)
//      rest.getServiceConfig(
//        this.directive.payload.scope.token, 'org.eclipse.smarthome.i18n', this.timeout),
//      rest.getServiceConfig(
//        this.directive.payload.scope.token, 'org.eclipse.smarthome.core.i18nprovider', this.timeout)
    ]).then((data) => {
````

I wasnt sure where to post this or if this is this an issue with the openhab core packages or the alexa lambda code.

**Comment by jsetton** [comment]
Thanks for all the details. After running the latest OH3 snapshot, there are two things that seem to have changed in OH3:

- The regional settings service pid is now `org.openhab.i18n` in OH3, as you pointed out (Similar change #341)\
- The rest services config calls seems to require the new admin authentication added in OH3 which is oddly not enforced on items calls. This one might be tricky because in theory it means these calls need to go through two authentications; the first being either the cloud connector or your own http authentication, if connected directly, and the second one being the new admin authentication at the server level.

**Comment by jsetton** [comment]
@digitaldan since the second point I mentioned above is also affecting the cloud connector, I am wondering how we could resolve these authentication errors with OH3.

**Comment by candiesdoodle** [comment]
Thank you for the reply. Will wait for a solution.
Considering that I commented out the API call to services config and it seemed to wrok fine, is there a reason why this is called during alexa discovery? Can we just leave it out?l and only make a single call to get the items?

**Comment by jsetton** [comment]
> Considering that I commented out the API call to services config and it seemed to wrok fine, is there a reason why this is called during alexa discovery? Can we just leave it out?l and only make a single call to get the items?

The services config calls are used to determine the user's [regional settings](https://www.openhab.org/docs/ecosystem/alexa/#regional-settings). If you aren't using some of the interfaces leveraging these settings or the default values are covering your setup, then these aren't necessary.

**Comment by digitaldan** [comment]
yes, i was actually thinking about this over the weekend as i moved my main system to oh3.  As you pointed out, basic REST calls are not authenticated ( for the time being), but certain calls do require a admin level authentication using oauth and tokens.  I may need to have @ghys weigh in on options here.   Off the top of my head, i could see a couple solutions, one would be to push the Alexa token to a users openHAB when the cloud binding connects and and allow the alexa request to also pass its token back with the config request and let our auth system verify the two, but I have not really though about the feasibility of such a solution.  We could also look at trying to not use the config call, or possible evaluating if those regional settings could somehow be exempted from auth (or moved/duplicated somewhere else)?  Maybe the cloud connector binding can expose a new API for this, or push the required config settings to our cloud service, and we make an API call there?   Disabling auth for the cloud connector is not an option as it would open a huge hole up when using our cloud service with any client.  Maybe @ghys has another suggestion ?

**Comment by jsetton** [comment]
> We could also look at trying to not use the config call, or possible evaluating if those regional settings could somehow be exempted from auth (or moved/duplicated somewhere else)?

Now that I think about it, since we are planning to have a new binding for the Alexa skill going forward, we wouldn't need to make these calls since we would get the regional settings through the binding and for users, who didn't migrate to use the binding, they would be forced to specify these settings in their Alexa configuration. And ultimately, if the basic REST calls end up requiring admin authentication, then at that point, we would require the usage of the binding which I think will be what we want to aim for in the end.

**Comment by ghys** [comment]
In OH3 you can get the locale (language + region) in the root `/rest/` resource.
It will be in the format `en_US`, `de_DE`, or just the language (`fr`) if you didn't specify the region.
You don't have the unit system though, but I suppose you could take metric by default and imperial if the region is US, LR or MM.

**Comment by jsetton** [comment]
This could work, although having the ability to query the REST service config would be the cleanest solution. The unauthorized service config call response errors would need to be handled gracefully, at the skill level, to allow concurrent REST calls. However, some users may not necessarily have a unit system in sync with the region they are located in. If this is the only solution available, any chance to have this information passed at that level as well?

Also, out of curiosity, are there plans in the future to directly leverage the new OAuth2 authorization layer part of OH3 through the cloud connector?

**Comment by jsetton** [comment]
@ghys I have opened feature request https://github.com/openhab/openhab-core/issues/1678 to have the measurement system passed in the root resource. I noticed in your original change you pointed to the potential need to include additional `org.openhab.i18n` service config properties.

It would make it much easier to have that information available to implement a quick fix for OH3 users.

**Comment by jsetton** [comment]
I merged a fix for this one. It also supports the `measurementSystem` property that was just added by @kaikreuzer to the OH3 root resource based on my feature request. I also improved the 2.x service config requests where only the supported service pid will now be queried based on the api version.

@candiesdoodle I was able to test this change on a barebone OH3 install without any issue. Can you please update your skill setup and let me know if it is working for you? Once you confirm, I will update the live skill.

**Comment by candiesdoodle** [comment]
Thank you.
I can confirm that this is now working fine on my cloud and alexa setup. Devices are correctly discovered.
Thanks again

**Comment by Tukks** [comment]
Hello,
Thanks for your work.
Do you know when this issue will be addressed in OH3?
Thanks

**Comment by jsetton** [comment]
The live skill has now been updated and will now work with OH3.

**Comment by Tukks** [comment]
Thanks, it work great!
