### ISSUE TITLE
Devices not discovered

### ISSUE THREAD

**Issue by chriswalker01** [openhab/openhab-alexa#377]
Hi everyone,

I have deployed the Alexa Skill and got it linked to my Openhab Cloud instance. This all went pretty smoothly.

I have also linked the skill in the Alexa app. When doing this, I was definitely taken to my url for auth, so I didn't accidentally select the official skill.

The issue I'm having is that no Openhab devices are found when I tell Alexa to discover the devices.

I switched back to myopenhab.org and the official skill and the devices were discovered again, so it's not an config issue in my Openhab items.

I'm using English AU and so the Lambda is deployed in us-west-2 and I can see it being invoked when I ask Alexa to discover devices.

Any ideas what might be going on here?
![image](https://user-images.githubusercontent.com/14160438/102461128-136e3e80-409c-11eb-9d44-f94429e8cc0d.png)

**Comment by jsetton** [comment]
You should increase the log level by setting the environment variable `LOG_LEVEL` to `info` in your Lambda function. That way you can see what requests are sent to your function.

**Comment by chriswalker01** [comment]
Thanks @jsetton for the reply. I've enabled info logging and have an error.
401. Does this point towards my mongo db entries being wrong?
![image](https://user-images.githubusercontent.com/14160438/102681395-17719c00-4215-11eb-8f0f-bd2bb4fcd377.png)

**Comment by jsetton** [comment]
> Does this point towards my mongo db entries being wrong?

If it were the case, you would have gotten an error when you first enabled the skill and went through the account linking process, unless you made some changes after that. If so, you should disable and re-enable the skill. Also, it could be that you setup by mistake the username/password settings in the `config.js` file. These shouldn't be set if using OAuth2 authentication.

**Comment by chriswalker01** [comment]
That's what I thought. Before posting here, I removed the entries from mongodb and was unable to link the skill. I then re-added the entries and was able to link again. 

I just realised I don't have a config.js file. I have config-production.json and config-development.json and I'm guessing I was meant to rename one of them to just config.js and update accordingly, with my domain name etc?

I'll give that a shot and report back.

**Comment by jsetton** [comment]
> I just realised I don't have a config.js file. I have config-production.json and config-development.json and I'm guessing I was meant to rename one of them to just config.js and update accordingly, with my domain name etc?

I am talking about this [config.js](https://github.com/openhab/openhab-alexa/blob/master/lambda/smarthome/config_sample.js). You seem to mix up cloud connector and Alexa skill configuration. You certainly need one for the skill that indicates where the Lambda function needs to send requests to.

**Comment by chriswalker01** [comment]
You were very quick to reply. I realised we were talking about different files a second after posting.

I haven't touched config.js, but it looks like I could do away with Openhab Cloud if I were to use it. I'm only using Openhab Cloud to allow Alexa to work.

If I were to set up a reverse proxy with basic auth, what steps would change when creating the skill? Would ``ask api create-account-linking -s <skillId>`` still be required? If so, what would the auth urls be? https://openhab.myserver.com/oauth2/authorize returns 404 when going direct to my openhab instance.

**Comment by jsetton** [comment]
> If I were to set up a reverse proxy with basic auth, what steps would change when creating the skill? Would `ask api create-account-linking -s <skillId>` still be required? If so, what would the auth urls be? https://openhab.myserver.com/oauth2/authorize returns 404 when going direct to my openhab instance.

Per the [documentation](https://github.com/openhab/openhab-alexa#oauth2-provider), if going with a direct server level authentication method, you should use Login with Amazon to bypass the Alexa Smart Home skill OAuth2 authentication requirement.

**Comment by chriswalker01** [comment]
Thank you, thank you! Updating the baseurl in config.js has done trick.

Thanks for your help. I really appreicate it.
