### ISSUE TITLE
Selection from a dynamic list (String Channel)

### ISSUE THREAD

**Issue by peepshow-21** [openhab/openhab-alexa#378]
Hi,

I'm currently looking at Alexa and GA to access my devices and have a real need for the dynamic selection.

I have OpenHab connected to my Kodi box. Kodi has a channel (String) which is used to play/open a favourite. When you add the channel as an item, PaperUI show the item as a list of favourites as a Combo Box of string values, you pick the selection from the combo box, and Kodi plays/opens the content. Example list "BBC 1", "Apollo 13", "Radio Station", "Tube Channel". I'd like to say "play/set [favourite] BBC 1 on Kodi".

The list of favourite's can't be a predefined list in the item, as it's whatever the user has currently decided to tag as a favourite in Kodi. But all the options are returned to OpenHab has as a list of strings via the thing's channel.

Channel;
![image](https://user-images.githubusercontent.com/42150988/102526675-f0d82780-4093-11eb-86ff-721c9e287046.png)

Item
![image](https://user-images.githubusercontent.com/42150988/102526554-be2e2f00-4093-11eb-84e9-ac93394d9c2c.png)

I can get it to work in Alexa via mode, with a pre-defined list in the item.
![image](https://user-images.githubusercontent.com/42150988/102527686-6264a580-4095-11eb-8de4-7adb53ba4d5a.png)
This works as in concept, but useless in real, unless the list is dynamic.

Is this possilbe?

**Comment by jsetton** [comment]
For usage questions, you should post on the [community forum](https://community.openhab.org/).

I have responded to what I assume is the same question you [posted](https://community.openhab.org/t/alexa-with-paperui-things-items/109839/6) on that forum.
