### ISSUE TITLE
Skill does not work with openHAB 3.0 API Security

### ISSUE THREAD

**Issue by gnilebein** [openhab/openhab-alexa#383]
If "Implicit user role for unauthenticated requests"is disabled, the Alexa Skill stops working becaus it is not possible to define an API Key in Skill or openHAB Cloud.

**Comment by jsetton** [comment]
This was somewhat discussed in #366. The skill depends on how the cloud connector access a given openHAB server. There isn't much that can be done at the skill level.

Maybe this is something that can be discussed at the cloud connector level?
