### ISSUE TITLE
Integrate URL into settings

### ISSUE THREAD

**Issue by bd8392** [openhab/openhab-alexa#386]
I know that it is possible to build your own Alexa skill, and add the URL of your own server there...but would it also be possible to setup this directly via the Alexa interface for selfhosted installations? It's the only reason that I have the OpenHab cloud and maybe this could take off some load of the server...As OpenHab 3 has now authentication integrated, this would be a really cool option and not everyone has to build his own Alexa skill :-). Let me know If I can be of help here :-)

**Comment by jsetton** [comment]
Is your question about not having to setup a private cloud connector and pointing your own skill directly to your OH server? If so, this is already possible using one of the [server level authentication methods](https://github.com/openhab/openhab-alexa#openhab-server). And in OH3, you can allow the API Security Basic Authentication option.

**Comment by bd8392** [comment]
> Is your question about not having to setup a private cloud connector and pointing your own skill directly to your OH server? If so, this is already possible using one of the [server level authentication methods](https://github.com/openhab/openhab-alexa#openhab-server). And in OH3, you can allow the API Security Basic Authentication option.

Yes exactly :-) but as I understood, to use this function, you have to deploy your own Alexa-skill (which not everyone is capable of) and as soon as your URL changes, you would have to redeploy.

**Comment by jsetton** [comment]
> I understood, to use this function, you have to deploy your own Alexa-skill (which not everyone is capable of)

So your request is to have the official skill bypass the myopenhab cloud connector and point directly to your OH server? If so, that's not possible. If you aren't able to setup your own skill, then I would recommend using the standard setup via the myopenhab.org cloud connector.

**Comment by bd8392** [comment]
> So your request is to have the official skill bypass the myopenhab cloud connector and point directly to your OH server

Yes :-)

> If so, that's not possible.

Wouldn't it be possible to do that like for the "find my telephone" skill? There you have to setup your phone-number to use it... would be something like that not possible for the OpenHab-Skill to setup the link and Auth for your installation?

P.s.: I really have no idea about developing Alexa skills, but the docs from you are very good :-). Maybe I could do It, but I want to take of some load of the myopenhab.org server, because on days like today (where it failed) , it eats up the time of the volunteer supporters...if it's easier to selfhost in general, maybe we have less load... therefore I'm looking for solutions :-)

**Comment by jsetton** [comment]
> Maybe I could do It, but I want to take of some load of the myopenhab.org server, because on days like today (where it failed) , it eats up the time of the volunteer supporters...if it's easier to selfhost in general, maybe we have less load... therefore I'm looking for solutions

As mentioned on the [main page](https://github.com/openhab/openhab-alexa#intended-audience), the instructions to install your own skill are intended for developers. I'm glad you are conscientious about limiting your resource usage of the myopenhab.org server but I would reiterate my recommendation to keep using that workflow unless you get around and setup your own skill. There are no other way around this unfortunately.
