### ISSUE TITLE
No devices detected

### ISSUE THREAD

**Issue by hco** [openhab/openhab-alexa#39]
Hi,

Alexa does not discover any devices in my opehab 2 installation.
I tagged my items, and they are working with Homekit.
https://myopenhab.org/rest/items returns this: https://gist.github.com/hco/53a7e44939d7d08fdcc1b9f28efeedfc
Could maybe something with the thermostat be the reason? It's not working perfectly with homekit either.

I am from germany and am using Alexa in german.

**Comment by Dom1n1c** [comment]
try to reinstall openhab. I had similar issues with openhab-alexa and mqtt. A reinstall, keeping your configuration files was a solution in my case.

**Comment by hco** [comment]
I actually configured quite some stuff using the paper ui now, so I'd have to recreate those items & things.

Also, my response of /rest/items should be wrong in that situation, and I'd like to understand what's wrong about my items, as that could improve documentation.

Is there an easy way to execute the alexa js code, without having to setup an AWS Lambda Account etc?

**Comment by digitaldan** [comment]
>Also, my response of /rest/items should be wrong in that situation, and I'd like to understand what's wrong about my items, as that could improve documentation.

That would be great.  When Alexa does discovery she does a GET request at `http://myopenhab.org/rest/items` and iterates through every item.  On each items the code then iterates through an item's tags (if it has any).  If it finds a matching tag then it "discovers" it.  That's it actually.  Thermostats are a little trickier b/c of how we use groups to associate the different items/channels to a single thermostat object, but its almost the same.

See  https://github.com/openhab/openhab-alexa/blob/master/oh2.js#L545

**Comment by hco** [comment]
Okay, I already figured out, that it has something to do with the Thermostat. I'm not completly sure what it is, though.

**Comment by stulandr** [comment]
> After removing the tags from the thermostat the devices were discoverable

That's good to know.  I've not resolved my problem [here](https://community.openhab.org/t/official-alexa-smart-home-skill-for-openhab-2/23533/231?u=stulandr) so will try this to see if that makes a difference.

**Comment by stulandr** [comment]
I can report that removing the thermostat tags solved the problem an my other Switchable device is now discoverable.  Thanks @hco for the tip!

**Comment by mboremski** [comment]
@hco, did you finally solve this problem?

Did you see that in your [items.json](https://gist.github.com/hco/53a7e44939d7d08fdcc1b9f28efeedfc) your tags are empty?
