### ISSUE TITLE
Separate Label

### ISSUE THREAD

**Issue by delid4ve** [openhab/openhab-alexa#390]
For naturally spoken commands Alexa requires names such as Lamp or Light.  As it currently stands the skill utilises the openHAB label for this.

There are issues either way with this..

Example:
* All Lamps named as Lamp
    * openHAB ui everything indistinguishable and hard to manage
    * Alexa - naturally spoken, works correctly in groups

* Lamps named specifically such as Lounge Lamp
    * openHAB ui clean
    * Alexa - naturally spoken doesn’t work correctly as standard
    * Time consuming renaming in Alexa app to just Lamp
        * If corruption on Alexa profile this has to be done every time

My proposal is that a separate customLabel tag is added to the metadata for channels.  In order to provide backwards compatibility if the customLabel tag is not present then it defaults to the openHAB label.

Other workaround:
I don’t know how this applies to v3 ui but at present on 2.5.13 I do the following:
Create a separate group (if not already using advanced endpoints) for all channels required to be exposed and use the advanced meta on the item itself.

A small snippet of this can be found here:
https://community.openhab.org/t/evolvement-of-items-in-ohx/120315/11

**Comment by jsetton** [comment]
> My proposal is that a separate customLabel tag is added to the metadata for channels. In order to provide backwards compatibility if the customLabel tag is not present then it defaults to the openHAB label.

We could add an optional `name` metadata parameter that would take precedence over the item label if specified, similar to how it is implemented with the Homekit integration.

To be clear, based on the forum discussion you referred, there is no support for different names for a given device on the Alexa end as of yet, compared to Google Assistant which seems to allow it.
