### ISSUE TITLE
Separated by spaces channels aren't discovered by alexa

### ISSUE THREAD

**Issue by Trysupe** [openhab/openhab-alexa#391]
Hey there=)

Today I found an interesting issue with the alexa binding: 

When adding the alexa channels to the item there are no spaces allowed between the channels themselves. Let me show you:

This works:
```
Color Sprachassistent_Licht_Bett "Bett" {alexa="PowerController.powerState,BrightnessController.brightness,ColorController.color" [category="LIGHT"]}
```
This doesn't:

```
Color Sprachassistent_Licht_Bett "Bett" {alexa="PowerController.powerState, BrightnessController.brightness,ColorController.color" [category="LIGHT"]}
```

When using the second configuration alexa can't control the brightness of the item.

These spaces are automatically added (in my case) by the openhab alignment extension of vscode. I opened an [issue there as well](https://github.com/MaxBec/openHAB-Alignment-Tool/issues/59). However I thought it might be desirable to have the alexa binding also accept channels separated by spaces.

**Comment by jsetton** [comment]
> However I thought it might be desirable to have the alexa binding also accept channels separated by spaces.

Agreed 👍
