### ISSUE TITLE
node 10.x EOL on AWS

### ISSUE THREAD

**Issue by CyberLine** [openhab/openhab-alexa#393]
`We are ending support for Node.js 10 in AWS Lambda on July 30, 2021. This follows the Node.js language governing body declaring Node.js 10 end of life as of April 30, 2021 [1].`

So it should be ensured, that this package works with node 12.x or 14.x

**Comment by jsetton** [comment]
> So it should be ensured, that this package works with node 12.x or 14.x

12.x is passing the build test suite already and 14.x should be fine as well. Have you tried to change your Lambda function environment to any of these node.js versions?

For your information, you can check the [strategy matrix](https://github.com/openhab/openhab-alexa/blob/main/.github/workflows/build.yml#L20) for the build GitHub Actions job to see which versions are completing the test suite without errors.

Also, keep in mind that the initial node.js 10.x version when the function is created is driven by the ASK CLI (v1).
