### ISSUE TITLE
OH3.1 stable can't link to Skill using private hosted cloud

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-alexa#398]
Hi All,

Spent near 20hrs trying to get this to work with no avail. Comparing my cloud version, it says 1.0.10 (which appears old) - seems you've released 1.0.16 but not updated the v ersion number?

Anyway, I'm using the latest. Lambda/Skill deploy just fine, but it fails the linking process when the skill redirects you to the Cloud se server and requests you to allow OAUTH. 

Basic API Security is turned off, as requested by jeremy to not double auth.

Any suggestions?? Banging my head against a wall now! And the wife isnt happy :) Thanks

**Comment by jsetton** [comment]
For usage questions, you should post on the [community forum](https://community.openhab.org/).

I have responded to the question you [posted](https://community.openhab.org/t/private-alexa-skill-cant-access-via-private-cloud-oh3-1-stable/126633/10) on that forum.
