### ISSUE TITLE
Support for openhab 1.x

### ISSUE THREAD

**Issue by paphko** [openhab/openhab-alexa#4]
The current implementation only supports items with tags which are not available in OH1. I would suggest the following additional configuration for making items visible to the skill: dedicated groups. Groups are available in OH1 and OH2, so this solution should be independent of the server version.

A preconfigured group could be 'gAlexa' or simply 'Alexa'. When this group is configured in config.js, it can also be changed as desired. We can even allow a configuration of multiple groups so that all items in all groups are collected.
Furthermore, the configured groups could also reflect the supported [device types of smarthome skills](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference). Examples:

```
module.exports = {
    //userpass: 'user@foo.com:Password1',
    host: 'my.openhab.org',
    port: 443,
    path: '/rest/items/',

    generalGroups: ['Alexa'], // item type determines capabilities, e.g. percent for dimmers
    switchGroups: ['AlexaLights', 'AlexaSockets'], // allows on/off messages
    temperatureGroups: ['AlexaThermostats'], // allows temperature messages
    percentageGroups: ['AlexaDimmers', 'AlexaRollershutters'] // allows percentage messages
};
```

What do you think? I already tested switches with OH1 and it seems to work pretty well.

As part of this implementation, the code should be refactored to eliminate duplicate code (oh1.js and oh2.js are almost identical).

**Comment by paphko** [comment]
I mixed up REST API of OH1 and OH2 - it seems as if the REST API of OH1 does not provide information which items are contained in a group :-(

**Comment by paphko** [comment]
In case someone wants to try it out, too: https://github.com/paphko/openhab-alexa/tree/oh1_oh2_groups

I'll test this a few days and if it's stable, I'll create a PR.

**Comment by paphko** [comment]
Although this solution works, it has the drawback that the (technical) item names must be used as device names for voice recognition because the OH1 REST API does not provide a label for items. So if you want to use this Skill, you should set proper item names.

I think a PR is not needed because OH2 should replace OH1 quite soon.

**Comment by htreu** [comment]
A solution for OH1 might be to load the items from a special sitemap. This way you can provide separate item labels for voice control. The [OpenHAB-Homekit-Bridge](https://github.com/htreu/OpenHAB-HomeKit-Bridge) is implemented this way.

**Comment by paphko** [comment]
You're right, a sitemap would have been a more elegant solution :-)
However, since OH2 is officially released now, I'll rather concentrate any further work on that release.

**Comment by digitaldan** [comment]
I am closing as OH2 is now GA and we don't have an elegant way to support OH1
