### ISSUE TITLE
feature request: support personal profiles

### ISSUE THREAD

**Issue by McMornan** [openhab/openhab-alexa#401]
Hi,

I have some switches which I do not want anyone to be able to toggle via voice commands (lock of house entry door, internet access of my kids etc.) I have read in the alexa skill documentation that skills can use my personal profile. Would it be possible to give a user tag to an item (only allow specific user profiles)
(And yes: I have read this: "VoiceProfile Permission #311". But that was two years ago ...)

Thanks,
Lars

**Comment by jsetton** [comment]
As matter a fact, part of the upcoming major change, support for [networking capabilities](https://github.com/jsetton/openhab-alexa/blob/refactor/USAGE.md#networking-capabilities) was added. It pretty much consist in allowing network access control at the moment.

One interesting feature you will be happy about (if you are located in the US) is the ability to set voice profiles to limit the access control in the Alexa app. Interestingly, this implementation is solely handled on the Alexa side before sending the request to the smart home skill. That information is not even pass to the skill when receiving the relevant request.

You can sign up for the [beta test](https://community.openhab.org/t/openhab-skill-for-amazon-alexa-new-metadata-syntax-beta-test/125732) if you want/can test this feature.
