### ISSUE TITLE
Arabic Language Support

### ISSUE THREAD

**Issue by jsetton** [openhab/openhab-alexa#403]
[Amazon](https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2021/06/update-alexa-skills-for-arabic) announced Arabic language support back in June.

It introduces a new [Middle East endpoint](https://developer.amazon.com/en-US/docs/alexa/smarthome/develop-smart-home-skills-in-multiple-languages.html#deploy) to be deployed in `me-south-1`, which doesn't seem to be available neither in the [skill manifest documentation](https://developer.amazon.com/en-US/docs/alexa/smapi/skill-manifest.html#regions), nor in the Alexa Developer Console.

I have reached out to the Alexa Developer support team for additional clarification.

**Comment by whb611** [comment]
Inter

**Comment by jsetton** [comment]
Amazon corrected their documentation. Arabic language requests should be hitting `eu-west-1` endpoint after all.
