### ISSUE TITLE
Window Covering Rollershutter percentage values are inverted

### ISSUE THREAD

**Issue by rogrun** [openhab/openhab-alexa#449]
When I say "Alexa, open rollershutter" the rollershutter should move up. But it moves down. And when I say "... close rollershutter" it moves up. 

I've updated the matadata to:
`{alexa="RangeController.rangeValue" [category="INTERIOR_BLIND", friendlyNames="@Setting.Opening", supportedRange="0:100:10", unitOfMeasure="Percent", actionMappings="Close=0,Open=100,Lower=(-10),Raise=(+10)", stateMappings="Closed=0,Open=1:100"]}`

Before it was:
`{alexa="RangeController.rangeValue" [category="INTERIOR_BLIND", friendlyNames="@Setting.Opening", supportedRange="0:100:10", unitOfMeasure="Percent", actionMappings="Close=100,Open=0,Lower=(+10),Raise=(-10)", stateMappings="Closed=1:100,Open=0"]}`

I also deleted and rediscovered the rollershutter in the Alexa app.

But this has no effect.

**Comment by jsetton** [comment]
For usage questions, you should post on the [community forum](https://community.openhab.org/).

I would recommend using the new metadata syntax. [This forum post](https://community.openhab.org/t/rollershutters-stops-operating-with-alexa-today-direction-inverted/130033) should provide you with all the information you need to resolve your issue.
