### ISSUE TITLE
Rollershutter supported?

### ISSUE THREAD

**Issue by mboremski** [openhab/openhab-alexa#45]
Hey,
I was really impressed to see that we have a alexa skill.
Thanks for your work here.

While playing around I tried to include a rollershutter:
* in .item file
Adding the Switchable tag like mentioned in the Readme.md
  ```java
  Rollershutter Shutter_MaBo_AZ   "Rolladen Arbeitszimmer"   (MaBo_AZ, Shutters)   ["Switchable"]   {channel="..."}
  ```
* searched for new Devices in Alexa-App
The device "Rolladen Arbeitszimmer" is found.
So far so good
* asked Alexa to move it:
"Alexa, mach die Rolladen im Arbeitszimmer hoch
 (for engl. readers "Alexa, lift the rollershutter in Arbeitszimmer")
* Alexa says: "Ich habe Rolladen Arbeitszimmer nicht gefunden"
 (for engl. readers "I could not find Rollershutter Arbeitszimmer")

I also tried to use only "Arbeitszimmer" (without "Rolladen" in front) as Itemname.
Same result.

Am I doing something wrong?

Thanks for replying.

**Comment by digitaldan** [comment]
I'm afraid I'm a bit confused, and this is probably a language issue, but you have named your device "Rolladen Arbeitszimmer" ,  which I believe translates to "study rollershutters", but then you ask to "lift" the "rollershutter in the study".  

Alexa thinks the device is called ""Rolladen Arbeitszimmer", it does not know what those words mean, so you can't break them apart in commands, she's not that smart.  You need to ask her to turn on or off "Rolladen Arbeitszimmer".  Also I don't even know if Alexa knows what "lift" means, she would need to translate that to a ON/OFF command since you device is tagged as "Switchable", but according to the error message, she can't even find your device.

**Comment by htreu** [comment]
Hi @mboremski, in my setup I have extra items for alexa which are modelled like this:
`Rollershutter Shutter_Alexa_Kitchen "Rollladen Küche" [ "Switchable" ]`. In the skill the Rollershutter items will be translated to dimmable things which also accept percent values. So you are able to tell Alexa "Setze Rolladen Küche auf 100%". You need an additional rule to make this work in case your Rollershutters (like mine) do not accept position values in openHAB:
```
rule Rollershutter_Kueche
when
    Item Shutter_Alexa_Kitchen received command
then
    if (receivedCommand < 50) { // alexa versteht "0%" als 9....
      sendCommand(Shutter_GF_Kitchen, UP)
    } else {
      sendCommand(Shutter_GF_Kitchen, DOWN)
    }
end
```

**Comment by mboremski** [comment]
Found out something new...
I got two devices like this:
```
Rollershutter Shutter_MaBo_Kueche	"Rollade Küche"			["Switchable"]	{...}
Rollershutter Shutter_MaBo_AZ 		"Rollade Arbeitszimmer"	 	["Switchable"]	{...}
```

The commando "Alexa, setze Rollade Küche auf 50%" is working.
The commando "Alexa, setze Rollade Arbeitszimmerauf 50%" is not working.

If I rename like that:
```
Rollershutter Shutter_MaBo_AZ 		"Arbeitszimmer"	 		["Switchable"]	{...}
```
(so, removed "Rollade") the following commando works fine:
"Alexa, setze Arbeitszimmer auf 50%"

**Are there any limitations on the length of a label?**

**Comment by mboremski** [comment]
Finally found the Solution...
In germany since 1996 (Spelling Reform) we write "Rolllade" with three L.
My labels only had two L -> "Rollade"
Since Alexa uses new germany spelling rules for "Speech to text" my Labels did not match 💢 

Corrected it:
```
Rollershutter Shutter_MaBo_Kueche	"Rolllade Küche"		["Switchable"]	{...}
Rollershutter Shutter_MaBo_AZ 		"Rolllade Arbeitszimmer"	["Switchable"]	{...}
```
Now it works perfect.
