### ISSUE TITLE
Dimmer percentage commands broken

### ISSUE THREAD

**Issue by reinsch82** [openhab/openhab-alexa#462]
First: I'm really sorry, this probably won't be specific enough.

I use z-wave dimmers.
The percentage commands don't work anymore.
I assume it is related to 3.x.
It started a view weeks ago.
I'm using german.

**Comment by jsetton** [comment]
For usage questions, you should post on the [community forum](https://community.openhab.org/c/apps-services/amazon-alexa/66) following [these guidelines](https://community.openhab.org/t/about-the-amazon-alexa-category/101194).

**Comment by jsetton** [comment]
It looks like you actually created a post related to this issue. I have updated the category.

https://community.openhab.org/t/dimmer-percentage-command-broken/130927
