### ISSUE TITLE
Television device not discovered if Channel item type is string

### ISSUE THREAD

**Issue by erelor** [openhab/openhab-alexa#478]
Alexa can't discover Television device if Channel item type is String. Everything works if the channel type is Number.
If channel item type is Number: Alexa discover the device as a TV set and I can change channel item value by voice.
If channel item type is String: Alexa doesn't discover the device.

Here the configuration that doesn't work

Group item 
`  "TVSoggiorno": {
    "class": "org.openhab.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "gSoggiorno"
      ],
      "itemType": "Group",
      "tags": [
        "Equipment"
      ],
      "label": "TV Soggiorno",
      "category": ""
    }
  },
`

Group metadata
`  "alexa:TVSoggiorno": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "alexa",
          "TVSoggiorno"
        ],
        "uid": "alexa:TVSoggiorno"
      },
      "value": "Television",
      "configuration": {}
    }
  },
`

Channel item
`  "TVSoggiorno_Channel": {
    "class": "org.openhab.core.items.ManagedItemProvider$PersistedItem",
    "value": {
      "groupNames": [
        "TVSoggiorno"
      ],
      "itemType": "String",
      "tags": [
        "Point"
      ],
      "label": "Channel",
      "category": ""
    }
  },
`

Channel metadata
`  "alexa:TVSoggiorno_Channel": {
    "class": "org.openhab.core.items.Metadata",
    "value": {
      "key": {
        "segments": [
          "alexa",
          "TVSoggiorno_Channel"
        ],
        "uid": "alexa:TVSoggiorno_Channel"
      },
      "value": "Television.Channel",
      "configuration": {}
    }
  },
`

**Comment by jsetton** [comment]
> Alexa can't discover Television device if Channel item type is String. Everything works if the channel type is Number.

Are you using the LG webOS binding by any chance? If so, there is a known issue which has been introduced by a recent change to the channel integration for String item type (#468) and has been fixed (#477) but not yet release into the live skill. You can read [this forum post](https://community.openhab.org/t/alexa-skill-tv-not-discovered-working-if-channel-item-configured/131845) for more information. The workaround is to set the metadata parameter `channelMappings`.

**Comment by jsetton** [comment]
@erelor any chance you can clarify your use case? We are planning to cut a patch release shortly including the change mentioned above for the upcoming OH 3.3 release. Thanks.

**Comment by erelor** [comment]
Yes, I use  LG webOS binding

**Comment by jsetton** [comment]
Thanks for confirming. I will close this issue since it is a known issue and fixed by #477.
