### ISSUE TITLE
Can say "Light On" but not "Fan Medium"  in an Alexa group without full thing name "Bedroom Fan Medium" 

### ISSUE THREAD

**Issue by norem** [openhab/openhab-alexa#490]
I'm using Alexa groups i.e. in the Alexa app I have several Groups set up with an Amazon Dot in each group.

So I have a group named Bedroom, that has "Bedroom Fan" and "Bedroom Light" I can just say "light off" "light on" "light 25 percent" without speaking the room name.

When I try to use the Fan I have to speak the room name i.e. "Bedroom Fan Low/Med/High/Off" if I say "Fan Medium" it asks for what device. ( I have 3 ceiling fans. )

If I ask Alexa when in the bedroom  "what is the fan speed" with or without the room, Alexa gives me the numeric speed of the fan in the bedroom.

Oh,  and this skill is awesome!

Thanx

**Comment by jsetton** [comment]
Usage questions should be posted on the [community forum](https://community.openhab.org/c/apps-services/amazon-alexa/66) following [these guidelines](https://community.openhab.org/t/about-the-amazon-alexa-category/101194).

Anyway, this is a recurring question related to the Alexa-enabled group feature. Only a handful of display categories such as lights are supported but fans aren't. This is something out of the skill control. However, [this workaround](https://community.openhab.org/t/alexa-voice-command-room-awareness-via-oh/80480) should help accomplish what you want.

> Oh, and this skill is awesome!

Thanks 😄

**Comment by norem** [comment]
Thank you Jeremy,

 

I had a feeling this was either something that was missed because fans were new, or because Amazon has a fear of fans ;)

 

I wasn’t sure so I started with this one here, trust me I scoured google first :) but didn’t see this community section, I’ll be reading this a lot.

 

Thanx for the work around.

 

Tim
