### ISSUE TITLE
Keep getting [Error]: CliError: The CloudFormation deploy failed for Alexa region "default": Access Denied

### ISSUE THREAD

**Issue by combatistor** [openhab/openhab-alexa#509]
Hi everyone, 
I had a previous installation of a self hosted openhab-cloud and alexa skill
I decided to update to the latest version 3.2.1
I think I setup everything correctly in the AWS side, I also cleaned up the previous lambda like shown in the readme.

The problem is when I use ask deploy, I keep getting this error
```
==================== Deploy Skill Infrastructure ====================
  × Deploy Alexa skill infrastructure for region "default"
[Error]: CliError: The CloudFormation deploy failed for Alexa region "default": Access Denied
```

I tried many things but I can't get it working
I'm using windows by the way
thank you for your help

**Comment by jsetton** [comment]
This looks like an AWS permission error. You should make sure that the AWS credentials you are using have the proper policy permissions.

The official documentation is missing some policies. You should use the ones listed in https://github.com/alexa/ask-cli/issues/408.

If this doesn't resolve your issue, I would recommend using the debug parameter to get more information about the source of the error and search online for a possible solution.

**Comment by combatistor** [comment]
Thanks for your comment, I could progress a bit.

Though I'm still getting some error when deploying...

![Screenshot 2022-06-27 213147](https://user-images.githubusercontent.com/6489301/175942532-0b978c83-fb83-419f-a03e-7a5b5af9e513.png)

**Comment by combatistor** [comment]
After adjusting the policies, still getting errors

![Screenshot 2022-06-27 213740](https://user-images.githubusercontent.com/6489301/175943524-6b852ff9-c6dc-468e-95a1-522d3b949a7e.png)

**Comment by combatistor** [comment]
Continuing...

**Comment by combatistor** [comment]
getting closer maybe?

![Screenshot 2022-06-27 215104](https://user-images.githubusercontent.com/6489301/175945889-1bb1b03c-bf38-4a11-a08b-ffff47295634.png)

**Comment by combatistor** [comment]
It seems to have worked!
this is my policy json configuration

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "lambda:CreateFunction",
                "cloudformation:UpdateResource",
                "logs:DescribeLogStreams",
                "iam:CreateRole",
                "s3:CreateBucket",
                "cloudformation:DescribeStackResource",
                "iam:AttachRolePolicy",
                "s3:ListBucket",
                "iam:PutRolePolicy",
                "iam:PassRole",
                "cloudformation:CancelResourceRequest",
                "iam:DeleteRolePolicy",
                "logs:GetLogEvents",
                "cloudformation:UpdateStack",
                "lambda:DeleteFunction",
                "logs:FilterLogEvents",
                "s3:PutBucketVersioning",
                "iam:GetRole",
                "cloudformation:DeleteResource",
                "lambda:ListFunctions",
                "lambda:GetFunction",
                "cloudformation:GetResourceRequestStatus",
                "cloudformation:ListResourceRequests",
                "lambda:UpdateFunctionConfiguration",
                "cloudformation:DescribeStackResources",
                "iam:DeleteRole",
                "s3:GetBucketVersioning",
                "logs:CreateLogGroup",
                "cloudformation:DescribeStacks",
                "lambda:UpdateFunctionCode",
                "cloudformation:ListResources",
                "s3:PutObject",
                "s3:GetObject",
                "lambda:AddPermission",
                "cloudformation:GetResource",
                "cloudformation:CreateStack",
                "cloudformation:CreateResource",
                "logs:PutRetentionPolicy",
                "lambda:RemovePermission",
                "s3:GetObjectVersion"
            ],
            "Resource": "*"
        }
    ]
}
```
