### ISSUE TITLE
AlexaSkillFunction[AWS::Lambda::Function]  CREATE_FAILED

### ISSUE THREAD

**Issue by gsegatori** [openhab/openhab-alexa#519]
Hello,
with the last pull with ask deploy I get this
`[Error]: CliError: The CloudFormation deploy failed for Alexa region "default": AlexaSkillFunctionPermission[AWS::Lambda::Permission]  CREATE_FAILED (Resource creation cancelled)`

**Comment by jsetton** [comment]
This sounds like an AWS permission error. You should make sure that the AWS credentials you are using have the proper policy permissions.

https://github.com/openhab/openhab-alexa/issues/509#issuecomment-1166652060
