### ISSUE TITLE
"message": "Required parameter(s) missing in the request."

### ISSUE THREAD

**Issue by octavioj** [openhab/openhab-alexa#526]
I am following the steps outlined to get Alexa to talk to our own instance but when I get to the step:

ask deploy

I get the error:

"message": "Required parameter(s) missing in the request."

Here is the ask-resources.json

{
  "askcliResourcesVersion": "2020-03-31",
  "profiles": {
    "default": {
      "skillMetadata": {
        "src": "./skill-package"
      },
      "code": {
        "default": {
          "src": "./lambda"
        }
      },
      "skillInfrastructure": {
        "type": "@ask-cli/cfn-deployer",
        "userConfig": {
          "awsRegion": "us-east-1",
          "runtime": "nodejs16.x",
          "handler": "index.handler",
          "templatePath": "./infrastructure/cfn-deployer/skill-stack.json",
          "cfn": {
            "parameters": {
              "LambdaFunctionName": "alexa-openhab",
              "LambdaLogLevel": "info",
              "OpenHABBaseURL": "<https://MyOpenHabCloudServer>",
              "OpenHABUsername": "<myuser>,
              "OpenHABPassword": "<mypassword>"
            }
          }
        }
      }
    }
  }
}

I can access the cloud server from the web browser. I can send commands to it using POST and CUrl . But when I try to go through the step to initially deploy, I get:

Deploy configuration loaded from ask-resources.json
Deploy project for profile [default]

==================== Deploy Skill Metadata ====================
[Error]: {
  "message": "Required parameter(s) missing in the request."
}

Any idea how to troubleshoot this?

I tried ask deploy --debug and the step that fails is:

[2022-09-25T19:48:00.554Z] - DEBUG - IMPORT-PACKAGE
request-id: 073f281b-da40-4286-8644-5baa3bba23a0
POST https://api.amazonalexa.com/v1/skills/imports
status code: 400 Bad Request

**Comment by jsetton** [comment]
`"OpenHABUsername": ",`

There is a typo in your `ask-resources.json`

**Comment by octavioj** [comment]
I checked and my mistake was only when I transposed to the report. There is no type there.

It is 

"OpenHABUsername": "username",

**Comment by jsetton** [comment]
That's actually a SMAPI error. Did you configure your ASK CLI as mentioned in the deployment requirements?

**Comment by octavioj** [comment]
I re-ran the configuration and it worked now. I created a new profile and used it in the ask-resources . Thank you for the assistance.
