### ISSUE TITLE
OpenHab Alexa skill to support English(india)

### ISSUE THREAD

**Issue by gagadepp** [openhab/openhab-alexa#53]
Who can be contacted to add support for OpenHab Alexa skill to support English(India)? It's unlisted on Alexa skill store as English India is not yet supported.

**Comment by digitaldan** [comment]
Hi I submitted our app for English(India) yesterday, hopefully it will be approved soon!

**Comment by gagadepp** [comment]
Brilliant! Thank you so much! ☺️

On 27-Nov-2017 03:36, "Dan Cunningham" <notifications@github.com> wrote:

Hi I submitted our app for English(India) yesterday, hopefully it will be
approved soon!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/openhab/openhab-alexa/issues/53#issuecomment-347042380>,
or mute the thread
