### ISSUE TITLE
The Command "Stop" does not stop the Rollershutter in German

### ISSUE THREAD

**Issue by Duffy77** [openhab/openhab-alexa#530]
Hello,
in German you have to say "Rolladen Büro halt" to stop the rollershutter.
But Stop is also a common word in german.
And normally you would say "Rolladen Büro stop" or "Stoppe Rolladen Büro"

So i think the File locales\de\catalog.json should be modified  to
“@Value.Stop”: “Halt,Stop”,

Is this the right way and can you do this please?

**Comment by jsetton** [comment]
Responded in the community forum:

https://community.openhab.org/t/alexa-openhab-translation/139691/2
