### ISSUE TITLE
Openhab-Alexa English (Canada) support

### ISSUE THREAD

**Issue by velaar** [openhab/openhab-alexa#55]
At the moment the skill is not available in Canada. Any chance to get it to work? Should be an easy fix.

**Comment by digitaldan** [comment]
Yes , this should be very easy :-). I will take a look this week

**Comment by mfloren** [comment]
Also looking for this skill from Canada.

**Comment by velaar** [comment]
Any news here? Or should I run it in a dev account for now?

**Comment by digitaldan** [comment]
Hi sorry for the delay, the skill has been resubmitted to support Canada and Australia , I'll let you know here when its been approved by Amazon.

**Comment by PaulKierstead** [comment]
Thanks digitaldan!! Now Amazon, get off your tushes and get that approved!

**Comment by velaar** [comment]
Surprisingly, amazon says "We will provide feedback or publish your skill within 7 business days in most cases." any issues there?

**Comment by inchlogic** [comment]
Hello. Any update on the Australian Store? I unpacked my new dot last night and was disappointed to see no OpenHAB skill in Australia.

**Comment by velaar** [comment]
Nor in Canada. "You are not eligible to enable this skill due to geographical restrictions." 
> English (GB), English (IN), English (US), German (DE)

**Comment by henwid** [comment]
Still not available on amazon.ca

**Comment by digitaldan** [comment]
I submitted it agin to Amazon and its currently in certification, hopefully this does it.

**Comment by inchlogic** [comment]
@digitaldan did you happen to also submit for AU store?

**Comment by digitaldan** [comment]
yes, its everywhere except Japan

**Comment by inchlogic** [comment]
Awesome! Thanks @digitaldan

**Comment by menzy81** [comment]
@digitaldan any word on Australian support?

**Comment by LukeScerri** [comment]
Any updates on this one please? Either For Canada or Australia?

**Comment by digitaldan** [comment]
Hi all, good news, we finally were approved this morning and are now live in the following languages/regions:

English (UK)
English (US)
English (CA)
English (AU)
English (IN)
French (FR)
German

**Comment by menzy81** [comment]
Amazing work Dan!
