### ISSUE TITLE
Television.Channel - Mapping names to number not working

### ISSUE THREAD

**Issue by olili** [openhab/openhab-alexa#554]
Hello,

I'm not able to use German channel mapping with Alexa.
"switch TV to channel 1,2,3,..." is working. 
But "switch TV to ZDF" is not working.   

Any hint? 

![Zwischenablage01](https://user-images.githubusercontent.com/41591843/212142192-d687a319-9491-43be-9aa5-87400614ed6c.jpg)

**Comment by jsetton** [comment]
For usage questions, you should post on the [community forum](https://community.openhab.org/c/apps-services/amazon-alexa/66).
