### ISSUE TITLE
Openhab-Alexa Japanese region support 

### ISSUE THREAD

**Issue by silkycove** [openhab/openhab-alexa#56]
I have verified that Alexa openHAB skill works fine for Japanese.
Please add Japanese language (region) to the official skill’s supported language (region) list.
I did the below to verify the skill in Japanese environment.
I cloned the skill, and run it under my AWS account. I set the language of the skill to Japanese and put openhab item label in Japanese (utf-8).  I added the skill and searched devices on alexa portal. I said "Alexa, turn on floor lamp" in Japanese. The lamp was lit.

**Comment by digitaldan** [comment]
@silkycove can you help but translating https://crowdin.com/translate/openhab-alexa/47/en-ja ?
