### ISSUE TITLE
devices discovery is terminated without new devices

### ISSUE THREAD

**Issue by sqw534** [openhab/openhab-alexa#567]
Hello,

I'm using the official skill and the myopenhab.org linked successfully to the skill since a couple of years. I appreciate this great work and all contrivbuting to this.
Unfortunately do I have recognized that new devices in my openhab items files are no longer discovered by Alexa.

To verify that this is not caused by my local openhab installation (3.4.1, Raspberry Pi 3+, openhabian) or editing mistakes I have done the following steps:
- reduced the setup of Alexa items to a minimum of 12 items in one file. I have changed all items to the new metadata convention like `{alexa="Light"}` . These 12 items are already a couple of years within Alexa and I'm scared to remove them as now new are detected.
- deleted all other openhab items except the 12 from Alexa (double checked this in alexa.amazon.com)
- double-checked with curl request to "https://myopenhab.org/rest/items" only delivers the expected 12 items and no other Alexa metadata are configured via UI
- set log of openhab cloud connector to TRACE
- setup a private skill with LWA for account linking and username/password and `"OpenHABBaseURL": "https://myopenhab.org",` in ask-resources.json
- disabled the official openhab skill and successfully linked the private skill while testing
- check the log files of the Lambda function in the private skill

In the private skill log the request terminate after 10 seconds without an response:

![image](https://user-images.githubusercontent.com/49973805/219972960-6e4e57cd-84a9-46c1-8b66-70e5f5aac571.png)

By reviewing the cloud connector log files I have realized, that the answer from locale server took around 7-8 seconds.
I extended the timeout value of the lambda function to 20 seconds and now I received a response:

![image](https://user-images.githubusercontent.com/49973805/219973339-0229721f-dfcb-4a18-94ec-ce5211cfe90e.png)

All items are parsed correctly. 

I reduced the items file to 2 new items but didn't not deleted the 12 working items from Alexa to see if new items could be added via the private skill. Unfortunately are the new items not detected by Alexa. 

My questions so far are now:

- As I can't debug the official skill: Is there as well a timeout of 10 seconds and could this be extended?
- Is there a way to have a co-existence between official skill and private skill both pointing to myopenhab.org? (Minor if the offcial skill will restart working)

Thanks in advance.

**Comment by jsetton** [comment]
> As I can't debug the official skill: Is there as well a timeout of 10 seconds and could this be extended?

Correct. The reason behind it is that the Alexa SMAPI expects a synchronous [response](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-response.html) within 8 seconds.

Based on the skill logs you provided, it seems it is taking a lot of time for the skill to retrieve your items from your OH server with potentially multiple retries. How many items, including the ones not configured for Alexa, are configured on your OH server? Seeing that you are running your server on a Raspberry Pi, there could be some performance issue depending on the number of configured items and running addons.

> Is there a way to have a co-existence between official skill and private skill both pointing to myopenhab.org? (Minor if the official skill will restart working)

Unless I am missing something, I am not sure why you would want to do that. Seeing a response in the skill logs doesn't necessarily indicate that the Alexa SMAPI processed it. Based on your testing, my understanding is that extending the timeout to 20 seconds didn't help resolve your issue.

**Comment by sqw534** [comment]
Hej,

many thanks for the fast reply. This additional information gives me the correct explanation as to why extending the timeout in my private skill does not fix the problem. 
I will try to resolve the delay in the response.

Regarding coexistence: It would give me a handy debug option while still having control via Alexa up and running. But this is as already mentioned a minor one. 

Again, many thanks for your great work and swift reply. Best regards.

**Comment by jsetton** [comment]
> I have currently 270 items in open. Already reduced them from 400+ but without any significant dely reduction.

It could also be that your server is running too many addons. Also look at improving the overall performance of your Raspberry Pi enabling ZRAM if you haven't done so already. Check the health of your SD card as well.

> Regarding coexistence: It would give me a handy debug option while still having control via Alexa up and running. But this is as already mentioned a minor one.

You would need to stick to one or the other as discovered devices are tied to a specific skill on the Alexa side and therefore, you would have duplicates if you want both to coexist.
