### ISSUE TITLE
all devices are identified as TYP- switch

### ISSUE THREAD

**Issue by Stefan39135** [openhab/openhab-alexa#57]
if i use the lable ["Switchable"]  or  [“Lighting”]  all devices are identified as TYP- "Switch" in the Alexa App
but this Typ is very importnat for using Group commands like "lights on"

**Comment by jsetton** [comment]
I already submitted the change, to correct this, which was merged but apparently not deployed.

#52

**Comment by Celaeno1** [comment]
Any updates here?

**Comment by digitaldan** [comment]
This was deployed today
