### ISSUE TITLE
Support for Australia

### ISSUE THREAD

**Issue by inchlogic** [openhab/openhab-alexa#59]
When will the OpenHAB skill be In Australia?

**Comment by damianpmorris** [comment]
I want to know this too.

**Comment by digitaldan** [comment]
I have this submitted and in certification, I'll post back here if/when its approved

**Comment by idkpmiller** [comment]
As the notice of certification submission was over the 7 business days that Amazon take to assess, I can only assume the skill failed to pass certification.
Please can you update on current progress.

**Comment by digitaldan** [comment]
We did get rejected, there is an apparent issue with our demo server, I'm trying to troubleshoot it this weekend, I'm hoping to resubmit today or tomorrow.

**Comment by idkpmiller** [comment]
Good luck!
My experience is if you respond with the issue corrected fast then they
seem to only test from the points picked up, which has the impact of a fast
turnaround for resubmitted skills.

**Comment by Clifford-Foster** [comment]
Hi @digitaldan - any update?

**Comment by DevNull000** [comment]
Hi @digitaldan, could you please update on the progress... :-)

**Comment by digitaldan** [comment]
The latest news  is that Amazon will not allow our app for submission until it is ported to the V3 skills api, they no longer accept new app or even updates to v2 skills.  The good news is I have a working v3 skill, see https://github.com/digitaldan/openhab-alexa/blob/v3/README.md#version-3-v3-item-mapping .  While the extended tags in that readme are going to be changed significantly due to a new feature in ESH,  the v2 capability layer will remain and work for everyones current setup.  The v3 skill API was a big change from v2 and so our v3 app is almost all new code.

**Comment by Clifford-Foster** [comment]
Thanks @digitaldan.  For the time being I have created it as a private skill in my development console.

**Comment by Clifford-Foster** [comment]
@digitaldan I had to add a response for Authorization else I couldn't link my account.

`/**
 * Handle Authorization
 */
function handleAuthorization() {
  var result = {
    event: {
      header: {
        messageId: uuid(),
        name: "AcceptGrant.Response",
        namespace: "Alexa.Authorization",
        payloadVersion: directive.header.payloadVersion,
        correlationToken: directive.header.correlationToken
      },
      payload: {}
    }
  };
  log.debug('Authorization result ' + JSON.stringify(result));
  context.succeed(result);
}`

**Comment by LukeScerri** [comment]
Hi All, any updates here? Patiently waiting.

**Comment by Clifford-Foster** [comment]
Have you considered deploying it yourself?  It's working fine for me in Australia with the Skill.

**Comment by DevNull000** [comment]
@Clifford-Foster I am completely new to this. Any pointers on how deploy the skill for private use?
Thanks, Alex.

**Comment by digitaldan** [comment]
Hi all, good news, we finally were approved this morning and are now live in the following languages/regions:

English (UK)
English (US)
English (CA)
English (AU)
English (IN)
French (FR)
German

**Comment by damianpmorris** [comment]
Great stuff @digitaldan. Works well so far. Thanks for making this available in Australia.

**Comment by dastrix80** [comment]
Hi All

Im trying to set this up, under AWS Console when configuring the lamba and using 'Sydney' as my location, I cannot see the Alexa Smart Home Trigger unless I set it to oregon.

For Australian users, can anyone explain how to do this?

Thanks
