### ISSUE TITLE
Item with tag "CurrentTemperature" is discovered as type "other"

### ISSUE THREAD

**Issue by DonStefano** [openhab/openhab-alexa#70]
I created an openHAB item with the tag "CurrentTemperature" without using a group with the tag "Thermostat". This item was dicovered by Alexa as type "Other". When put into a group with tag "Thermostat" it was discovered as type "Thermostat". I think the item outside a group should be discovered as type "Temperature_Sensor".

**Comment by digitaldan** [comment]
I believe this is fixed in v3 , closing for now
