### ISSUE TITLE
Is it possible to implement dynamically scheduled commands?

### ISSUE THREAD

**Issue by redeye86** [openhab/openhab-alexa#81]
Due to the hotness these days, i opened the roller shutters last night to let the house cool down.
I was asking myself if it is possible to spontaneously ask Alexa to "close the roller shutters in 5 hours", so that the house can cool down but the sun won't wake me early when it comes out.

Of course this would be interesting for many other things as well. E.g. "Switch of the lights in 30 Minutes". Although it makes sense to use rules if you use it periodically, but there are many dynamic and spontaneous cases where it would make sense.

I am unsure whether this should better be handled by alexa (which means amazons needs to implement it) or would it be better to use some kind of timed command queue in openhab itself. Is it even possible with the current API? What do you think?

**Comment by jsetton** [comment]
@redeye86 The Alexa Skill API unfortunately doesn't support scheduled or timed requests currently. Hopefully, this is something that Amazon will add in the future. I have seen this topic mentioned in several Alexa-related boards. At this point, this logic would need to be handled on the OH side if possible.

**Comment by jsetton** [comment]
It looks like Amazon recently introduced [scheduling capabilities](https://developer.amazon.com/docs/device-apis/alexa-thermostatcontroller.html#hold-duration-scheduling) for Thermostat control. This is limited to Thermostat capability and duration from current time only. It doesn't resolving this issue but there is hope that Amazon will extend that support to other capabilities along with the ability to set future time.

**Comment by digitaldan** [comment]
I'm going to close for now since there is not a way of doing this, thanks.
