### ISSUE TITLE
unable to discover devices through the alexa App

### ISSUE THREAD

**Issue by vivekpratap007** [openhab/openhab-alexa#84]
Dear team,
Greetings!
Since I am configuring this Alexa skill with my own Google cloud instance which I have created with below link.
https://github.com/openhab/openhab-cloud/tree/master
I have done the testing using google assistance with my google openhab cloud server ,
but when I am configuring with alexa , facing below issue.
1-for Oauth2 configuration, when i using "login with Amazon" .But after successful account linking , when I am hitting "discover device" it saying as "discover device failed".
Looking out for help.

Thanks in Advance!

**Comment by digitaldan** [comment]
Is your config.json filled out correctly with the hostname of your cloud instance ?  see https://github.com/openhab/openhab-alexa/blob/master/config_sample.js ?  When running the skill, what does the cloud watch logs say when you discover devices?
