### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mtzro2003** [openhab/openhab-alexa#9]
HI!

I'd love to try this, but I'm having trouble going through the installation instructions.Could you please elaborate a little?
For example, first step is:

> run npm install to install the nodejs dependencies

"npm install WHAT"?
Sorry, but this "mode" thing is pretty new to me...
Thanks!

**Comment by digitaldan** [comment]
Hi,  node package manager (npm) is the standard way of installing node packages.  This is needed if you plan on using the deploy tool mentioned in the readme.  Its a bit outside the scope of that doc to explain how node works (big topic).  Not sure if you have posted yet to community.openhab.org , but that would be a better place to ask these types of questions as you will get way more visibility.  Thanks.
