### ISSUE TITLE
Alexa unable to discover devices using OH2 private cloud instance.. Error 401

### ISSUE THREAD

**Issue by dastrix80** [openhab/openhab-alexa#93]
Hi All

Im unable to discover the devices. Using the private instance of OpenHab Cloud. Any thoughts?

2018-10-17T07:37:52.458Z 8df75a26-d1df-11e8-9816-534a5dfaf4ac Input:
{
    "header": {
        "namespace": "Alexa.ConnectedHome.Discovery",
        "name": "DiscoverAppliancesRequest",
        "payloadVersion": "2",
        "messageId": "5930161b-3945-4352-a5af-937f851e9727"
    },
    "payload": {
        "accessToken": "XXXXXXXXXXXXXXJ4xMgW_onniG1-mVWFtPfEQQOcZ0kU1DlkDCDeFG7wevMW0ovYo7-64N_1i9ZMxGflJzyrL_QQ1P9RWINQJWrysHnh98kWDkTbLR5e6uEApLN3SiW00h5lUdJyvAL7n8wRjjLFem76EBDbmkiI7aZwHnvlv87ybiWSANXzyXFN5BVq9r23eqKVroEEU5xWZyWLm7VL2_0jysclgj6yV-WchqN_YNVYQWNlYQW-IAIsVocNXwtkDt7kspiFxKkzRyhp5pOSYF5Lq5DN3ndGpk2cePFLZNld68ZnroVRESEcEx2DqJIytar1227DaB5yptcK35LR6QducAiwqUA47bDnc2lepOEzeog_crr9v5_rH_aEWjKOJV8AUWY1FLT9_teaR7AEPcOt5vqWUwPbQ8U0vHUb-spheOEAWfJRGvJklLFz5niulgINRc0ywSTeikuKX5Ckl9954z5j5dVfDEOUNHNEHwGD0DjGOuxduGeGQgEUaMCn_kgeK4Ujortdx6oISt2Q0yHgVHquK0PafU2OGK8phZhZ5NwdJ39-csLBrKuTo"
    }
}


07:37:53
2018-10-17T07:37:53.411Z 8df75a26-d1df-11e8-9816-534a5dfaf4ac discoverDevices failed: Error response 401
2018-10-17T07:37:53.411Z 8df75a26-d1df-11e8-9816-534a5dfaf4ac discoverDevices failed: Error response 401

**Comment by digitaldan** [comment]
Do you have the config.js pointed to your cloud?  Did the oauth account linking work?

**Comment by dastrix80** [comment]
I found the error digitaldan. It was an NGINX issue, in the local cloud instance. I had to add a location for it inside the nginx config file

Working now.

How is V3 going??

**Comment by digitaldan** [comment]
coming along, as soon as we submit in some additional countries this week, I would like to start a beta.
